2021-02-22 05:01:34,431 - INFO - Reading existing Domain with UUID f27c063f-c6c4-434f-a616-97e72e0043e5
2021-02-22 05:01:34,465 - INFO - Using existing domain ['admin_domain'](f27c063f-c6c4-434f-a616-97e72e0043e5)
2021-02-22 05:01:35,620 - INFO - Project ctest-TestBasicPolicy-78623860 not found, creating it
2021-02-22 05:01:36,406 - INFO - Created Project:ctest-TestBasicPolicy-78623860, ID : e4a634ad-1c22-41bd-8b35-ae3362faa107 
2021-02-22 05:01:41,735 - INFO - ================================================================================
2021-02-22 05:01:41,735 - INFO - STARTING TEST    : test_basic_policy_allow_deny
2021-02-22 05:01:41,735 - INFO - TEST DESCRIPTION : 
        Create 2 Vns and allow icmp traffic between them and validate with pings
        Update the policy to deny the same traffic
        Check that pings fail
        
2021-02-22 05:01:43,084 - DEBUG - Nothing to compare xmpp stats {'192.168.7.19': {'192.168.27.20': '0', '192.168.27.34': '0'}, '192.168.7.9': {'192.168.27.20': '0', '192.168.27.34': '0'}} with
2021-02-22 05:01:43,084 - INFO - Initial checks done. Running the testcase now
2021-02-22 05:01:43,084 - INFO - 
2021-02-22 05:01:44,269 - DEBUG - Response for create_network : {'network': {'status': 'ACTIVE', 'router:external': False, 'subnets': [], 'fq_name': ['admin_domain', 'ctest-TestBasicPolicy-78623860', 'ctest-vn-56904684'], 'name': 'ctest-vn-56904684', 'admin_state_up': True, 'tenant_id': 'e4a634ad1c2241bd8b35ae3362faa107', 'created_at': None, 'updated_at': None, 'shared': False, 'port_security_enabled': True, 'project_id': 'e4a634ad1c2241bd8b35ae3362faa107', 'id': '8fd5720b-b8e9-48f7-a125-25970b84e8b7', 'description': ''}}
2021-02-22 05:01:44,609 - DEBUG - Response for create_subnet : {'subnet': {'name': '', 'enable_dhcp': True, 'network_id': '8fd5720b-b8e9-48f7-a125-25970b84e8b7', 'tenant_id': 'e4a634ad1c2241bd8b35ae3362faa107', 'created_at': '2021-02-22T05:01:43.963951', 'dns_nameservers': [], 'updated_at': '2021-02-22T05:01:43.963951', 'ipv6_ra_mode': None, 'allocation_pools': [{'start': '31.232.159.66', 'end': '31.232.159.126'}], 'gateway_ip': '31.232.159.65', 'dns_server_address': '31.232.159.66', 'ipv6_address_mode': None, 'ip_version': 4, 'host_routes': [], 'cidr': '31.232.159.64/26', 'id': '17b774eb-763e-4689-bebb-51bc4c7aa60d'}}
2021-02-22 05:01:44,663 - INFO - Created VN ctest-vn-56904684
2021-02-22 05:01:44,699 - DEBUG - VN ctest-vn-56904684 UUID is 8fd5720b-b8e9-48f7-a125-25970b84e8b7
2021-02-22 05:01:45,204 - DEBUG - Response for create_network : {'network': {'status': 'ACTIVE', 'router:external': False, 'subnets': [], 'fq_name': ['admin_domain', 'ctest-TestBasicPolicy-78623860', 'ctest-vn-46231072'], 'name': 'ctest-vn-46231072', 'admin_state_up': True, 'tenant_id': 'e4a634ad1c2241bd8b35ae3362faa107', 'created_at': None, 'updated_at': None, 'shared': False, 'port_security_enabled': True, 'project_id': 'e4a634ad1c2241bd8b35ae3362faa107', 'id': 'a5cf493d-d56a-4966-a29e-eaeb22c6e5c9', 'description': ''}}
2021-02-22 05:03:15,234 - INFO - Deleting VN ctest-vn-56904684 
2021-02-22 05:04:46,560 - ERROR - ConnectFailure
Python 3.6.8: /usr/bin/python3
Mon Feb 22 05:03:15 2021

A problem occurred in a Python script.  Here is the sequence of
function calls leading up to the error, in the order they occurred.

 /contrail-test/tcutils/wrappers.py in wrapper(self=<scripts.policy.test_policy_basic.TestBasicPolic...sanity,suite1,vcenter_compute] id=0x7fa56c389240>, *args=(), **kwargs={})
   80             log.info('Initial checks done. Running the testcase now')
   81             log.info('')
   82             result = function(self, *args, **kwargs)
   83             if self.inputs.upgrade:
   84                 pid = os.getpid()
result = None
function = <function TestBasicPolicy.test_basic_policy_allow_deny>
self = <scripts.policy.test_policy_basic.TestBasicPolic...sanity,suite1,vcenter_compute] id=0x7fa56c389240>
args = ()
kwargs = {}

 /contrail-test/scripts/policy/test_policy_basic.py in test_basic_policy_allow_deny(self=<scripts.policy.test_policy_basic.TestBasicPolic...sanity,suite1,vcenter_compute] id=0x7fa56c389240>)
   97         '''
   98         vn1_fixture = self.create_vn()
   99         vn2_fixture = self.create_vn()
  100 #        vn1_name = get_random_name('vn1')
  101 #        vn1_subnets = ['192.168.10.0/24']
vn2_fixture undefined
self = <scripts.policy.test_policy_basic.TestBasicPolic...sanity,suite1,vcenter_compute] id=0x7fa56c389240>
self.create_vn = <bound method GenericTestBase.create_vn of <scri...anity,suite1,vcenter_compute] id=0x7fa56c389240>>

 /contrail-test/common/base.py in create_vn(self=<scripts.policy.test_policy_basic.TestBasicPolic...sanity,suite1,vcenter_compute] id=0x7fa56c389240>, vn_name=None, vn_subnets=None, cleanup=True, **kwargs={})
  202         vn_fixture = self.create_only_vn(vn_name=vn_name,
  203                                      vn_subnets=vn_subnets,
  204                                      **kwargs)
  205         if cleanup:
  206             self.addCleanup(vn_fixture.cleanUp)
kwargs = {}

 /contrail-test/common/base.py in create_only_vn(cls=<class 'scripts.policy.test_policy_basic.TestBasicPolicy'>, vn_name='ctest-vn-46231072', vn_subnets=None, **kwargs={})
  195                       subnets=vn_subnets,
  196                       **kwargs)
  197         vn_fixture.setUp()
  198         return vn_fixture
  199     # end create_only_vn
vn_fixture = <vn_test.VNFixture object>
vn_fixture.setUp = <bound method VNFixture.setUp of <vn_test.VNFixture object>>

 /contrail-test/fixtures/vn_test.py in setUp(self=<vn_test.VNFixture object>)
  442     def setUp(self):
  443         super(VNFixture, self).setUp()
  444         self.create()
  445 
  446     def create(self):
self = <vn_test.VNFixture object>
self.create = <bound method VNFixture.create of <vn_test.VNFixture object>>

 /contrail-test/fixtures/vn_test.py in create(self=<vn_test.VNFixture object>)
  455             self._create_vn_api(self.vn_name, self.project_obj)
  456         else:
  457             self._create_vn_orch()
  458         if not self.obj:
  459              self.logger.debug('VN %s not present' % (self.vn_name))
self = <vn_test.VNFixture object>
self._create_vn_orch = <bound method VNFixture._create_vn_orch of <vn_test.VNFixture object>>

 /contrail-test/fixtures/vn_test.py in _create_vn_orch(self=<vn_test.VNFixture object>)
  313                                                 sriov_provider_network=self.sriov_provider_network,
  314                                                 disable_gateway=self.disable_gateway,
  315                                                 dns_nameservers_list=self.dns_nameservers_list)
  316                 if self.obj:
  317                     self.logger.info('Created VN %s' %(self.vn_name))
dns_nameservers_list undefined
self = <vn_test.VNFixture object>
self.dns_nameservers_list = None

 /contrail-test/fixtures/openstack.py in create_vn(self=<openstack.OpenstackOrchestrator object>, name='ctest-vn-46231072', subnets=[{'cidr': '145.198.90.128/26', 'enable_dhcp': True, 'ip_version': '4', 'ipam_fq_name': ['default-domain', 'default-project', 'default-network-ipam'], 'network_id': 'a5cf493d-d56a-4966-a29e-eaeb22c6e5c9'}], option='orch', **kwargs={'disable_gateway': False, 'dns_nameservers_list': None, 'enable_dhcp': True, 'ipam_fq_name': ['default-domain', 'default-project', 'default-network-ipam'], 'router_external': False, 'shared': False, 'sriov_enable': False, 'sriov_provider_network': None, 'sriov_vlan': None})
  184 
  185    def create_vn(self, name, subnets, option='orch', **kwargs):
  186        return self.quantum_h.create_network(name, subnets, **kwargs)
  187 
  188    def delete_vn(self, vn_obj, option='orch', **kwargs):
self = <openstack.OpenstackOrchestrator object>
self.quantum_h = <quantum_test.QuantumHelper object>
self.quantum_h.create_network = <bound method QuantumHelper.create_network of <quantum_test.QuantumHelper object>>
name = 'ctest-vn-46231072'
subnets = [{'cidr': '145.198.90.128/26', 'enable_dhcp': True, 'ip_version': '4', 'ipam_fq_name': ['default-domain', 'default-project', 'default-network-ipam'], 'network_id': 'a5cf493d-d56a-4966-a29e-eaeb22c6e5c9'}]
kwargs = {'disable_gateway': False, 'dns_nameservers_list': None, 'enable_dhcp': True, 'ipam_fq_name': ['default-domain', 'default-project', 'default-network-ipam'], 'router_external': False, 'shared': False, 'sriov_enable': False, 'sriov_provider_network': None, 'sriov_vlan': None}

 /contrail-test/fixtures/quantum_test.py in create_network(self=<quantum_test.QuantumHelper object>, vn_name='ctest-vn-46231072', vn_subnets=[{'cidr': '145.198.90.128/26', 'enable_dhcp': True, 'ip_version': '4', 'ipam_fq_name': ['default-domain', 'default-project', 'default-network-ipam'], 'network_id': 'a5cf493d-d56a-4966-a29e-eaeb22c6e5c9'}], ipam_fq_name=['default-domain', 'default-project', 'default-network-ipam'], shared=False, router_external=False, enable_dhcp=True, sriov_enable=False, sriov_vlan=None, sriov_provider_network=None, dns_nameservers_list=None, disable_gateway=False)
  107                 for subnet in vn_subnets:
  108                     net_rsp = self.create_subnet(
  109                         subnet, net_id, ipam_fq_name, enable_dhcp, disable_gateway,dns_nameservers_list)
  110             # end for
  111             return self.obj.show_network(network=net_id)
subnet = {'cidr': '145.198.90.128/26', 'enable_dhcp': True, 'ip_version': '4', 'ipam_fq_name': ['default-domain', 'default-project', 'default-network-ipam'], 'network_id': 'a5cf493d-d56a-4966-a29e-eaeb22c6e5c9'}
net_id = 'a5cf493d-d56a-4966-a29e-eaeb22c6e5c9'
ipam_fq_name = ['default-domain', 'default-project', 'default-network-ipam']
enable_dhcp = True
disable_gateway = False
dns_nameservers_list = None

 /contrail-test/fixtures/quantum_test.py in create_subnet(self=<quantum_test.QuantumHelper object>, subnet={'cidr': '145.198.90.128/26', 'enable_dhcp': True, 'ip_version': '4', 'ipam_fq_name': ['default-domain', 'default-project', 'default-network-ipam'], 'network_id': 'a5cf493d-d56a-4966-a29e-eaeb22c6e5c9'}, net_id='a5cf493d-d56a-4966-a29e-eaeb22c6e5c9', ipam_fq_name=['default-domain', 'default-project', 'default-network-ipam'], enable_dhcp=True, disable_gateway=False, dns_nameservers_list=None)
  127            subnet_req['gateway_ip'] = None
  128         try:
  129             subnet_rsp = self.obj.create_subnet({'subnet': subnet_req})
  130             self.logger.debug(
  131                 'Response for create_subnet : ' +
subnet_rsp undefined
self = <quantum_test.QuantumHelper object>
self.obj = <neutronclient.v2_0.client.Client object>
self.obj.create_subnet = <bound method Client.create_subnet of <neutronclient.v2_0.client.Client object>>
subnet_req = {'cidr': '145.198.90.128/26', 'enable_dhcp': True, 'ip_version': '4', 'ipam_fq_name': ['default-domain', 'default-project', 'default-network-ipam'], 'network_id': 'a5cf493d-d56a-4966-a29e-eaeb22c6e5c9'}

 /usr/local/lib/python3.6/site-packages/neutronclient/v2_0/client.py in create_subnet(self=<neutronclient.v2_0.client.Client object>, body={'subnet': {'cidr': '145.198.90.128/26', 'enable_dhcp': True, 'ip_version': '4', 'ipam_fq_name': ['default-domain', 'default-project', 'default-network-ipam'], 'network_id': 'a5cf493d-d56a-4966-a29e-eaeb22c6e5c9'}})
  846     def create_subnet(self, body=None):
  847         """Creates a new subnet."""
  848         return self.post(self.subnets_path, body=body)
  849 
  850     def update_subnet(self, subnet, body=None, revision_number=None):
self = <neutronclient.v2_0.client.Client object>
self.post = <bound method ClientBase.post of <neutronclient.v2_0.client.Client object>>
self.subnets_path = '/subnets'
body = {'subnet': {'cidr': '145.198.90.128/26', 'enable_dhcp': True, 'ip_version': '4', 'ipam_fq_name': ['default-domain', 'default-project', 'default-network-ipam'], 'network_id': 'a5cf493d-d56a-4966-a29e-eaeb22c6e5c9'}}

 /usr/local/lib/python3.6/site-packages/neutronclient/v2_0/client.py in post(self=<neutronclient.v2_0.client.Client object>, action='/subnets', body={'subnet': {'cidr': '145.198.90.128/26', 'enable_dhcp': True, 'ip_version': '4', 'ipam_fq_name': ['default-domain', 'default-project', 'default-network-ipam'], 'network_id': 'a5cf493d-d56a-4966-a29e-eaeb22c6e5c9'}}, headers=None, params=None)
  357         # Do not retry POST requests to avoid the orphan objects problem.
  358         return self.do_request("POST", action, body=body,
  359                                headers=headers, params=params)
  360 
  361     def put(self, action, body=None, headers=None, params=None):
headers = None
params = None

 /usr/local/lib/python3.6/site-packages/neutronclient/v2_0/client.py in do_request(self=<neutronclient.v2_0.client.Client object>, method='POST', action='/v2.0/subnets', body='{"subnet": {"cidr": "145.198.90.128/26", "networ...in", "default-project", "default-network-ipam"]}}', headers=None, params=None)
  280 
  281         resp, replybody = self.httpclient.do_request(action, method, body=body,
  282                                                      headers=headers)
  283 
  284         status_code = resp.status_code
headers = None

 /usr/local/lib/python3.6/site-packages/neutronclient/client.py in do_request(self=<neutronclient.client.SessionClient object>, url='/v2.0/subnets', method='POST', **kwargs={'authenticated': True, 'body': '{"subnet": {"cidr": "145.198.90.128/26", "networ...in", "default-project", "default-network-ipam"]}}', 'headers': None})
  338         kwargs.setdefault('authenticated', True)
  339         self._check_uri_length(url)
  340         return self.request(url, method, **kwargs)
  341 
  342     @property
self = <neutronclient.client.SessionClient object>
self.request = <bound method SessionClient.request of <neutronclient.client.SessionClient object>>
url = '/v2.0/subnets'
method = 'POST'
kwargs = {'authenticated': True, 'body': '{"subnet": {"cidr": "145.198.90.128/26", "networ...in", "default-project", "default-network-ipam"]}}', 'headers': None}

 /usr/local/lib/python3.6/site-packages/neutronclient/client.py in request(self=<neutronclient.client.SessionClient object>, *args=('/v2.0/subnets', 'POST'), **kwargs={'authenticated': True, 'data': '{"subnet": {"cidr": "145.198.90.128/26", "networ...in", "default-project", "default-network-ipam"]}}', 'headers': {'Accept': 'application/json', 'Content-Type': 'application/json', 'User-Agent': 'python-neutronclient', 'X-Auth-Token': 'c775cfedf7eb4d8f8bc78cbcc0fe513e'}, 'raise_exc': False})
  326 
  327         kwargs['headers'] = headers
  328         resp = super(SessionClient, self).request(*args, **kwargs)
  329         return resp, resp.text
  330 
resp undefined
builtinsuper = <class 'super'>
global SessionClient = <class 'neutronclient.client.SessionClient'>
self = <neutronclient.client.SessionClient object>
).request = <bound method SessionClient.request of <neutronclient.client.SessionClient object>>
args = ('/v2.0/subnets', 'POST')
kwargs = {'authenticated': True, 'data': '{"subnet": {"cidr": "145.198.90.128/26", "networ...in", "default-project", "default-network-ipam"]}}', 'headers': {'Accept': 'application/json', 'Content-Type': 'application/json', 'User-Agent': 'python-neutronclient', 'X-Auth-Token': 'c775cfedf7eb4d8f8bc78cbcc0fe513e'}, 'raise_exc': False}

 /usr/local/lib/python3.6/site-packages/keystoneauth1/adapter.py in request(self=<neutronclient.client.SessionClient object>, url='/v2.0/subnets', method='POST', **kwargs={'authenticated': True, 'data': '{"subnet": {"cidr": "145.198.90.128/26", "networ...in", "default-project", "default-network-ipam"]}}', 'endpoint_filter': {'interface': 'public', 'region_name': 'RegionOne', 'service_type': 'network'}, 'headers': {'Accept': 'application/json', 'Content-Type': 'application/json', 'User-Agent': 'python-neutronclient', 'X-Auth-Token': 'c775cfedf7eb4d8f8bc78cbcc0fe513e'}, 'raise_exc': False, 'rate_semaphore': <keystoneauth1._fair_semaphore.FairSemaphore object>, 'user_agent': 'python-neutronclient'})
  246             kwargs.setdefault('raise_exc', self.raise_exc)
  247 
  248         return self.session.request(url, method, **kwargs)
  249 
  250     def get_token(self, auth=None):
self = <neutronclient.client.SessionClient object>
self.session = <keystoneauth1.session.Session object>
self.session.request = <bound method Session.request of <keystoneauth1.session.Session object>>
url = '/v2.0/subnets'
method = 'POST'
kwargs = {'authenticated': True, 'data': '{"subnet": {"cidr": "145.198.90.128/26", "networ...in", "default-project", "default-network-ipam"]}}', 'endpoint_filter': {'interface': 'public', 'region_name': 'RegionOne', 'service_type': 'network'}, 'headers': {'Accept': 'application/json', 'Content-Type': 'application/json', 'User-Agent': 'python-neutronclient', 'X-Auth-Token': 'c775cfedf7eb4d8f8bc78cbcc0fe513e'}, 'raise_exc': False, 'rate_semaphore': <keystoneauth1._fair_semaphore.FairSemaphore object>, 'user_agent': 'python-neutronclient'}

 /usr/local/lib/python3.6/site-packages/keystoneauth1/session.py in request(self=<keystoneauth1.session.Session object>, url='http://192.168.7.31:9696/v2.0/subnets', method='POST', json=None, original_ip=None, user_agent='python-neutronclient', redirect=30, authenticated=True, endpoint_filter={'interface': 'public', 'region_name': 'RegionOne', 'service_type': 'network'}, auth=None, requests_auth=None, raise_exc=False, allow_reauth=True, log=True, endpoint_override=None, connect_retries=0, logger=<Logger keystoneauth.session (WARNING)>, allow=None, client_name=None, client_version=None, microversion=None, microversion_service_type=None, status_code_retries=0, retriable_status_codes=[503], rate_semaphore=<keystoneauth1._fair_semaphore.FairSemaphore object>, global_request_id=None, connect_retry_delay=None, status_code_retry_delay=None, **kwargs={'allow_redirects': False, 'cert': (None, None), 'data': '{"subnet": {"cidr": "145.198.90.128/26", "networ...in", "default-project", "default-network-ipam"]}}', 'headers': {'Accept': 'application/json', 'Content-Type': 'application/json', 'User-Agent': 'python-neutronclient', 'X-Auth-Token': 'c775cfedf7eb4d8f8bc78cbcc0fe513e'}, 'verify': False})
  911                 kwargs.update(connection_params)
  912 
  913         resp = send(**kwargs)
  914 
  915         # log callee and caller request-id for each api call
resp undefined
send = functools.partial(<bound method Session._send_re...auth1.session._Retries object at 0x7fa56a7cd6a0>)
kwargs = {'allow_redirects': False, 'cert': (None, None), 'data': '{"subnet": {"cidr": "145.198.90.128/26", "networ...in", "default-project", "default-network-ipam"]}}', 'headers': {'Accept': 'application/json', 'Content-Type': 'application/json', 'User-Agent': 'python-neutronclient', 'X-Auth-Token': 'c775cfedf7eb4d8f8bc78cbcc0fe513e'}, 'verify': False}

 /usr/local/lib/python3.6/site-packages/keystoneauth1/session.py in _send_request(self=<keystoneauth1.session.Session object>, url='http://192.168.7.31:9696/v2.0/subnets', method='POST', redirect=30, log=True, logger=<Logger keystoneauth.session (WARNING)>, split_loggers=None, connect_retries=0, status_code_retries=0, retriable_status_codes=[503], rate_semaphore=<keystoneauth1._fair_semaphore.FairSemaphore object>, connect_retry_delays=<keystoneauth1.session._Retries object>, status_code_retry_delays=<keystoneauth1.session._Retries object>, **kwargs={'allow_redirects': False, 'cert': (None, None), 'data': '{"subnet": {"cidr": "145.198.90.128/26", "networ...in", "default-project", "default-network-ipam"]}}', 'headers': {'Accept': 'application/json', 'Content-Type': 'application/json', 'User-Agent': 'python-neutronclient', 'X-Auth-Token': 'c775cfedf7eb4d8f8bc78cbcc0fe513e'}, 'verify': False})
 1018                 # and firewall blocking.
 1019                 msg = 'Unable to establish connection to %s: %s' % (url, e)
 1020                 raise exceptions.ConnectFailure(msg)
 1021             except requests.exceptions.RequestException as e:
 1022                 msg = 'Unexpected exception for %(url)s: %(error)s' % {
global exceptions = <module 'keystoneauth1.exceptions' from '/usr/lo...e-packages/keystoneauth1/exceptions/__init__.py'>
exceptions.ConnectFailure = <class 'keystoneauth1.exceptions.connection.ConnectFailure'>
msg = "Unable to establish connection to http://192.168...Remote end closed connection without response',))"
ConnectFailure: Unable to establish connection to http://192.168.7.31:9696/v2.0/subnets: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
    __cause__ = None
    __class__ = <class 'keystoneauth1.exceptions.connection.ConnectFailure'>
    __context__ = ConnectionError(ProtocolError('Connection aborte...mote end closed connection without response',)),)
    __delattr__ = <method-wrapper '__delattr__' of ConnectFailure object>
    __dict__ = {'message': "Unable to establish connection to http://192.168...Remote end closed connection without response',))"}
    __dir__ = <built-in method __dir__ of ConnectFailure object>
    __doc__ = None
    __eq__ = <method-wrapper '__eq__' of ConnectFailure object>
    __format__ = <built-in method __format__ of ConnectFailure object>
    __ge__ = <method-wrapper '__ge__' of ConnectFailure object>
    __getattribute__ = <method-wrapper '__getattribute__' of ConnectFailure object>
    __gt__ = <method-wrapper '__gt__' of ConnectFailure object>
    __hash__ = <method-wrapper '__hash__' of ConnectFailure object>
    __init__ = <bound method ClientException.__init__ of Connec...te end closed connection without response',))",)>
    __init_subclass__ = <built-in method __init_subclass__ of type object>
    __le__ = <method-wrapper '__le__' of ConnectFailure object>
    __lt__ = <method-wrapper '__lt__' of ConnectFailure object>
    __module__ = 'keystoneauth1.exceptions.connection'
    __ne__ = <method-wrapper '__ne__' of ConnectFailure object>
    __new__ = <built-in method __new__ of type object>
    __reduce__ = <built-in method __reduce__ of ConnectFailure object>
    __reduce_ex__ = <built-in method __reduce_ex__ of ConnectFailure object>
    __repr__ = <method-wrapper '__repr__' of ConnectFailure object>
    __setattr__ = <method-wrapper '__setattr__' of ConnectFailure object>
    __setstate__ = <built-in method __setstate__ of ConnectFailure object>
    __sizeof__ = <built-in method __sizeof__ of ConnectFailure object>
    __str__ = <method-wrapper '__str__' of ConnectFailure object>
    __subclasshook__ = <built-in method __subclasshook__ of type object>
    __suppress_context__ = False
    __traceback__ = <traceback object>
    __weakref__ = None
    args = ("Unable to establish connection to http://192.168...Remote end closed connection without response',))",)
    message = "Unable to establish connection to http://192.168...Remote end closed connection without response',))"
    with_traceback = <built-in method with_traceback of ConnectFailure object>

The above is a description of an error in a Python program.  Here is
the original traceback:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib64/python3.6/http/client.py", line 1346, in getresponse
    response.begin()
  File "/usr/lib64/python3.6/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python3.6/http/client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/retry.py", line 400, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.6/site-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib64/python3.6/http/client.py", line 1346, in getresponse
    response.begin()
  File "/usr/lib64/python3.6/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python3.6/http/client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/keystoneauth1/session.py", line 1004, in _send_request
    resp = self.session.request(method, url, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/contrail-test/tcutils/wrappers.py", line 82, in wrapper
    result = function(self, *args, **kwargs)
  File "/contrail-test/scripts/policy/test_policy_basic.py", line 99, in test_basic_policy_allow_deny
    vn2_fixture = self.create_vn()
  File "/contrail-test/common/base.py", line 204, in create_vn
    **kwargs)
  File "/contrail-test/common/base.py", line 197, in create_only_vn
    vn_fixture.setUp()
  File "/contrail-test/fixtures/vn_test.py", line 444, in setUp
    self.create()
  File "/contrail-test/fixtures/vn_test.py", line 457, in create
    self._create_vn_orch()
  File "/contrail-test/fixtures/vn_test.py", line 315, in _create_vn_orch
    dns_nameservers_list=self.dns_nameservers_list)
  File "/contrail-test/fixtures/openstack.py", line 186, in create_vn
    return self.quantum_h.create_network(name, subnets, **kwargs)
  File "/contrail-test/fixtures/quantum_test.py", line 109, in create_network
    subnet, net_id, ipam_fq_name, enable_dhcp, disable_gateway,dns_nameservers_list)
  File "/contrail-test/fixtures/quantum_test.py", line 129, in create_subnet
    subnet_rsp = self.obj.create_subnet({'subnet': subnet_req})
  File "/usr/local/lib/python3.6/site-packages/neutronclient/v2_0/client.py", line 848, in create_subnet
    return self.post(self.subnets_path, body=body)
  File "/usr/local/lib/python3.6/site-packages/neutronclient/v2_0/client.py", line 359, in post
    headers=headers, params=params)
  File "/usr/local/lib/python3.6/site-packages/neutronclient/v2_0/client.py", line 282, in do_request
    headers=headers)
  File "/usr/local/lib/python3.6/site-packages/neutronclient/client.py", line 340, in do_request
    return self.request(url, method, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/neutronclient/client.py", line 328, in request
    resp = super(SessionClient, self).request(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/keystoneauth1/adapter.py", line 248, in request
    return self.session.request(url, method, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/keystoneauth1/session.py", line 913, in request
    resp = send(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/keystoneauth1/session.py", line 1020, in _send_request
    raise exceptions.ConnectFailure(msg)
keystoneauth1.exceptions.connection.ConnectFailure: Unable to establish connection to http://192.168.7.31:9696/v2.0/subnets: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))



2021-02-22 05:04:50,184 - WARNING - Project ctest-TestBasicPolicy-78623860 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicy-78623860', 'ctest-vn-46231072'], 'href': 'https://192.168.7.34:8082/virtual-network/a5cf493d-d56a-4966-a29e-eaeb22c6e5c9', 'uuid': 'a5cf493d-d56a-4966-a29e-eaeb22c6e5c9'}] before deletion
2021-02-22 05:04:52,310 - WARNING - Project ctest-TestBasicPolicy-78623860 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicy-78623860', 'ctest-vn-46231072'], 'href': 'https://192.168.7.34:8082/virtual-network/a5cf493d-d56a-4966-a29e-eaeb22c6e5c9', 'uuid': 'a5cf493d-d56a-4966-a29e-eaeb22c6e5c9'}] before deletion
2021-02-22 05:04:54,438 - WARNING - Project ctest-TestBasicPolicy-78623860 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicy-78623860', 'ctest-vn-46231072'], 'href': 'https://192.168.7.34:8082/virtual-network/a5cf493d-d56a-4966-a29e-eaeb22c6e5c9', 'uuid': 'a5cf493d-d56a-4966-a29e-eaeb22c6e5c9'}] before deletion
2021-02-22 05:04:56,552 - WARNING - Project ctest-TestBasicPolicy-78623860 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicy-78623860', 'ctest-vn-46231072'], 'href': 'https://192.168.7.34:8082/virtual-network/a5cf493d-d56a-4966-a29e-eaeb22c6e5c9', 'uuid': 'a5cf493d-d56a-4966-a29e-eaeb22c6e5c9'}] before deletion
2021-02-22 05:04:58,674 - WARNING - Project ctest-TestBasicPolicy-78623860 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicy-78623860', 'ctest-vn-46231072'], 'href': 'https://192.168.7.34:8082/virtual-network/a5cf493d-d56a-4966-a29e-eaeb22c6e5c9', 'uuid': 'a5cf493d-d56a-4966-a29e-eaeb22c6e5c9'}] before deletion
2021-02-22 05:05:00,792 - WARNING - Project ctest-TestBasicPolicy-78623860 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicy-78623860', 'ctest-vn-46231072'], 'href': 'https://192.168.7.34:8082/virtual-network/a5cf493d-d56a-4966-a29e-eaeb22c6e5c9', 'uuid': 'a5cf493d-d56a-4966-a29e-eaeb22c6e5c9'}] before deletion
2021-02-22 05:05:02,901 - WARNING - Project ctest-TestBasicPolicy-78623860 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicy-78623860', 'ctest-vn-46231072'], 'href': 'https://192.168.7.34:8082/virtual-network/a5cf493d-d56a-4966-a29e-eaeb22c6e5c9', 'uuid': 'a5cf493d-d56a-4966-a29e-eaeb22c6e5c9'}] before deletion
2021-02-22 05:05:05,038 - WARNING - Project ctest-TestBasicPolicy-78623860 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicy-78623860', 'ctest-vn-46231072'], 'href': 'https://192.168.7.34:8082/virtual-network/a5cf493d-d56a-4966-a29e-eaeb22c6e5c9', 'uuid': 'a5cf493d-d56a-4966-a29e-eaeb22c6e5c9'}] before deletion
2021-02-22 05:05:07,148 - WARNING - Project ctest-TestBasicPolicy-78623860 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicy-78623860', 'ctest-vn-46231072'], 'href': 'https://192.168.7.34:8082/virtual-network/a5cf493d-d56a-4966-a29e-eaeb22c6e5c9', 'uuid': 'a5cf493d-d56a-4966-a29e-eaeb22c6e5c9'}] before deletion
2021-02-22 05:05:09,257 - WARNING - Project ctest-TestBasicPolicy-78623860 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicy-78623860', 'ctest-vn-46231072'], 'href': 'https://192.168.7.34:8082/virtual-network/a5cf493d-d56a-4966-a29e-eaeb22c6e5c9', 'uuid': 'a5cf493d-d56a-4966-a29e-eaeb22c6e5c9'}] before deletion
2021-02-22 05:05:11,370 - WARNING - Project ctest-TestBasicPolicy-78623860 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicy-78623860', 'ctest-vn-46231072'], 'href': 'https://192.168.7.34:8082/virtual-network/a5cf493d-d56a-4966-a29e-eaeb22c6e5c9', 'uuid': 'a5cf493d-d56a-4966-a29e-eaeb22c6e5c9'}] before deletion
2021-02-22 05:05:13,479 - WARNING - Project ctest-TestBasicPolicy-78623860 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicy-78623860', 'ctest-vn-46231072'], 'href': 'https://192.168.7.34:8082/virtual-network/a5cf493d-d56a-4966-a29e-eaeb22c6e5c9', 'uuid': 'a5cf493d-d56a-4966-a29e-eaeb22c6e5c9'}] before deletion
2021-02-22 05:05:15,595 - WARNING - Project ctest-TestBasicPolicy-78623860 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicy-78623860', 'ctest-vn-46231072'], 'href': 'https://192.168.7.34:8082/virtual-network/a5cf493d-d56a-4966-a29e-eaeb22c6e5c9', 'uuid': 'a5cf493d-d56a-4966-a29e-eaeb22c6e5c9'}] before deletion
2021-02-22 05:05:17,709 - WARNING - Project ctest-TestBasicPolicy-78623860 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicy-78623860', 'ctest-vn-46231072'], 'href': 'https://192.168.7.34:8082/virtual-network/a5cf493d-d56a-4966-a29e-eaeb22c6e5c9', 'uuid': 'a5cf493d-d56a-4966-a29e-eaeb22c6e5c9'}] before deletion
2021-02-22 05:05:19,808 - WARNING - Project ctest-TestBasicPolicy-78623860 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicy-78623860', 'ctest-vn-46231072'], 'href': 'https://192.168.7.34:8082/virtual-network/a5cf493d-d56a-4966-a29e-eaeb22c6e5c9', 'uuid': 'a5cf493d-d56a-4966-a29e-eaeb22c6e5c9'}] before deletion
2021-02-22 05:05:21,924 - WARNING - Project ctest-TestBasicPolicy-78623860 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicy-78623860', 'ctest-vn-46231072'], 'href': 'https://192.168.7.34:8082/virtual-network/a5cf493d-d56a-4966-a29e-eaeb22c6e5c9', 'uuid': 'a5cf493d-d56a-4966-a29e-eaeb22c6e5c9'}] before deletion
2021-02-22 05:05:24,047 - WARNING - Project ctest-TestBasicPolicy-78623860 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicy-78623860', 'ctest-vn-46231072'], 'href': 'https://192.168.7.34:8082/virtual-network/a5cf493d-d56a-4966-a29e-eaeb22c6e5c9', 'uuid': 'a5cf493d-d56a-4966-a29e-eaeb22c6e5c9'}] before deletion
2021-02-22 05:05:26,174 - WARNING - Project ctest-TestBasicPolicy-78623860 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicy-78623860', 'ctest-vn-46231072'], 'href': 'https://192.168.7.34:8082/virtual-network/a5cf493d-d56a-4966-a29e-eaeb22c6e5c9', 'uuid': 'a5cf493d-d56a-4966-a29e-eaeb22c6e5c9'}] before deletion
2021-02-22 05:05:28,301 - WARNING - Project ctest-TestBasicPolicy-78623860 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicy-78623860', 'ctest-vn-46231072'], 'href': 'https://192.168.7.34:8082/virtual-network/a5cf493d-d56a-4966-a29e-eaeb22c6e5c9', 'uuid': 'a5cf493d-d56a-4966-a29e-eaeb22c6e5c9'}] before deletion
2021-02-22 05:05:30,410 - WARNING - Project ctest-TestBasicPolicy-78623860 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicy-78623860', 'ctest-vn-46231072'], 'href': 'https://192.168.7.34:8082/virtual-network/a5cf493d-d56a-4966-a29e-eaeb22c6e5c9', 'uuid': 'a5cf493d-d56a-4966-a29e-eaeb22c6e5c9'}] before deletion
2021-02-22 05:05:32,518 - WARNING - Project ctest-TestBasicPolicy-78623860 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicy-78623860', 'ctest-vn-46231072'], 'href': 'https://192.168.7.34:8082/virtual-network/a5cf493d-d56a-4966-a29e-eaeb22c6e5c9', 'uuid': 'a5cf493d-d56a-4966-a29e-eaeb22c6e5c9'}] before deletion
2021-02-22 05:05:34,622 - WARNING - Project ctest-TestBasicPolicy-78623860 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicy-78623860', 'ctest-vn-46231072'], 'href': 'https://192.168.7.34:8082/virtual-network/a5cf493d-d56a-4966-a29e-eaeb22c6e5c9', 'uuid': 'a5cf493d-d56a-4966-a29e-eaeb22c6e5c9'}] before deletion
2021-02-22 05:05:36,740 - WARNING - Project ctest-TestBasicPolicy-78623860 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicy-78623860', 'ctest-vn-46231072'], 'href': 'https://192.168.7.34:8082/virtual-network/a5cf493d-d56a-4966-a29e-eaeb22c6e5c9', 'uuid': 'a5cf493d-d56a-4966-a29e-eaeb22c6e5c9'}] before deletion
2021-02-22 05:05:38,851 - WARNING - Project ctest-TestBasicPolicy-78623860 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicy-78623860', 'ctest-vn-46231072'], 'href': 'https://192.168.7.34:8082/virtual-network/a5cf493d-d56a-4966-a29e-eaeb22c6e5c9', 'uuid': 'a5cf493d-d56a-4966-a29e-eaeb22c6e5c9'}] before deletion
2021-02-22 05:05:40,982 - WARNING - Project ctest-TestBasicPolicy-78623860 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicy-78623860', 'ctest-vn-46231072'], 'href': 'https://192.168.7.34:8082/virtual-network/a5cf493d-d56a-4966-a29e-eaeb22c6e5c9', 'uuid': 'a5cf493d-d56a-4966-a29e-eaeb22c6e5c9'}] before deletion
2021-02-22 05:05:43,102 - WARNING - Project ctest-TestBasicPolicy-78623860 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicy-78623860', 'ctest-vn-46231072'], 'href': 'https://192.168.7.34:8082/virtual-network/a5cf493d-d56a-4966-a29e-eaeb22c6e5c9', 'uuid': 'a5cf493d-d56a-4966-a29e-eaeb22c6e5c9'}] before deletion
2021-02-22 05:05:45,230 - WARNING - Project ctest-TestBasicPolicy-78623860 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicy-78623860', 'ctest-vn-46231072'], 'href': 'https://192.168.7.34:8082/virtual-network/a5cf493d-d56a-4966-a29e-eaeb22c6e5c9', 'uuid': 'a5cf493d-d56a-4966-a29e-eaeb22c6e5c9'}] before deletion
2021-02-22 05:05:47,371 - WARNING - Project ctest-TestBasicPolicy-78623860 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicy-78623860', 'ctest-vn-46231072'], 'href': 'https://192.168.7.34:8082/virtual-network/a5cf493d-d56a-4966-a29e-eaeb22c6e5c9', 'uuid': 'a5cf493d-d56a-4966-a29e-eaeb22c6e5c9'}] before deletion
2021-02-22 05:05:49,495 - WARNING - Project ctest-TestBasicPolicy-78623860 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicy-78623860', 'ctest-vn-46231072'], 'href': 'https://192.168.7.34:8082/virtual-network/a5cf493d-d56a-4966-a29e-eaeb22c6e5c9', 'uuid': 'a5cf493d-d56a-4966-a29e-eaeb22c6e5c9'}] before deletion
2021-02-22 05:05:51,617 - WARNING - Project ctest-TestBasicPolicy-78623860 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicy-78623860', 'ctest-vn-46231072'], 'href': 'https://192.168.7.34:8082/virtual-network/a5cf493d-d56a-4966-a29e-eaeb22c6e5c9', 'uuid': 'a5cf493d-d56a-4966-a29e-eaeb22c6e5c9'}] before deletion
2021-02-22 05:05:53,738 - WARNING - Project ctest-TestBasicPolicy-78623860 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicy-78623860', 'ctest-vn-46231072'], 'href': 'https://192.168.7.34:8082/virtual-network/a5cf493d-d56a-4966-a29e-eaeb22c6e5c9', 'uuid': 'a5cf493d-d56a-4966-a29e-eaeb22c6e5c9'}] before deletion
2021-02-22 05:05:53,738 - WARNING - One or more references still present, will not delete the project ctest-TestBasicPolicy-78623860
2021-02-22 05:22:19,342 - INFO - Reading existing Domain with UUID f27c063f-c6c4-434f-a616-97e72e0043e5
2021-02-22 05:22:19,382 - INFO - Using existing domain ['admin_domain'](f27c063f-c6c4-434f-a616-97e72e0043e5)
2021-02-22 05:22:19,716 - INFO - Project ctest-TestBasicPolicy-22274781 not found, creating it
2021-02-22 05:22:20,265 - INFO - Created Project:ctest-TestBasicPolicy-22274781, ID : e3dfbfca-d1a7-4f75-8663-b21922cc40e9 
2021-02-22 05:22:23,582 - INFO - ================================================================================
2021-02-22 05:22:23,583 - INFO - STARTING TEST    : test_basic_policy_allow_deny
2021-02-22 05:22:23,583 - INFO - TEST DESCRIPTION : 
        Create 2 Vns and allow icmp traffic between them and validate with pings
        Update the policy to deny the same traffic
        Check that pings fail
        
2021-02-22 05:22:24,946 - DEBUG - Nothing to compare xmpp stats {'192.168.7.19': {'192.168.27.20': '0', '192.168.27.34': '0'}, '192.168.7.9': {'192.168.27.20': '0', '192.168.27.34': '0'}} with
2021-02-22 05:22:24,946 - INFO - Initial checks done. Running the testcase now
2021-02-22 05:22:24,946 - INFO - 
2021-02-22 05:22:26,164 - DEBUG - Response for create_network : {'network': {'status': 'ACTIVE', 'router:external': False, 'subnets': [], 'fq_name': ['admin_domain', 'ctest-TestBasicPolicy-22274781', 'ctest-vn-00096540'], 'name': 'ctest-vn-00096540', 'admin_state_up': True, 'tenant_id': 'e3dfbfcad1a74f758663b21922cc40e9', 'created_at': None, 'updated_at': None, 'shared': False, 'port_security_enabled': True, 'project_id': 'e3dfbfcad1a74f758663b21922cc40e9', 'id': 'dd3a49eb-b94e-41b9-acf8-1eae603ad71c', 'description': ''}}
2021-02-22 05:23:57,512 - ERROR - ConnectFailure
Python 3.6.8: /usr/bin/python3
Mon Feb 22 05:23:56 2021

A problem occurred in a Python script.  Here is the sequence of
function calls leading up to the error, in the order they occurred.

 /contrail-test/tcutils/wrappers.py in wrapper(self=<scripts.policy.test_policy_basic.TestBasicPolic...sanity,suite1,vcenter_compute] id=0x7ff91a1cb128>, *args=(), **kwargs={})
   80             log.info('Initial checks done. Running the testcase now')
   81             log.info('')
   82             result = function(self, *args, **kwargs)
   83             if self.inputs.upgrade:
   84                 pid = os.getpid()
result = None
function = <function TestBasicPolicy.test_basic_policy_allow_deny>
self = <scripts.policy.test_policy_basic.TestBasicPolic...sanity,suite1,vcenter_compute] id=0x7ff91a1cb128>
args = ()
kwargs = {}

 /contrail-test/scripts/policy/test_policy_basic.py in test_basic_policy_allow_deny(self=<scripts.policy.test_policy_basic.TestBasicPolic...sanity,suite1,vcenter_compute] id=0x7ff91a1cb128>)
   96         Check that pings fail
   97         '''
   98         vn1_fixture = self.create_vn()
   99         vn2_fixture = self.create_vn()
  100 #        vn1_name = get_random_name('vn1')
vn1_fixture undefined
self = <scripts.policy.test_policy_basic.TestBasicPolic...sanity,suite1,vcenter_compute] id=0x7ff91a1cb128>
self.create_vn = <bound method GenericTestBase.create_vn of <scri...anity,suite1,vcenter_compute] id=0x7ff91a1cb128>>

 /contrail-test/common/base.py in create_vn(self=<scripts.policy.test_policy_basic.TestBasicPolic...sanity,suite1,vcenter_compute] id=0x7ff91a1cb128>, vn_name=None, vn_subnets=None, cleanup=True, **kwargs={})
  202         vn_fixture = self.create_only_vn(vn_name=vn_name,
  203                                      vn_subnets=vn_subnets,
  204                                      **kwargs)
  205         if cleanup:
  206             self.addCleanup(vn_fixture.cleanUp)
kwargs = {}

 /contrail-test/common/base.py in create_only_vn(cls=<class 'scripts.policy.test_policy_basic.TestBasicPolicy'>, vn_name='ctest-vn-00096540', vn_subnets=None, **kwargs={})
  195                       subnets=vn_subnets,
  196                       **kwargs)
  197         vn_fixture.setUp()
  198         return vn_fixture
  199     # end create_only_vn
vn_fixture = <vn_test.VNFixture object>
vn_fixture.setUp = <bound method VNFixture.setUp of <vn_test.VNFixture object>>

 /contrail-test/fixtures/vn_test.py in setUp(self=<vn_test.VNFixture object>)
  442     def setUp(self):
  443         super(VNFixture, self).setUp()
  444         self.create()
  445 
  446     def create(self):
self = <vn_test.VNFixture object>
self.create = <bound method VNFixture.create of <vn_test.VNFixture object>>

 /contrail-test/fixtures/vn_test.py in create(self=<vn_test.VNFixture object>)
  455             self._create_vn_api(self.vn_name, self.project_obj)
  456         else:
  457             self._create_vn_orch()
  458         if not self.obj:
  459              self.logger.debug('VN %s not present' % (self.vn_name))
self = <vn_test.VNFixture object>
self._create_vn_orch = <bound method VNFixture._create_vn_orch of <vn_test.VNFixture object>>

 /contrail-test/fixtures/vn_test.py in _create_vn_orch(self=<vn_test.VNFixture object>)
  313                                                 sriov_provider_network=self.sriov_provider_network,
  314                                                 disable_gateway=self.disable_gateway,
  315                                                 dns_nameservers_list=self.dns_nameservers_list)
  316                 if self.obj:
  317                     self.logger.info('Created VN %s' %(self.vn_name))
dns_nameservers_list undefined
self = <vn_test.VNFixture object>
self.dns_nameservers_list = None

 /contrail-test/fixtures/openstack.py in create_vn(self=<openstack.OpenstackOrchestrator object>, name='ctest-vn-00096540', subnets=[{'cidr': '199.144.36.128/26', 'enable_dhcp': True, 'ip_version': '4', 'ipam_fq_name': ['default-domain', 'default-project', 'default-network-ipam'], 'network_id': 'dd3a49eb-b94e-41b9-acf8-1eae603ad71c'}], option='orch', **kwargs={'disable_gateway': False, 'dns_nameservers_list': None, 'enable_dhcp': True, 'ipam_fq_name': ['default-domain', 'default-project', 'default-network-ipam'], 'router_external': False, 'shared': False, 'sriov_enable': False, 'sriov_provider_network': None, 'sriov_vlan': None})
  184 
  185    def create_vn(self, name, subnets, option='orch', **kwargs):
  186        return self.quantum_h.create_network(name, subnets, **kwargs)
  187 
  188    def delete_vn(self, vn_obj, option='orch', **kwargs):
self = <openstack.OpenstackOrchestrator object>
self.quantum_h = <quantum_test.QuantumHelper object>
self.quantum_h.create_network = <bound method QuantumHelper.create_network of <quantum_test.QuantumHelper object>>
name = 'ctest-vn-00096540'
subnets = [{'cidr': '199.144.36.128/26', 'enable_dhcp': True, 'ip_version': '4', 'ipam_fq_name': ['default-domain', 'default-project', 'default-network-ipam'], 'network_id': 'dd3a49eb-b94e-41b9-acf8-1eae603ad71c'}]
kwargs = {'disable_gateway': False, 'dns_nameservers_list': None, 'enable_dhcp': True, 'ipam_fq_name': ['default-domain', 'default-project', 'default-network-ipam'], 'router_external': False, 'shared': False, 'sriov_enable': False, 'sriov_provider_network': None, 'sriov_vlan': None}

 /contrail-test/fixtures/quantum_test.py in create_network(self=<quantum_test.QuantumHelper object>, vn_name='ctest-vn-00096540', vn_subnets=[{'cidr': '199.144.36.128/26', 'enable_dhcp': True, 'ip_version': '4', 'ipam_fq_name': ['default-domain', 'default-project', 'default-network-ipam'], 'network_id': 'dd3a49eb-b94e-41b9-acf8-1eae603ad71c'}], ipam_fq_name=['default-domain', 'default-project', 'default-network-ipam'], shared=False, router_external=False, enable_dhcp=True, sriov_enable=False, sriov_vlan=None, sriov_provider_network=None, dns_nameservers_list=None, disable_gateway=False)
  107                 for subnet in vn_subnets:
  108                     net_rsp = self.create_subnet(
  109                         subnet, net_id, ipam_fq_name, enable_dhcp, disable_gateway,dns_nameservers_list)
  110             # end for
  111             return self.obj.show_network(network=net_id)
subnet = {'cidr': '199.144.36.128/26', 'enable_dhcp': True, 'ip_version': '4', 'ipam_fq_name': ['default-domain', 'default-project', 'default-network-ipam'], 'network_id': 'dd3a49eb-b94e-41b9-acf8-1eae603ad71c'}
net_id = 'dd3a49eb-b94e-41b9-acf8-1eae603ad71c'
ipam_fq_name = ['default-domain', 'default-project', 'default-network-ipam']
enable_dhcp = True
disable_gateway = False
dns_nameservers_list = None

 /contrail-test/fixtures/quantum_test.py in create_subnet(self=<quantum_test.QuantumHelper object>, subnet={'cidr': '199.144.36.128/26', 'enable_dhcp': True, 'ip_version': '4', 'ipam_fq_name': ['default-domain', 'default-project', 'default-network-ipam'], 'network_id': 'dd3a49eb-b94e-41b9-acf8-1eae603ad71c'}, net_id='dd3a49eb-b94e-41b9-acf8-1eae603ad71c', ipam_fq_name=['default-domain', 'default-project', 'default-network-ipam'], enable_dhcp=True, disable_gateway=False, dns_nameservers_list=None)
  127            subnet_req['gateway_ip'] = None
  128         try:
  129             subnet_rsp = self.obj.create_subnet({'subnet': subnet_req})
  130             self.logger.debug(
  131                 'Response for create_subnet : ' +
subnet_rsp undefined
self = <quantum_test.QuantumHelper object>
self.obj = <neutronclient.v2_0.client.Client object>
self.obj.create_subnet = <bound method Client.create_subnet of <neutronclient.v2_0.client.Client object>>
subnet_req = {'cidr': '199.144.36.128/26', 'enable_dhcp': True, 'ip_version': '4', 'ipam_fq_name': ['default-domain', 'default-project', 'default-network-ipam'], 'network_id': 'dd3a49eb-b94e-41b9-acf8-1eae603ad71c'}

 /usr/local/lib/python3.6/site-packages/neutronclient/v2_0/client.py in create_subnet(self=<neutronclient.v2_0.client.Client object>, body={'subnet': {'cidr': '199.144.36.128/26', 'enable_dhcp': True, 'ip_version': '4', 'ipam_fq_name': ['default-domain', 'default-project', 'default-network-ipam'], 'network_id': 'dd3a49eb-b94e-41b9-acf8-1eae603ad71c'}})
  846     def create_subnet(self, body=None):
  847         """Creates a new subnet."""
  848         return self.post(self.subnets_path, body=body)
  849 
  850     def update_subnet(self, subnet, body=None, revision_number=None):
self = <neutronclient.v2_0.client.Client object>
self.post = <bound method ClientBase.post of <neutronclient.v2_0.client.Client object>>
self.subnets_path = '/subnets'
body = {'subnet': {'cidr': '199.144.36.128/26', 'enable_dhcp': True, 'ip_version': '4', 'ipam_fq_name': ['default-domain', 'default-project', 'default-network-ipam'], 'network_id': 'dd3a49eb-b94e-41b9-acf8-1eae603ad71c'}}

 /usr/local/lib/python3.6/site-packages/neutronclient/v2_0/client.py in post(self=<neutronclient.v2_0.client.Client object>, action='/subnets', body={'subnet': {'cidr': '199.144.36.128/26', 'enable_dhcp': True, 'ip_version': '4', 'ipam_fq_name': ['default-domain', 'default-project', 'default-network-ipam'], 'network_id': 'dd3a49eb-b94e-41b9-acf8-1eae603ad71c'}}, headers=None, params=None)
  357         # Do not retry POST requests to avoid the orphan objects problem.
  358         return self.do_request("POST", action, body=body,
  359                                headers=headers, params=params)
  360 
  361     def put(self, action, body=None, headers=None, params=None):
headers = None
params = None

 /usr/local/lib/python3.6/site-packages/neutronclient/v2_0/client.py in do_request(self=<neutronclient.v2_0.client.Client object>, method='POST', action='/v2.0/subnets', body='{"subnet": {"cidr": "199.144.36.128/26", "networ...in", "default-project", "default-network-ipam"]}}', headers=None, params=None)
  280 
  281         resp, replybody = self.httpclient.do_request(action, method, body=body,
  282                                                      headers=headers)
  283 
  284         status_code = resp.status_code
headers = None

 /usr/local/lib/python3.6/site-packages/neutronclient/client.py in do_request(self=<neutronclient.client.SessionClient object>, url='/v2.0/subnets', method='POST', **kwargs={'authenticated': True, 'body': '{"subnet": {"cidr": "199.144.36.128/26", "networ...in", "default-project", "default-network-ipam"]}}', 'headers': None})
  338         kwargs.setdefault('authenticated', True)
  339         self._check_uri_length(url)
  340         return self.request(url, method, **kwargs)
  341 
  342     @property
self = <neutronclient.client.SessionClient object>
self.request = <bound method SessionClient.request of <neutronclient.client.SessionClient object>>
url = '/v2.0/subnets'
method = 'POST'
kwargs = {'authenticated': True, 'body': '{"subnet": {"cidr": "199.144.36.128/26", "networ...in", "default-project", "default-network-ipam"]}}', 'headers': None}

 /usr/local/lib/python3.6/site-packages/neutronclient/client.py in request(self=<neutronclient.client.SessionClient object>, *args=('/v2.0/subnets', 'POST'), **kwargs={'authenticated': True, 'data': '{"subnet": {"cidr": "199.144.36.128/26", "networ...in", "default-project", "default-network-ipam"]}}', 'headers': {'Accept': 'application/json', 'Content-Type': 'application/json', 'User-Agent': 'python-neutronclient', 'X-Auth-Token': '1c5aa963dc914f56bdf4e9c005a86753'}, 'raise_exc': False})
  326 
  327         kwargs['headers'] = headers
  328         resp = super(SessionClient, self).request(*args, **kwargs)
  329         return resp, resp.text
  330 
resp undefined
builtinsuper = <class 'super'>
global SessionClient = <class 'neutronclient.client.SessionClient'>
self = <neutronclient.client.SessionClient object>
).request = <bound method SessionClient.request of <neutronclient.client.SessionClient object>>
args = ('/v2.0/subnets', 'POST')
kwargs = {'authenticated': True, 'data': '{"subnet": {"cidr": "199.144.36.128/26", "networ...in", "default-project", "default-network-ipam"]}}', 'headers': {'Accept': 'application/json', 'Content-Type': 'application/json', 'User-Agent': 'python-neutronclient', 'X-Auth-Token': '1c5aa963dc914f56bdf4e9c005a86753'}, 'raise_exc': False}

 /usr/local/lib/python3.6/site-packages/keystoneauth1/adapter.py in request(self=<neutronclient.client.SessionClient object>, url='/v2.0/subnets', method='POST', **kwargs={'authenticated': True, 'data': '{"subnet": {"cidr": "199.144.36.128/26", "networ...in", "default-project", "default-network-ipam"]}}', 'endpoint_filter': {'interface': 'public', 'region_name': 'RegionOne', 'service_type': 'network'}, 'headers': {'Accept': 'application/json', 'Content-Type': 'application/json', 'User-Agent': 'python-neutronclient', 'X-Auth-Token': '1c5aa963dc914f56bdf4e9c005a86753'}, 'raise_exc': False, 'rate_semaphore': <keystoneauth1._fair_semaphore.FairSemaphore object>, 'user_agent': 'python-neutronclient'})
  246             kwargs.setdefault('raise_exc', self.raise_exc)
  247 
  248         return self.session.request(url, method, **kwargs)
  249 
  250     def get_token(self, auth=None):
self = <neutronclient.client.SessionClient object>
self.session = <keystoneauth1.session.Session object>
self.session.request = <bound method Session.request of <keystoneauth1.session.Session object>>
url = '/v2.0/subnets'
method = 'POST'
kwargs = {'authenticated': True, 'data': '{"subnet": {"cidr": "199.144.36.128/26", "networ...in", "default-project", "default-network-ipam"]}}', 'endpoint_filter': {'interface': 'public', 'region_name': 'RegionOne', 'service_type': 'network'}, 'headers': {'Accept': 'application/json', 'Content-Type': 'application/json', 'User-Agent': 'python-neutronclient', 'X-Auth-Token': '1c5aa963dc914f56bdf4e9c005a86753'}, 'raise_exc': False, 'rate_semaphore': <keystoneauth1._fair_semaphore.FairSemaphore object>, 'user_agent': 'python-neutronclient'}

 /usr/local/lib/python3.6/site-packages/keystoneauth1/session.py in request(self=<keystoneauth1.session.Session object>, url='http://192.168.7.31:9696/v2.0/subnets', method='POST', json=None, original_ip=None, user_agent='python-neutronclient', redirect=30, authenticated=True, endpoint_filter={'interface': 'public', 'region_name': 'RegionOne', 'service_type': 'network'}, auth=None, requests_auth=None, raise_exc=False, allow_reauth=True, log=True, endpoint_override=None, connect_retries=0, logger=<Logger keystoneauth.session (WARNING)>, allow=None, client_name=None, client_version=None, microversion=None, microversion_service_type=None, status_code_retries=0, retriable_status_codes=[503], rate_semaphore=<keystoneauth1._fair_semaphore.FairSemaphore object>, global_request_id=None, connect_retry_delay=None, status_code_retry_delay=None, **kwargs={'allow_redirects': False, 'cert': (None, None), 'data': '{"subnet": {"cidr": "199.144.36.128/26", "networ...in", "default-project", "default-network-ipam"]}}', 'headers': {'Accept': 'application/json', 'Content-Type': 'application/json', 'User-Agent': 'python-neutronclient', 'X-Auth-Token': '1c5aa963dc914f56bdf4e9c005a86753'}, 'verify': False})
  911                 kwargs.update(connection_params)
  912 
  913         resp = send(**kwargs)
  914 
  915         # log callee and caller request-id for each api call
resp undefined
send = functools.partial(<bound method Session._send_re...auth1.session._Retries object at 0x7ff9185a1cf8>)
kwargs = {'allow_redirects': False, 'cert': (None, None), 'data': '{"subnet": {"cidr": "199.144.36.128/26", "networ...in", "default-project", "default-network-ipam"]}}', 'headers': {'Accept': 'application/json', 'Content-Type': 'application/json', 'User-Agent': 'python-neutronclient', 'X-Auth-Token': '1c5aa963dc914f56bdf4e9c005a86753'}, 'verify': False}

 /usr/local/lib/python3.6/site-packages/keystoneauth1/session.py in _send_request(self=<keystoneauth1.session.Session object>, url='http://192.168.7.31:9696/v2.0/subnets', method='POST', redirect=30, log=True, logger=<Logger keystoneauth.session (WARNING)>, split_loggers=None, connect_retries=0, status_code_retries=0, retriable_status_codes=[503], rate_semaphore=<keystoneauth1._fair_semaphore.FairSemaphore object>, connect_retry_delays=<keystoneauth1.session._Retries object>, status_code_retry_delays=<keystoneauth1.session._Retries object>, **kwargs={'allow_redirects': False, 'cert': (None, None), 'data': '{"subnet": {"cidr": "199.144.36.128/26", "networ...in", "default-project", "default-network-ipam"]}}', 'headers': {'Accept': 'application/json', 'Content-Type': 'application/json', 'User-Agent': 'python-neutronclient', 'X-Auth-Token': '1c5aa963dc914f56bdf4e9c005a86753'}, 'verify': False})
 1018                 # and firewall blocking.
 1019                 msg = 'Unable to establish connection to %s: %s' % (url, e)
 1020                 raise exceptions.ConnectFailure(msg)
 1021             except requests.exceptions.RequestException as e:
 1022                 msg = 'Unexpected exception for %(url)s: %(error)s' % {
global exceptions = <module 'keystoneauth1.exceptions' from '/usr/lo...e-packages/keystoneauth1/exceptions/__init__.py'>
exceptions.ConnectFailure = <class 'keystoneauth1.exceptions.connection.ConnectFailure'>
msg = "Unable to establish connection to http://192.168...Remote end closed connection without response',))"
ConnectFailure: Unable to establish connection to http://192.168.7.31:9696/v2.0/subnets: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
    __cause__ = None
    __class__ = <class 'keystoneauth1.exceptions.connection.ConnectFailure'>
    __context__ = ConnectionError(ProtocolError('Connection aborte...mote end closed connection without response',)),)
    __delattr__ = <method-wrapper '__delattr__' of ConnectFailure object>
    __dict__ = {'message': "Unable to establish connection to http://192.168...Remote end closed connection without response',))"}
    __dir__ = <built-in method __dir__ of ConnectFailure object>
    __doc__ = None
    __eq__ = <method-wrapper '__eq__' of ConnectFailure object>
    __format__ = <built-in method __format__ of ConnectFailure object>
    __ge__ = <method-wrapper '__ge__' of ConnectFailure object>
    __getattribute__ = <method-wrapper '__getattribute__' of ConnectFailure object>
    __gt__ = <method-wrapper '__gt__' of ConnectFailure object>
    __hash__ = <method-wrapper '__hash__' of ConnectFailure object>
    __init__ = <bound method ClientException.__init__ of Connec...te end closed connection without response',))",)>
    __init_subclass__ = <built-in method __init_subclass__ of type object>
    __le__ = <method-wrapper '__le__' of ConnectFailure object>
    __lt__ = <method-wrapper '__lt__' of ConnectFailure object>
    __module__ = 'keystoneauth1.exceptions.connection'
    __ne__ = <method-wrapper '__ne__' of ConnectFailure object>
    __new__ = <built-in method __new__ of type object>
    __reduce__ = <built-in method __reduce__ of ConnectFailure object>
    __reduce_ex__ = <built-in method __reduce_ex__ of ConnectFailure object>
    __repr__ = <method-wrapper '__repr__' of ConnectFailure object>
    __setattr__ = <method-wrapper '__setattr__' of ConnectFailure object>
    __setstate__ = <built-in method __setstate__ of ConnectFailure object>
    __sizeof__ = <built-in method __sizeof__ of ConnectFailure object>
    __str__ = <method-wrapper '__str__' of ConnectFailure object>
    __subclasshook__ = <built-in method __subclasshook__ of type object>
    __suppress_context__ = False
    __traceback__ = <traceback object>
    __weakref__ = None
    args = ("Unable to establish connection to http://192.168...Remote end closed connection without response',))",)
    message = "Unable to establish connection to http://192.168...Remote end closed connection without response',))"
    with_traceback = <built-in method with_traceback of ConnectFailure object>

The above is a description of an error in a Python program.  Here is
the original traceback:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib64/python3.6/http/client.py", line 1346, in getresponse
    response.begin()
  File "/usr/lib64/python3.6/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python3.6/http/client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/retry.py", line 400, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.6/site-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib64/python3.6/http/client.py", line 1346, in getresponse
    response.begin()
  File "/usr/lib64/python3.6/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python3.6/http/client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/keystoneauth1/session.py", line 1004, in _send_request
    resp = self.session.request(method, url, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/contrail-test/tcutils/wrappers.py", line 82, in wrapper
    result = function(self, *args, **kwargs)
  File "/contrail-test/scripts/policy/test_policy_basic.py", line 98, in test_basic_policy_allow_deny
    vn1_fixture = self.create_vn()
  File "/contrail-test/common/base.py", line 204, in create_vn
    **kwargs)
  File "/contrail-test/common/base.py", line 197, in create_only_vn
    vn_fixture.setUp()
  File "/contrail-test/fixtures/vn_test.py", line 444, in setUp
    self.create()
  File "/contrail-test/fixtures/vn_test.py", line 457, in create
    self._create_vn_orch()
  File "/contrail-test/fixtures/vn_test.py", line 315, in _create_vn_orch
    dns_nameservers_list=self.dns_nameservers_list)
  File "/contrail-test/fixtures/openstack.py", line 186, in create_vn
    return self.quantum_h.create_network(name, subnets, **kwargs)
  File "/contrail-test/fixtures/quantum_test.py", line 109, in create_network
    subnet, net_id, ipam_fq_name, enable_dhcp, disable_gateway,dns_nameservers_list)
  File "/contrail-test/fixtures/quantum_test.py", line 129, in create_subnet
    subnet_rsp = self.obj.create_subnet({'subnet': subnet_req})
  File "/usr/local/lib/python3.6/site-packages/neutronclient/v2_0/client.py", line 848, in create_subnet
    return self.post(self.subnets_path, body=body)
  File "/usr/local/lib/python3.6/site-packages/neutronclient/v2_0/client.py", line 359, in post
    headers=headers, params=params)
  File "/usr/local/lib/python3.6/site-packages/neutronclient/v2_0/client.py", line 282, in do_request
    headers=headers)
  File "/usr/local/lib/python3.6/site-packages/neutronclient/client.py", line 340, in do_request
    return self.request(url, method, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/neutronclient/client.py", line 328, in request
    resp = super(SessionClient, self).request(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/keystoneauth1/adapter.py", line 248, in request
    return self.session.request(url, method, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/keystoneauth1/session.py", line 913, in request
    resp = send(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/keystoneauth1/session.py", line 1020, in _send_request
    raise exceptions.ConnectFailure(msg)
keystoneauth1.exceptions.connection.ConnectFailure: Unable to establish connection to http://192.168.7.31:9696/v2.0/subnets: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))



2021-02-22 05:23:57,554 - DEBUG - No XMPP flaps were noticed during the test
2021-02-22 05:23:57,554 - INFO - 
2021-02-22 05:23:57,554 - INFO - END TEST : test_basic_policy_allow_deny : FAILED[0:01:34]
2021-02-22 05:23:57,555 - INFO - --------------------------------------------------------------------------------
2021-02-22 05:23:57,695 - WARNING - Project ctest-TestBasicPolicy-22274781 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicy-22274781', 'ctest-vn-00096540'], 'href': 'https://192.168.7.34:8082/virtual-network/dd3a49eb-b94e-41b9-acf8-1eae603ad71c', 'uuid': 'dd3a49eb-b94e-41b9-acf8-1eae603ad71c'}] before deletion
2021-02-22 05:23:59,813 - WARNING - Project ctest-TestBasicPolicy-22274781 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicy-22274781', 'ctest-vn-00096540'], 'href': 'https://192.168.7.34:8082/virtual-network/dd3a49eb-b94e-41b9-acf8-1eae603ad71c', 'uuid': 'dd3a49eb-b94e-41b9-acf8-1eae603ad71c'}] before deletion
2021-02-22 05:24:01,922 - WARNING - Project ctest-TestBasicPolicy-22274781 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicy-22274781', 'ctest-vn-00096540'], 'href': 'https://192.168.7.34:8082/virtual-network/dd3a49eb-b94e-41b9-acf8-1eae603ad71c', 'uuid': 'dd3a49eb-b94e-41b9-acf8-1eae603ad71c'}] before deletion
2021-02-22 05:24:04,035 - WARNING - Project ctest-TestBasicPolicy-22274781 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicy-22274781', 'ctest-vn-00096540'], 'href': 'https://192.168.7.34:8082/virtual-network/dd3a49eb-b94e-41b9-acf8-1eae603ad71c', 'uuid': 'dd3a49eb-b94e-41b9-acf8-1eae603ad71c'}] before deletion
2021-02-22 05:24:06,151 - WARNING - Project ctest-TestBasicPolicy-22274781 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicy-22274781', 'ctest-vn-00096540'], 'href': 'https://192.168.7.34:8082/virtual-network/dd3a49eb-b94e-41b9-acf8-1eae603ad71c', 'uuid': 'dd3a49eb-b94e-41b9-acf8-1eae603ad71c'}] before deletion
2021-02-22 05:24:08,269 - WARNING - Project ctest-TestBasicPolicy-22274781 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicy-22274781', 'ctest-vn-00096540'], 'href': 'https://192.168.7.34:8082/virtual-network/dd3a49eb-b94e-41b9-acf8-1eae603ad71c', 'uuid': 'dd3a49eb-b94e-41b9-acf8-1eae603ad71c'}] before deletion
2021-02-22 05:24:10,553 - WARNING - Project ctest-TestBasicPolicy-22274781 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicy-22274781', 'ctest-vn-00096540'], 'href': 'https://192.168.7.34:8082/virtual-network/dd3a49eb-b94e-41b9-acf8-1eae603ad71c', 'uuid': 'dd3a49eb-b94e-41b9-acf8-1eae603ad71c'}] before deletion
2021-02-22 05:24:12,656 - WARNING - Project ctest-TestBasicPolicy-22274781 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicy-22274781', 'ctest-vn-00096540'], 'href': 'https://192.168.7.34:8082/virtual-network/dd3a49eb-b94e-41b9-acf8-1eae603ad71c', 'uuid': 'dd3a49eb-b94e-41b9-acf8-1eae603ad71c'}] before deletion
2021-02-22 05:24:14,771 - WARNING - Project ctest-TestBasicPolicy-22274781 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicy-22274781', 'ctest-vn-00096540'], 'href': 'https://192.168.7.34:8082/virtual-network/dd3a49eb-b94e-41b9-acf8-1eae603ad71c', 'uuid': 'dd3a49eb-b94e-41b9-acf8-1eae603ad71c'}] before deletion
2021-02-22 05:24:16,891 - WARNING - Project ctest-TestBasicPolicy-22274781 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicy-22274781', 'ctest-vn-00096540'], 'href': 'https://192.168.7.34:8082/virtual-network/dd3a49eb-b94e-41b9-acf8-1eae603ad71c', 'uuid': 'dd3a49eb-b94e-41b9-acf8-1eae603ad71c'}] before deletion
2021-02-22 05:24:18,993 - WARNING - Project ctest-TestBasicPolicy-22274781 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicy-22274781', 'ctest-vn-00096540'], 'href': 'https://192.168.7.34:8082/virtual-network/dd3a49eb-b94e-41b9-acf8-1eae603ad71c', 'uuid': 'dd3a49eb-b94e-41b9-acf8-1eae603ad71c'}] before deletion
2021-02-22 05:24:21,105 - WARNING - Project ctest-TestBasicPolicy-22274781 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicy-22274781', 'ctest-vn-00096540'], 'href': 'https://192.168.7.34:8082/virtual-network/dd3a49eb-b94e-41b9-acf8-1eae603ad71c', 'uuid': 'dd3a49eb-b94e-41b9-acf8-1eae603ad71c'}] before deletion
2021-02-22 05:24:23,224 - WARNING - Project ctest-TestBasicPolicy-22274781 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicy-22274781', 'ctest-vn-00096540'], 'href': 'https://192.168.7.34:8082/virtual-network/dd3a49eb-b94e-41b9-acf8-1eae603ad71c', 'uuid': 'dd3a49eb-b94e-41b9-acf8-1eae603ad71c'}] before deletion
2021-02-22 05:24:25,339 - WARNING - Project ctest-TestBasicPolicy-22274781 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicy-22274781', 'ctest-vn-00096540'], 'href': 'https://192.168.7.34:8082/virtual-network/dd3a49eb-b94e-41b9-acf8-1eae603ad71c', 'uuid': 'dd3a49eb-b94e-41b9-acf8-1eae603ad71c'}] before deletion
2021-02-22 05:24:27,456 - WARNING - Project ctest-TestBasicPolicy-22274781 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicy-22274781', 'ctest-vn-00096540'], 'href': 'https://192.168.7.34:8082/virtual-network/dd3a49eb-b94e-41b9-acf8-1eae603ad71c', 'uuid': 'dd3a49eb-b94e-41b9-acf8-1eae603ad71c'}] before deletion
2021-02-22 05:24:29,598 - WARNING - Project ctest-TestBasicPolicy-22274781 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicy-22274781', 'ctest-vn-00096540'], 'href': 'https://192.168.7.34:8082/virtual-network/dd3a49eb-b94e-41b9-acf8-1eae603ad71c', 'uuid': 'dd3a49eb-b94e-41b9-acf8-1eae603ad71c'}] before deletion
2021-02-22 05:24:31,731 - WARNING - Project ctest-TestBasicPolicy-22274781 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicy-22274781', 'ctest-vn-00096540'], 'href': 'https://192.168.7.34:8082/virtual-network/dd3a49eb-b94e-41b9-acf8-1eae603ad71c', 'uuid': 'dd3a49eb-b94e-41b9-acf8-1eae603ad71c'}] before deletion
2021-02-22 05:24:33,850 - WARNING - Project ctest-TestBasicPolicy-22274781 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicy-22274781', 'ctest-vn-00096540'], 'href': 'https://192.168.7.34:8082/virtual-network/dd3a49eb-b94e-41b9-acf8-1eae603ad71c', 'uuid': 'dd3a49eb-b94e-41b9-acf8-1eae603ad71c'}] before deletion
2021-02-22 05:24:35,972 - WARNING - Project ctest-TestBasicPolicy-22274781 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicy-22274781', 'ctest-vn-00096540'], 'href': 'https://192.168.7.34:8082/virtual-network/dd3a49eb-b94e-41b9-acf8-1eae603ad71c', 'uuid': 'dd3a49eb-b94e-41b9-acf8-1eae603ad71c'}] before deletion
2021-02-22 05:24:38,071 - WARNING - Project ctest-TestBasicPolicy-22274781 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicy-22274781', 'ctest-vn-00096540'], 'href': 'https://192.168.7.34:8082/virtual-network/dd3a49eb-b94e-41b9-acf8-1eae603ad71c', 'uuid': 'dd3a49eb-b94e-41b9-acf8-1eae603ad71c'}] before deletion
2021-02-22 05:24:40,190 - WARNING - Project ctest-TestBasicPolicy-22274781 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicy-22274781', 'ctest-vn-00096540'], 'href': 'https://192.168.7.34:8082/virtual-network/dd3a49eb-b94e-41b9-acf8-1eae603ad71c', 'uuid': 'dd3a49eb-b94e-41b9-acf8-1eae603ad71c'}] before deletion
2021-02-22 05:24:42,319 - WARNING - Project ctest-TestBasicPolicy-22274781 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicy-22274781', 'ctest-vn-00096540'], 'href': 'https://192.168.7.34:8082/virtual-network/dd3a49eb-b94e-41b9-acf8-1eae603ad71c', 'uuid': 'dd3a49eb-b94e-41b9-acf8-1eae603ad71c'}] before deletion
2021-02-22 05:24:44,432 - WARNING - Project ctest-TestBasicPolicy-22274781 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicy-22274781', 'ctest-vn-00096540'], 'href': 'https://192.168.7.34:8082/virtual-network/dd3a49eb-b94e-41b9-acf8-1eae603ad71c', 'uuid': 'dd3a49eb-b94e-41b9-acf8-1eae603ad71c'}] before deletion
2021-02-22 05:24:46,552 - WARNING - Project ctest-TestBasicPolicy-22274781 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicy-22274781', 'ctest-vn-00096540'], 'href': 'https://192.168.7.34:8082/virtual-network/dd3a49eb-b94e-41b9-acf8-1eae603ad71c', 'uuid': 'dd3a49eb-b94e-41b9-acf8-1eae603ad71c'}] before deletion
2021-02-22 05:24:48,681 - WARNING - Project ctest-TestBasicPolicy-22274781 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicy-22274781', 'ctest-vn-00096540'], 'href': 'https://192.168.7.34:8082/virtual-network/dd3a49eb-b94e-41b9-acf8-1eae603ad71c', 'uuid': 'dd3a49eb-b94e-41b9-acf8-1eae603ad71c'}] before deletion
2021-02-22 05:24:50,808 - WARNING - Project ctest-TestBasicPolicy-22274781 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicy-22274781', 'ctest-vn-00096540'], 'href': 'https://192.168.7.34:8082/virtual-network/dd3a49eb-b94e-41b9-acf8-1eae603ad71c', 'uuid': 'dd3a49eb-b94e-41b9-acf8-1eae603ad71c'}] before deletion
2021-02-22 05:24:52,914 - WARNING - Project ctest-TestBasicPolicy-22274781 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicy-22274781', 'ctest-vn-00096540'], 'href': 'https://192.168.7.34:8082/virtual-network/dd3a49eb-b94e-41b9-acf8-1eae603ad71c', 'uuid': 'dd3a49eb-b94e-41b9-acf8-1eae603ad71c'}] before deletion
2021-02-22 05:24:55,032 - WARNING - Project ctest-TestBasicPolicy-22274781 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicy-22274781', 'ctest-vn-00096540'], 'href': 'https://192.168.7.34:8082/virtual-network/dd3a49eb-b94e-41b9-acf8-1eae603ad71c', 'uuid': 'dd3a49eb-b94e-41b9-acf8-1eae603ad71c'}] before deletion
2021-02-22 05:24:57,155 - WARNING - Project ctest-TestBasicPolicy-22274781 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicy-22274781', 'ctest-vn-00096540'], 'href': 'https://192.168.7.34:8082/virtual-network/dd3a49eb-b94e-41b9-acf8-1eae603ad71c', 'uuid': 'dd3a49eb-b94e-41b9-acf8-1eae603ad71c'}] before deletion
2021-02-22 05:24:59,277 - WARNING - Project ctest-TestBasicPolicy-22274781 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicy-22274781', 'ctest-vn-00096540'], 'href': 'https://192.168.7.34:8082/virtual-network/dd3a49eb-b94e-41b9-acf8-1eae603ad71c', 'uuid': 'dd3a49eb-b94e-41b9-acf8-1eae603ad71c'}] before deletion
2021-02-22 05:25:01,397 - WARNING - Project ctest-TestBasicPolicy-22274781 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicy-22274781', 'ctest-vn-00096540'], 'href': 'https://192.168.7.34:8082/virtual-network/dd3a49eb-b94e-41b9-acf8-1eae603ad71c', 'uuid': 'dd3a49eb-b94e-41b9-acf8-1eae603ad71c'}] before deletion
2021-02-22 05:25:01,398 - WARNING - One or more references still present, will not delete the project ctest-TestBasicPolicy-22274781
2021-02-23 05:53:59,515 - INFO - Reading existing Domain with UUID f27c063f-c6c4-434f-a616-97e72e0043e5
2021-02-23 05:53:59,546 - INFO - Using existing domain ['admin_domain'](f27c063f-c6c4-434f-a616-97e72e0043e5)
2021-02-23 05:53:59,892 - INFO - Project ctest-TestBasicPolicy-91559276 not found, creating it
2021-02-23 05:54:00,603 - INFO - Created Project:ctest-TestBasicPolicy-91559276, ID : ee8f8b33-551d-4867-8326-742980486609 
2021-02-23 05:54:04,270 - INFO - ================================================================================
2021-02-23 05:54:04,271 - INFO - STARTING TEST    : test_basic_policy_allow_deny
2021-02-23 05:54:04,271 - INFO - TEST DESCRIPTION : 
        Create 2 Vns and allow icmp traffic between them and validate with pings
        Update the policy to deny the same traffic
        Check that pings fail
        
2021-02-23 05:54:04,561 - ERROR - [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/contrail-test/tcutils/cores.py", line 47, in get_cores_node
    if exists(CORE_DIR):
  File "/usr/local/lib64/python3.6/site-packages/fabric/contrib/files.py", line 31, in exists
    cmd = 'stat %s' % _expand_path(path)
  File "/usr/local/lib64/python3.6/site-packages/fabric/contrib/files.py", line 485, in _expand_path
    return path if is_win() else '"$(echo %s)"' % path
  File "/usr/local/lib64/python3.6/site-packages/fabric/contrib/files.py", line 472, in is_win
    return '"' in run('echo "Will you echo quotation marks"')
  File "/usr/local/lib64/python3.6/site-packages/fabric/network.py", line 692, in host_prompting_wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib64/python3.6/site-packages/fabric/operations.py", line 1095, in run
    shell_escape=shell_escape, capture_buffer_size=capture_buffer_size,
  File "/usr/local/lib64/python3.6/site-packages/fabric/operations.py", line 935, in _run_command
    channel=default_channel(), command=wrapped_command, pty=pty,
  File "/usr/local/lib64/python3.6/site-packages/fabric/state.py", line 435, in default_channel
    chan = _open_session()
  File "/usr/local/lib64/python3.6/site-packages/fabric/state.py", line 420, in _open_session
    session = transport.open_session(timeout=env.timeout)
  File "/usr/local/lib/python3.6/site-packages/paramiko/transport.py", line 879, in open_session
    timeout=timeout,
  File "/usr/local/lib/python3.6/site-packages/paramiko/transport.py", line 1006, in open_channel
    raise e
  File "/usr/local/lib/python3.6/site-packages/paramiko/transport.py", line 2055, in run
    ptype, m = self.packetizer.read_message()
  File "/usr/local/lib/python3.6/site-packages/paramiko/packet.py", line 459, in read_message
    header = self.read_all(self.__block_size_in, check_rekey=True)
  File "/usr/local/lib/python3.6/site-packages/paramiko/packet.py", line 301, in read_all
    x = self.__socket.recv(n)
  File "/usr/local/lib64/python3.6/site-packages/gevent/_socket3.py", line 378, in recv
    return _socket.socket.recv(self._sock, *args)
ConnectionResetError: [Errno 104] Connection reset by peer
2021-02-23 05:54:05,387 - DEBUG - Nothing to compare xmpp stats {'192.168.7.19': {'192.168.27.20': '0', '192.168.27.34': '0'}, '192.168.7.9': {'192.168.27.20': '0', '192.168.27.34': '0'}} with
2021-02-23 05:54:05,387 - INFO - Initial checks done. Running the testcase now
2021-02-23 05:54:05,387 - INFO - 
2021-02-23 05:54:07,025 - DEBUG - Response for create_network : {'network': {'status': 'ACTIVE', 'router:external': False, 'subnets': [], 'fq_name': ['admin_domain', 'ctest-TestBasicPolicy-91559276', 'ctest-vn-27666492'], 'name': 'ctest-vn-27666492', 'admin_state_up': True, 'tenant_id': 'ee8f8b33551d48678326742980486609', 'created_at': None, 'updated_at': None, 'shared': False, 'port_security_enabled': True, 'project_id': 'ee8f8b33551d48678326742980486609', 'id': '2347abad-c3d1-4384-aae7-5711fc981928', 'description': ''}}
2021-02-23 05:54:07,386 - DEBUG - Response for create_subnet : {'subnet': {'name': '', 'enable_dhcp': True, 'network_id': '2347abad-c3d1-4384-aae7-5711fc981928', 'tenant_id': 'ee8f8b33551d48678326742980486609', 'created_at': '2021-02-23T05:54:06.604526', 'dns_nameservers': [], 'updated_at': '2021-02-23T05:54:06.604526', 'ipv6_ra_mode': None, 'allocation_pools': [{'start': '93.16.217.194', 'end': '93.16.217.254'}], 'gateway_ip': '93.16.217.193', 'dns_server_address': '93.16.217.194', 'ipv6_address_mode': None, 'ip_version': 4, 'host_routes': [], 'cidr': '93.16.217.192/26', 'id': '70a7a64c-a022-4073-bcc6-9bb20549f971'}}
2021-02-23 05:54:07,439 - INFO - Created VN ctest-vn-27666492
2021-02-23 05:54:07,471 - DEBUG - VN ctest-vn-27666492 UUID is 2347abad-c3d1-4384-aae7-5711fc981928
2021-02-23 05:54:07,981 - DEBUG - Response for create_network : {'network': {'status': 'ACTIVE', 'router:external': False, 'subnets': [], 'fq_name': ['admin_domain', 'ctest-TestBasicPolicy-91559276', 'ctest-vn-86240521'], 'name': 'ctest-vn-86240521', 'admin_state_up': True, 'tenant_id': 'ee8f8b33551d48678326742980486609', 'created_at': None, 'updated_at': None, 'shared': False, 'port_security_enabled': True, 'project_id': 'ee8f8b33551d48678326742980486609', 'id': 'bc588d79-95c2-48c3-b2e4-af058ac837b3', 'description': ''}}
2021-02-23 05:55:38,011 - INFO - Deleting VN ctest-vn-27666492 
2021-02-23 05:55:38,274 - DEBUG - Response for deleting network ()
2021-02-23 05:55:40,520 - ERROR - ConnectFailure
Python 3.6.8: /usr/bin/python3
Tue Feb 23 05:55:37 2021

A problem occurred in a Python script.  Here is the sequence of
function calls leading up to the error, in the order they occurred.

 /contrail-test/tcutils/wrappers.py in wrapper(self=<scripts.policy.test_policy_basic.TestBasicPolic...sanity,suite1,vcenter_compute] id=0x7f2c5360a3c8>, *args=(), **kwargs={})
   80             log.info('Initial checks done. Running the testcase now')
   81             log.info('')
   82             result = function(self, *args, **kwargs)
   83             if self.inputs.upgrade:
   84                 pid = os.getpid()
result = None
function = <function TestBasicPolicy.test_basic_policy_allow_deny>
self = <scripts.policy.test_policy_basic.TestBasicPolic...sanity,suite1,vcenter_compute] id=0x7f2c5360a3c8>
args = ()
kwargs = {}

 /contrail-test/scripts/policy/test_policy_basic.py in test_basic_policy_allow_deny(self=<scripts.policy.test_policy_basic.TestBasicPolic...sanity,suite1,vcenter_compute] id=0x7f2c5360a3c8>)
   97         '''
   98         vn1_fixture = self.create_vn()
   99         vn2_fixture = self.create_vn()
  100 #        vn1_name = get_random_name('vn1')
  101 #        vn1_subnets = ['192.168.10.0/24']
vn2_fixture undefined
self = <scripts.policy.test_policy_basic.TestBasicPolic...sanity,suite1,vcenter_compute] id=0x7f2c5360a3c8>
self.create_vn = <bound method GenericTestBase.create_vn of <scri...anity,suite1,vcenter_compute] id=0x7f2c5360a3c8>>

 /contrail-test/common/base.py in create_vn(self=<scripts.policy.test_policy_basic.TestBasicPolic...sanity,suite1,vcenter_compute] id=0x7f2c5360a3c8>, vn_name=None, vn_subnets=None, cleanup=True, **kwargs={})
  202         vn_fixture = self.create_only_vn(vn_name=vn_name,
  203                                      vn_subnets=vn_subnets,
  204                                      **kwargs)
  205         if cleanup:
  206             self.addCleanup(vn_fixture.cleanUp)
kwargs = {}

 /contrail-test/common/base.py in create_only_vn(cls=<class 'scripts.policy.test_policy_basic.TestBasicPolicy'>, vn_name='ctest-vn-86240521', vn_subnets=None, **kwargs={})
  195                       subnets=vn_subnets,
  196                       **kwargs)
  197         vn_fixture.setUp()
  198         return vn_fixture
  199     # end create_only_vn
vn_fixture = <vn_test.VNFixture object>
vn_fixture.setUp = <bound method VNFixture.setUp of <vn_test.VNFixture object>>

 /contrail-test/fixtures/vn_test.py in setUp(self=<vn_test.VNFixture object>)
  442     def setUp(self):
  443         super(VNFixture, self).setUp()
  444         self.create()
  445 
  446     def create(self):
self = <vn_test.VNFixture object>
self.create = <bound method VNFixture.create of <vn_test.VNFixture object>>

 /contrail-test/fixtures/vn_test.py in create(self=<vn_test.VNFixture object>)
  455             self._create_vn_api(self.vn_name, self.project_obj)
  456         else:
  457             self._create_vn_orch()
  458         if not self.obj:
  459              self.logger.debug('VN %s not present' % (self.vn_name))
self = <vn_test.VNFixture object>
self._create_vn_orch = <bound method VNFixture._create_vn_orch of <vn_test.VNFixture object>>

 /contrail-test/fixtures/vn_test.py in _create_vn_orch(self=<vn_test.VNFixture object>)
  313                                                 sriov_provider_network=self.sriov_provider_network,
  314                                                 disable_gateway=self.disable_gateway,
  315                                                 dns_nameservers_list=self.dns_nameservers_list)
  316                 if self.obj:
  317                     self.logger.info('Created VN %s' %(self.vn_name))
dns_nameservers_list undefined
self = <vn_test.VNFixture object>
self.dns_nameservers_list = None

 /contrail-test/fixtures/openstack.py in create_vn(self=<openstack.OpenstackOrchestrator object>, name='ctest-vn-86240521', subnets=[{'cidr': '123.93.64.64/26', 'enable_dhcp': True, 'ip_version': '4', 'ipam_fq_name': ['default-domain', 'default-project', 'default-network-ipam'], 'network_id': 'bc588d79-95c2-48c3-b2e4-af058ac837b3'}], option='orch', **kwargs={'disable_gateway': False, 'dns_nameservers_list': None, 'enable_dhcp': True, 'ipam_fq_name': ['default-domain', 'default-project', 'default-network-ipam'], 'router_external': False, 'shared': False, 'sriov_enable': False, 'sriov_provider_network': None, 'sriov_vlan': None})
  184 
  185    def create_vn(self, name, subnets, option='orch', **kwargs):
  186        return self.quantum_h.create_network(name, subnets, **kwargs)
  187 
  188    def delete_vn(self, vn_obj, option='orch', **kwargs):
self = <openstack.OpenstackOrchestrator object>
self.quantum_h = <quantum_test.QuantumHelper object>
self.quantum_h.create_network = <bound method QuantumHelper.create_network of <quantum_test.QuantumHelper object>>
name = 'ctest-vn-86240521'
subnets = [{'cidr': '123.93.64.64/26', 'enable_dhcp': True, 'ip_version': '4', 'ipam_fq_name': ['default-domain', 'default-project', 'default-network-ipam'], 'network_id': 'bc588d79-95c2-48c3-b2e4-af058ac837b3'}]
kwargs = {'disable_gateway': False, 'dns_nameservers_list': None, 'enable_dhcp': True, 'ipam_fq_name': ['default-domain', 'default-project', 'default-network-ipam'], 'router_external': False, 'shared': False, 'sriov_enable': False, 'sriov_provider_network': None, 'sriov_vlan': None}

 /contrail-test/fixtures/quantum_test.py in create_network(self=<quantum_test.QuantumHelper object>, vn_name='ctest-vn-86240521', vn_subnets=[{'cidr': '123.93.64.64/26', 'enable_dhcp': True, 'ip_version': '4', 'ipam_fq_name': ['default-domain', 'default-project', 'default-network-ipam'], 'network_id': 'bc588d79-95c2-48c3-b2e4-af058ac837b3'}], ipam_fq_name=['default-domain', 'default-project', 'default-network-ipam'], shared=False, router_external=False, enable_dhcp=True, sriov_enable=False, sriov_vlan=None, sriov_provider_network=None, dns_nameservers_list=None, disable_gateway=False)
  107                 for subnet in vn_subnets:
  108                     net_rsp = self.create_subnet(
  109                         subnet, net_id, ipam_fq_name, enable_dhcp, disable_gateway,dns_nameservers_list)
  110             # end for
  111             return self.obj.show_network(network=net_id)
subnet = {'cidr': '123.93.64.64/26', 'enable_dhcp': True, 'ip_version': '4', 'ipam_fq_name': ['default-domain', 'default-project', 'default-network-ipam'], 'network_id': 'bc588d79-95c2-48c3-b2e4-af058ac837b3'}
net_id = 'bc588d79-95c2-48c3-b2e4-af058ac837b3'
ipam_fq_name = ['default-domain', 'default-project', 'default-network-ipam']
enable_dhcp = True
disable_gateway = False
dns_nameservers_list = None

 /contrail-test/fixtures/quantum_test.py in create_subnet(self=<quantum_test.QuantumHelper object>, subnet={'cidr': '123.93.64.64/26', 'enable_dhcp': True, 'ip_version': '4', 'ipam_fq_name': ['default-domain', 'default-project', 'default-network-ipam'], 'network_id': 'bc588d79-95c2-48c3-b2e4-af058ac837b3'}, net_id='bc588d79-95c2-48c3-b2e4-af058ac837b3', ipam_fq_name=['default-domain', 'default-project', 'default-network-ipam'], enable_dhcp=True, disable_gateway=False, dns_nameservers_list=None)
  127            subnet_req['gateway_ip'] = None
  128         try:
  129             subnet_rsp = self.obj.create_subnet({'subnet': subnet_req})
  130             self.logger.debug(
  131                 'Response for create_subnet : ' +
subnet_rsp undefined
self = <quantum_test.QuantumHelper object>
self.obj = <neutronclient.v2_0.client.Client object>
self.obj.create_subnet = <bound method Client.create_subnet of <neutronclient.v2_0.client.Client object>>
subnet_req = {'cidr': '123.93.64.64/26', 'enable_dhcp': True, 'ip_version': '4', 'ipam_fq_name': ['default-domain', 'default-project', 'default-network-ipam'], 'network_id': 'bc588d79-95c2-48c3-b2e4-af058ac837b3'}

 /usr/local/lib/python3.6/site-packages/neutronclient/v2_0/client.py in create_subnet(self=<neutronclient.v2_0.client.Client object>, body={'subnet': {'cidr': '123.93.64.64/26', 'enable_dhcp': True, 'ip_version': '4', 'ipam_fq_name': ['default-domain', 'default-project', 'default-network-ipam'], 'network_id': 'bc588d79-95c2-48c3-b2e4-af058ac837b3'}})
  846     def create_subnet(self, body=None):
  847         """Creates a new subnet."""
  848         return self.post(self.subnets_path, body=body)
  849 
  850     def update_subnet(self, subnet, body=None, revision_number=None):
self = <neutronclient.v2_0.client.Client object>
self.post = <bound method ClientBase.post of <neutronclient.v2_0.client.Client object>>
self.subnets_path = '/subnets'
body = {'subnet': {'cidr': '123.93.64.64/26', 'enable_dhcp': True, 'ip_version': '4', 'ipam_fq_name': ['default-domain', 'default-project', 'default-network-ipam'], 'network_id': 'bc588d79-95c2-48c3-b2e4-af058ac837b3'}}

 /usr/local/lib/python3.6/site-packages/neutronclient/v2_0/client.py in post(self=<neutronclient.v2_0.client.Client object>, action='/subnets', body={'subnet': {'cidr': '123.93.64.64/26', 'enable_dhcp': True, 'ip_version': '4', 'ipam_fq_name': ['default-domain', 'default-project', 'default-network-ipam'], 'network_id': 'bc588d79-95c2-48c3-b2e4-af058ac837b3'}}, headers=None, params=None)
  357         # Do not retry POST requests to avoid the orphan objects problem.
  358         return self.do_request("POST", action, body=body,
  359                                headers=headers, params=params)
  360 
  361     def put(self, action, body=None, headers=None, params=None):
headers = None
params = None

 /usr/local/lib/python3.6/site-packages/neutronclient/v2_0/client.py in do_request(self=<neutronclient.v2_0.client.Client object>, method='POST', action='/v2.0/subnets', body='{"subnet": {"cidr": "123.93.64.64/26", "network_...in", "default-project", "default-network-ipam"]}}', headers=None, params=None)
  280 
  281         resp, replybody = self.httpclient.do_request(action, method, body=body,
  282                                                      headers=headers)
  283 
  284         status_code = resp.status_code
headers = None

 /usr/local/lib/python3.6/site-packages/neutronclient/client.py in do_request(self=<neutronclient.client.SessionClient object>, url='/v2.0/subnets', method='POST', **kwargs={'authenticated': True, 'body': '{"subnet": {"cidr": "123.93.64.64/26", "network_...in", "default-project", "default-network-ipam"]}}', 'headers': None})
  338         kwargs.setdefault('authenticated', True)
  339         self._check_uri_length(url)
  340         return self.request(url, method, **kwargs)
  341 
  342     @property
self = <neutronclient.client.SessionClient object>
self.request = <bound method SessionClient.request of <neutronclient.client.SessionClient object>>
url = '/v2.0/subnets'
method = 'POST'
kwargs = {'authenticated': True, 'body': '{"subnet": {"cidr": "123.93.64.64/26", "network_...in", "default-project", "default-network-ipam"]}}', 'headers': None}

 /usr/local/lib/python3.6/site-packages/neutronclient/client.py in request(self=<neutronclient.client.SessionClient object>, *args=('/v2.0/subnets', 'POST'), **kwargs={'authenticated': True, 'data': '{"subnet": {"cidr": "123.93.64.64/26", "network_...in", "default-project", "default-network-ipam"]}}', 'headers': {'Accept': 'application/json', 'Content-Type': 'application/json', 'User-Agent': 'python-neutronclient', 'X-Auth-Token': '5b9f483e01de45b08d1f8e8dbd8d6a56'}, 'raise_exc': False})
  326 
  327         kwargs['headers'] = headers
  328         resp = super(SessionClient, self).request(*args, **kwargs)
  329         return resp, resp.text
  330 
resp undefined
builtinsuper = <class 'super'>
global SessionClient = <class 'neutronclient.client.SessionClient'>
self = <neutronclient.client.SessionClient object>
).request = <bound method SessionClient.request of <neutronclient.client.SessionClient object>>
args = ('/v2.0/subnets', 'POST')
kwargs = {'authenticated': True, 'data': '{"subnet": {"cidr": "123.93.64.64/26", "network_...in", "default-project", "default-network-ipam"]}}', 'headers': {'Accept': 'application/json', 'Content-Type': 'application/json', 'User-Agent': 'python-neutronclient', 'X-Auth-Token': '5b9f483e01de45b08d1f8e8dbd8d6a56'}, 'raise_exc': False}

 /usr/local/lib/python3.6/site-packages/keystoneauth1/adapter.py in request(self=<neutronclient.client.SessionClient object>, url='/v2.0/subnets', method='POST', **kwargs={'authenticated': True, 'data': '{"subnet": {"cidr": "123.93.64.64/26", "network_...in", "default-project", "default-network-ipam"]}}', 'endpoint_filter': {'interface': 'public', 'region_name': 'RegionOne', 'service_type': 'network'}, 'headers': {'Accept': 'application/json', 'Content-Type': 'application/json', 'User-Agent': 'python-neutronclient', 'X-Auth-Token': '5b9f483e01de45b08d1f8e8dbd8d6a56'}, 'raise_exc': False, 'rate_semaphore': <keystoneauth1._fair_semaphore.FairSemaphore object>, 'user_agent': 'python-neutronclient'})
  246             kwargs.setdefault('raise_exc', self.raise_exc)
  247 
  248         return self.session.request(url, method, **kwargs)
  249 
  250     def get_token(self, auth=None):
self = <neutronclient.client.SessionClient object>
self.session = <keystoneauth1.session.Session object>
self.session.request = <bound method Session.request of <keystoneauth1.session.Session object>>
url = '/v2.0/subnets'
method = 'POST'
kwargs = {'authenticated': True, 'data': '{"subnet": {"cidr": "123.93.64.64/26", "network_...in", "default-project", "default-network-ipam"]}}', 'endpoint_filter': {'interface': 'public', 'region_name': 'RegionOne', 'service_type': 'network'}, 'headers': {'Accept': 'application/json', 'Content-Type': 'application/json', 'User-Agent': 'python-neutronclient', 'X-Auth-Token': '5b9f483e01de45b08d1f8e8dbd8d6a56'}, 'raise_exc': False, 'rate_semaphore': <keystoneauth1._fair_semaphore.FairSemaphore object>, 'user_agent': 'python-neutronclient'}

 /usr/local/lib/python3.6/site-packages/keystoneauth1/session.py in request(self=<keystoneauth1.session.Session object>, url='http://192.168.7.31:9696/v2.0/subnets', method='POST', json=None, original_ip=None, user_agent='python-neutronclient', redirect=30, authenticated=True, endpoint_filter={'interface': 'public', 'region_name': 'RegionOne', 'service_type': 'network'}, auth=None, requests_auth=None, raise_exc=False, allow_reauth=True, log=True, endpoint_override=None, connect_retries=0, logger=<Logger keystoneauth.session (WARNING)>, allow=None, client_name=None, client_version=None, microversion=None, microversion_service_type=None, status_code_retries=0, retriable_status_codes=[503], rate_semaphore=<keystoneauth1._fair_semaphore.FairSemaphore object>, global_request_id=None, connect_retry_delay=None, status_code_retry_delay=None, **kwargs={'allow_redirects': False, 'cert': (None, None), 'data': '{"subnet": {"cidr": "123.93.64.64/26", "network_...in", "default-project", "default-network-ipam"]}}', 'headers': {'Accept': 'application/json', 'Content-Type': 'application/json', 'User-Agent': 'python-neutronclient', 'X-Auth-Token': '5b9f483e01de45b08d1f8e8dbd8d6a56'}, 'verify': False})
  911                 kwargs.update(connection_params)
  912 
  913         resp = send(**kwargs)
  914 
  915         # log callee and caller request-id for each api call
resp undefined
send = functools.partial(<bound method Session._send_re...auth1.session._Retries object at 0x7f2c526c4ba8>)
kwargs = {'allow_redirects': False, 'cert': (None, None), 'data': '{"subnet": {"cidr": "123.93.64.64/26", "network_...in", "default-project", "default-network-ipam"]}}', 'headers': {'Accept': 'application/json', 'Content-Type': 'application/json', 'User-Agent': 'python-neutronclient', 'X-Auth-Token': '5b9f483e01de45b08d1f8e8dbd8d6a56'}, 'verify': False}

 /usr/local/lib/python3.6/site-packages/keystoneauth1/session.py in _send_request(self=<keystoneauth1.session.Session object>, url='http://192.168.7.31:9696/v2.0/subnets', method='POST', redirect=30, log=True, logger=<Logger keystoneauth.session (WARNING)>, split_loggers=None, connect_retries=0, status_code_retries=0, retriable_status_codes=[503], rate_semaphore=<keystoneauth1._fair_semaphore.FairSemaphore object>, connect_retry_delays=<keystoneauth1.session._Retries object>, status_code_retry_delays=<keystoneauth1.session._Retries object>, **kwargs={'allow_redirects': False, 'cert': (None, None), 'data': '{"subnet": {"cidr": "123.93.64.64/26", "network_...in", "default-project", "default-network-ipam"]}}', 'headers': {'Accept': 'application/json', 'Content-Type': 'application/json', 'User-Agent': 'python-neutronclient', 'X-Auth-Token': '5b9f483e01de45b08d1f8e8dbd8d6a56'}, 'verify': False})
 1018                 # and firewall blocking.
 1019                 msg = 'Unable to establish connection to %s: %s' % (url, e)
 1020                 raise exceptions.ConnectFailure(msg)
 1021             except requests.exceptions.RequestException as e:
 1022                 msg = 'Unexpected exception for %(url)s: %(error)s' % {
global exceptions = <module 'keystoneauth1.exceptions' from '/usr/lo...e-packages/keystoneauth1/exceptions/__init__.py'>
exceptions.ConnectFailure = <class 'keystoneauth1.exceptions.connection.ConnectFailure'>
msg = "Unable to establish connection to http://192.168...Remote end closed connection without response',))"
ConnectFailure: Unable to establish connection to http://192.168.7.31:9696/v2.0/subnets: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
    __cause__ = None
    __class__ = <class 'keystoneauth1.exceptions.connection.ConnectFailure'>
    __context__ = ConnectionError(ProtocolError('Connection aborte...mote end closed connection without response',)),)
    __delattr__ = <method-wrapper '__delattr__' of ConnectFailure object>
    __dict__ = {'message': "Unable to establish connection to http://192.168...Remote end closed connection without response',))"}
    __dir__ = <built-in method __dir__ of ConnectFailure object>
    __doc__ = None
    __eq__ = <method-wrapper '__eq__' of ConnectFailure object>
    __format__ = <built-in method __format__ of ConnectFailure object>
    __ge__ = <method-wrapper '__ge__' of ConnectFailure object>
    __getattribute__ = <method-wrapper '__getattribute__' of ConnectFailure object>
    __gt__ = <method-wrapper '__gt__' of ConnectFailure object>
    __hash__ = <method-wrapper '__hash__' of ConnectFailure object>
    __init__ = <bound method ClientException.__init__ of Connec...te end closed connection without response',))",)>
    __init_subclass__ = <built-in method __init_subclass__ of type object>
    __le__ = <method-wrapper '__le__' of ConnectFailure object>
    __lt__ = <method-wrapper '__lt__' of ConnectFailure object>
    __module__ = 'keystoneauth1.exceptions.connection'
    __ne__ = <method-wrapper '__ne__' of ConnectFailure object>
    __new__ = <built-in method __new__ of type object>
    __reduce__ = <built-in method __reduce__ of ConnectFailure object>
    __reduce_ex__ = <built-in method __reduce_ex__ of ConnectFailure object>
    __repr__ = <method-wrapper '__repr__' of ConnectFailure object>
    __setattr__ = <method-wrapper '__setattr__' of ConnectFailure object>
    __setstate__ = <built-in method __setstate__ of ConnectFailure object>
    __sizeof__ = <built-in method __sizeof__ of ConnectFailure object>
    __str__ = <method-wrapper '__str__' of ConnectFailure object>
    __subclasshook__ = <built-in method __subclasshook__ of type object>
    __suppress_context__ = False
    __traceback__ = <traceback object>
    __weakref__ = None
    args = ("Unable to establish connection to http://192.168...Remote end closed connection without response',))",)
    message = "Unable to establish connection to http://192.168...Remote end closed connection without response',))"
    with_traceback = <built-in method with_traceback of ConnectFailure object>

The above is a description of an error in a Python program.  Here is
the original traceback:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib64/python3.6/http/client.py", line 1346, in getresponse
    response.begin()
  File "/usr/lib64/python3.6/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python3.6/http/client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/retry.py", line 400, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.6/site-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib64/python3.6/http/client.py", line 1346, in getresponse
    response.begin()
  File "/usr/lib64/python3.6/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python3.6/http/client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/keystoneauth1/session.py", line 1004, in _send_request
    resp = self.session.request(method, url, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/contrail-test/tcutils/wrappers.py", line 82, in wrapper
    result = function(self, *args, **kwargs)
  File "/contrail-test/scripts/policy/test_policy_basic.py", line 99, in test_basic_policy_allow_deny
    vn2_fixture = self.create_vn()
  File "/contrail-test/common/base.py", line 204, in create_vn
    **kwargs)
  File "/contrail-test/common/base.py", line 197, in create_only_vn
    vn_fixture.setUp()
  File "/contrail-test/fixtures/vn_test.py", line 444, in setUp
    self.create()
  File "/contrail-test/fixtures/vn_test.py", line 457, in create
    self._create_vn_orch()
  File "/contrail-test/fixtures/vn_test.py", line 315, in _create_vn_orch
    dns_nameservers_list=self.dns_nameservers_list)
  File "/contrail-test/fixtures/openstack.py", line 186, in create_vn
    return self.quantum_h.create_network(name, subnets, **kwargs)
  File "/contrail-test/fixtures/quantum_test.py", line 109, in create_network
    subnet, net_id, ipam_fq_name, enable_dhcp, disable_gateway,dns_nameservers_list)
  File "/contrail-test/fixtures/quantum_test.py", line 129, in create_subnet
    subnet_rsp = self.obj.create_subnet({'subnet': subnet_req})
  File "/usr/local/lib/python3.6/site-packages/neutronclient/v2_0/client.py", line 848, in create_subnet
    return self.post(self.subnets_path, body=body)
  File "/usr/local/lib/python3.6/site-packages/neutronclient/v2_0/client.py", line 359, in post
    headers=headers, params=params)
  File "/usr/local/lib/python3.6/site-packages/neutronclient/v2_0/client.py", line 282, in do_request
    headers=headers)
  File "/usr/local/lib/python3.6/site-packages/neutronclient/client.py", line 340, in do_request
    return self.request(url, method, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/neutronclient/client.py", line 328, in request
    resp = super(SessionClient, self).request(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/keystoneauth1/adapter.py", line 248, in request
    return self.session.request(url, method, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/keystoneauth1/session.py", line 913, in request
    resp = send(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/keystoneauth1/session.py", line 1020, in _send_request
    raise exceptions.ConnectFailure(msg)
keystoneauth1.exceptions.connection.ConnectFailure: Unable to establish connection to http://192.168.7.31:9696/v2.0/subnets: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))



2021-02-23 05:55:40,565 - DEBUG - No XMPP flaps were noticed during the test
2021-02-23 05:55:40,565 - INFO - 
2021-02-23 05:55:40,565 - INFO - END TEST : test_basic_policy_allow_deny : FAILED[0:01:36]
2021-02-23 05:55:40,565 - INFO - --------------------------------------------------------------------------------
2021-02-23 05:55:40,691 - WARNING - Project ctest-TestBasicPolicy-91559276 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicy-91559276', 'ctest-vn-86240521'], 'href': 'https://192.168.7.34:8082/virtual-network/bc588d79-95c2-48c3-b2e4-af058ac837b3', 'uuid': 'bc588d79-95c2-48c3-b2e4-af058ac837b3'}] before deletion
2021-02-23 05:55:42,804 - WARNING - Project ctest-TestBasicPolicy-91559276 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicy-91559276', 'ctest-vn-86240521'], 'href': 'https://192.168.7.34:8082/virtual-network/bc588d79-95c2-48c3-b2e4-af058ac837b3', 'uuid': 'bc588d79-95c2-48c3-b2e4-af058ac837b3'}] before deletion
2021-02-23 05:55:44,918 - WARNING - Project ctest-TestBasicPolicy-91559276 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicy-91559276', 'ctest-vn-86240521'], 'href': 'https://192.168.7.34:8082/virtual-network/bc588d79-95c2-48c3-b2e4-af058ac837b3', 'uuid': 'bc588d79-95c2-48c3-b2e4-af058ac837b3'}] before deletion
2021-02-23 05:55:47,041 - WARNING - Project ctest-TestBasicPolicy-91559276 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicy-91559276', 'ctest-vn-86240521'], 'href': 'https://192.168.7.34:8082/virtual-network/bc588d79-95c2-48c3-b2e4-af058ac837b3', 'uuid': 'bc588d79-95c2-48c3-b2e4-af058ac837b3'}] before deletion
2021-02-23 05:55:49,161 - WARNING - Project ctest-TestBasicPolicy-91559276 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicy-91559276', 'ctest-vn-86240521'], 'href': 'https://192.168.7.34:8082/virtual-network/bc588d79-95c2-48c3-b2e4-af058ac837b3', 'uuid': 'bc588d79-95c2-48c3-b2e4-af058ac837b3'}] before deletion
2021-02-23 05:55:51,286 - WARNING - Project ctest-TestBasicPolicy-91559276 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicy-91559276', 'ctest-vn-86240521'], 'href': 'https://192.168.7.34:8082/virtual-network/bc588d79-95c2-48c3-b2e4-af058ac837b3', 'uuid': 'bc588d79-95c2-48c3-b2e4-af058ac837b3'}] before deletion
2021-02-23 05:55:53,399 - WARNING - Project ctest-TestBasicPolicy-91559276 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicy-91559276', 'ctest-vn-86240521'], 'href': 'https://192.168.7.34:8082/virtual-network/bc588d79-95c2-48c3-b2e4-af058ac837b3', 'uuid': 'bc588d79-95c2-48c3-b2e4-af058ac837b3'}] before deletion
2021-02-23 05:55:55,518 - WARNING - Project ctest-TestBasicPolicy-91559276 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicy-91559276', 'ctest-vn-86240521'], 'href': 'https://192.168.7.34:8082/virtual-network/bc588d79-95c2-48c3-b2e4-af058ac837b3', 'uuid': 'bc588d79-95c2-48c3-b2e4-af058ac837b3'}] before deletion
2021-02-23 05:55:57,646 - WARNING - Project ctest-TestBasicPolicy-91559276 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicy-91559276', 'ctest-vn-86240521'], 'href': 'https://192.168.7.34:8082/virtual-network/bc588d79-95c2-48c3-b2e4-af058ac837b3', 'uuid': 'bc588d79-95c2-48c3-b2e4-af058ac837b3'}] before deletion
2021-02-23 05:55:59,752 - WARNING - Project ctest-TestBasicPolicy-91559276 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicy-91559276', 'ctest-vn-86240521'], 'href': 'https://192.168.7.34:8082/virtual-network/bc588d79-95c2-48c3-b2e4-af058ac837b3', 'uuid': 'bc588d79-95c2-48c3-b2e4-af058ac837b3'}] before deletion
2021-02-23 05:56:01,862 - WARNING - Project ctest-TestBasicPolicy-91559276 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicy-91559276', 'ctest-vn-86240521'], 'href': 'https://192.168.7.34:8082/virtual-network/bc588d79-95c2-48c3-b2e4-af058ac837b3', 'uuid': 'bc588d79-95c2-48c3-b2e4-af058ac837b3'}] before deletion
2021-02-23 05:56:03,991 - WARNING - Project ctest-TestBasicPolicy-91559276 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicy-91559276', 'ctest-vn-86240521'], 'href': 'https://192.168.7.34:8082/virtual-network/bc588d79-95c2-48c3-b2e4-af058ac837b3', 'uuid': 'bc588d79-95c2-48c3-b2e4-af058ac837b3'}] before deletion
2021-02-23 05:56:06,095 - WARNING - Project ctest-TestBasicPolicy-91559276 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicy-91559276', 'ctest-vn-86240521'], 'href': 'https://192.168.7.34:8082/virtual-network/bc588d79-95c2-48c3-b2e4-af058ac837b3', 'uuid': 'bc588d79-95c2-48c3-b2e4-af058ac837b3'}] before deletion
2021-02-23 05:56:08,209 - WARNING - Project ctest-TestBasicPolicy-91559276 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicy-91559276', 'ctest-vn-86240521'], 'href': 'https://192.168.7.34:8082/virtual-network/bc588d79-95c2-48c3-b2e4-af058ac837b3', 'uuid': 'bc588d79-95c2-48c3-b2e4-af058ac837b3'}] before deletion
2021-02-23 05:56:10,397 - WARNING - Project ctest-TestBasicPolicy-91559276 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicy-91559276', 'ctest-vn-86240521'], 'href': 'https://192.168.7.34:8082/virtual-network/bc588d79-95c2-48c3-b2e4-af058ac837b3', 'uuid': 'bc588d79-95c2-48c3-b2e4-af058ac837b3'}] before deletion
2021-02-23 05:56:12,523 - WARNING - Project ctest-TestBasicPolicy-91559276 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicy-91559276', 'ctest-vn-86240521'], 'href': 'https://192.168.7.34:8082/virtual-network/bc588d79-95c2-48c3-b2e4-af058ac837b3', 'uuid': 'bc588d79-95c2-48c3-b2e4-af058ac837b3'}] before deletion
2021-02-23 05:56:14,651 - WARNING - Project ctest-TestBasicPolicy-91559276 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicy-91559276', 'ctest-vn-86240521'], 'href': 'https://192.168.7.34:8082/virtual-network/bc588d79-95c2-48c3-b2e4-af058ac837b3', 'uuid': 'bc588d79-95c2-48c3-b2e4-af058ac837b3'}] before deletion
2021-02-23 05:56:16,766 - WARNING - Project ctest-TestBasicPolicy-91559276 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicy-91559276', 'ctest-vn-86240521'], 'href': 'https://192.168.7.34:8082/virtual-network/bc588d79-95c2-48c3-b2e4-af058ac837b3', 'uuid': 'bc588d79-95c2-48c3-b2e4-af058ac837b3'}] before deletion
2021-02-23 05:56:18,882 - WARNING - Project ctest-TestBasicPolicy-91559276 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicy-91559276', 'ctest-vn-86240521'], 'href': 'https://192.168.7.34:8082/virtual-network/bc588d79-95c2-48c3-b2e4-af058ac837b3', 'uuid': 'bc588d79-95c2-48c3-b2e4-af058ac837b3'}] before deletion
2021-02-23 05:56:21,000 - WARNING - Project ctest-TestBasicPolicy-91559276 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicy-91559276', 'ctest-vn-86240521'], 'href': 'https://192.168.7.34:8082/virtual-network/bc588d79-95c2-48c3-b2e4-af058ac837b3', 'uuid': 'bc588d79-95c2-48c3-b2e4-af058ac837b3'}] before deletion
2021-02-23 05:56:23,112 - WARNING - Project ctest-TestBasicPolicy-91559276 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicy-91559276', 'ctest-vn-86240521'], 'href': 'https://192.168.7.34:8082/virtual-network/bc588d79-95c2-48c3-b2e4-af058ac837b3', 'uuid': 'bc588d79-95c2-48c3-b2e4-af058ac837b3'}] before deletion
2021-02-23 05:56:25,223 - WARNING - Project ctest-TestBasicPolicy-91559276 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicy-91559276', 'ctest-vn-86240521'], 'href': 'https://192.168.7.34:8082/virtual-network/bc588d79-95c2-48c3-b2e4-af058ac837b3', 'uuid': 'bc588d79-95c2-48c3-b2e4-af058ac837b3'}] before deletion
2021-02-23 05:56:27,351 - WARNING - Project ctest-TestBasicPolicy-91559276 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicy-91559276', 'ctest-vn-86240521'], 'href': 'https://192.168.7.34:8082/virtual-network/bc588d79-95c2-48c3-b2e4-af058ac837b3', 'uuid': 'bc588d79-95c2-48c3-b2e4-af058ac837b3'}] before deletion
2021-02-23 05:56:29,461 - WARNING - Project ctest-TestBasicPolicy-91559276 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicy-91559276', 'ctest-vn-86240521'], 'href': 'https://192.168.7.34:8082/virtual-network/bc588d79-95c2-48c3-b2e4-af058ac837b3', 'uuid': 'bc588d79-95c2-48c3-b2e4-af058ac837b3'}] before deletion
2021-02-23 05:56:31,575 - WARNING - Project ctest-TestBasicPolicy-91559276 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicy-91559276', 'ctest-vn-86240521'], 'href': 'https://192.168.7.34:8082/virtual-network/bc588d79-95c2-48c3-b2e4-af058ac837b3', 'uuid': 'bc588d79-95c2-48c3-b2e4-af058ac837b3'}] before deletion
2021-02-23 05:56:33,702 - WARNING - Project ctest-TestBasicPolicy-91559276 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicy-91559276', 'ctest-vn-86240521'], 'href': 'https://192.168.7.34:8082/virtual-network/bc588d79-95c2-48c3-b2e4-af058ac837b3', 'uuid': 'bc588d79-95c2-48c3-b2e4-af058ac837b3'}] before deletion
2021-02-23 05:56:35,810 - WARNING - Project ctest-TestBasicPolicy-91559276 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicy-91559276', 'ctest-vn-86240521'], 'href': 'https://192.168.7.34:8082/virtual-network/bc588d79-95c2-48c3-b2e4-af058ac837b3', 'uuid': 'bc588d79-95c2-48c3-b2e4-af058ac837b3'}] before deletion
2021-02-23 05:56:37,947 - WARNING - Project ctest-TestBasicPolicy-91559276 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicy-91559276', 'ctest-vn-86240521'], 'href': 'https://192.168.7.34:8082/virtual-network/bc588d79-95c2-48c3-b2e4-af058ac837b3', 'uuid': 'bc588d79-95c2-48c3-b2e4-af058ac837b3'}] before deletion
2021-02-23 05:56:40,061 - WARNING - Project ctest-TestBasicPolicy-91559276 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicy-91559276', 'ctest-vn-86240521'], 'href': 'https://192.168.7.34:8082/virtual-network/bc588d79-95c2-48c3-b2e4-af058ac837b3', 'uuid': 'bc588d79-95c2-48c3-b2e4-af058ac837b3'}] before deletion
2021-02-23 05:56:42,170 - WARNING - Project ctest-TestBasicPolicy-91559276 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicy-91559276', 'ctest-vn-86240521'], 'href': 'https://192.168.7.34:8082/virtual-network/bc588d79-95c2-48c3-b2e4-af058ac837b3', 'uuid': 'bc588d79-95c2-48c3-b2e4-af058ac837b3'}] before deletion
2021-02-23 05:56:44,279 - WARNING - Project ctest-TestBasicPolicy-91559276 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicy-91559276', 'ctest-vn-86240521'], 'href': 'https://192.168.7.34:8082/virtual-network/bc588d79-95c2-48c3-b2e4-af058ac837b3', 'uuid': 'bc588d79-95c2-48c3-b2e4-af058ac837b3'}] before deletion
2021-02-23 05:56:44,280 - WARNING - One or more references still present, will not delete the project ctest-TestBasicPolicy-91559276
2021-02-24 06:24:39,703 - INFO - Reading existing Domain with UUID f27c063f-c6c4-434f-a616-97e72e0043e5
2021-02-24 06:24:39,734 - INFO - Using existing domain ['admin_domain'](f27c063f-c6c4-434f-a616-97e72e0043e5)
2021-02-24 06:24:40,170 - INFO - Project ctest-TestBasicPolicy-57660166 not found, creating it
2021-02-24 06:24:40,799 - INFO - Created Project:ctest-TestBasicPolicy-57660166, ID : 74efdb0c-b51b-486c-bef3-bb1dd3336b3e 
2021-02-24 06:24:44,409 - INFO - ================================================================================
2021-02-24 06:24:44,410 - INFO - STARTING TEST    : test_basic_policy_allow_deny
2021-02-24 06:24:44,410 - INFO - TEST DESCRIPTION : 
        Create 2 Vns and allow icmp traffic between them and validate with pings
        Update the policy to deny the same traffic
        Check that pings fail
        
2021-02-24 06:24:45,759 - DEBUG - Nothing to compare xmpp stats {'192.168.7.19': {'192.168.27.20': '0', '192.168.27.34': '0'}, '192.168.7.9': {'192.168.27.20': '0', '192.168.27.34': '0'}} with
2021-02-24 06:24:45,759 - INFO - Initial checks done. Running the testcase now
2021-02-24 06:24:45,759 - INFO - 
2021-02-24 06:24:47,042 - DEBUG - Response for create_network : {'network': {'status': 'ACTIVE', 'router:external': False, 'subnets': [], 'fq_name': ['admin_domain', 'ctest-TestBasicPolicy-57660166', 'ctest-vn-44147984'], 'name': 'ctest-vn-44147984', 'admin_state_up': True, 'tenant_id': '74efdb0cb51b486cbef3bb1dd3336b3e', 'created_at': None, 'updated_at': None, 'shared': False, 'port_security_enabled': True, 'project_id': '74efdb0cb51b486cbef3bb1dd3336b3e', 'id': '63f20fd4-b8f9-4a0d-a100-fcb4b4eedad2', 'description': ''}}
2021-02-24 06:24:47,446 - DEBUG - Response for create_subnet : {'subnet': {'name': '', 'enable_dhcp': True, 'network_id': '63f20fd4-b8f9-4a0d-a100-fcb4b4eedad2', 'tenant_id': '74efdb0cb51b486cbef3bb1dd3336b3e', 'created_at': '2021-02-24T06:24:46.475343', 'dns_nameservers': [], 'updated_at': '2021-02-24T06:24:46.475343', 'ipv6_ra_mode': None, 'allocation_pools': [{'start': '193.48.202.66', 'end': '193.48.202.126'}], 'gateway_ip': '193.48.202.65', 'dns_server_address': '193.48.202.66', 'ipv6_address_mode': None, 'ip_version': 4, 'host_routes': [], 'cidr': '193.48.202.64/26', 'id': '6e673066-9bba-43c9-8f14-861f11826568'}}
2021-02-24 06:24:47,515 - INFO - Created VN ctest-vn-44147984
2021-02-24 06:24:47,549 - DEBUG - VN ctest-vn-44147984 UUID is 63f20fd4-b8f9-4a0d-a100-fcb4b4eedad2
2021-02-24 06:24:48,036 - DEBUG - Response for create_network : {'network': {'status': 'ACTIVE', 'router:external': False, 'subnets': [], 'fq_name': ['admin_domain', 'ctest-TestBasicPolicy-57660166', 'ctest-vn-25714786'], 'name': 'ctest-vn-25714786', 'admin_state_up': True, 'tenant_id': '74efdb0cb51b486cbef3bb1dd3336b3e', 'created_at': None, 'updated_at': None, 'shared': False, 'port_security_enabled': True, 'project_id': '74efdb0cb51b486cbef3bb1dd3336b3e', 'id': 'a6ecd8ef-340d-4379-be13-d935ca66847a', 'description': ''}}
2021-02-24 06:24:48,354 - DEBUG - Response for create_subnet : {'subnet': {'name': '', 'enable_dhcp': True, 'network_id': 'a6ecd8ef-340d-4379-be13-d935ca66847a', 'tenant_id': '74efdb0cb51b486cbef3bb1dd3336b3e', 'created_at': '2021-02-24T06:24:49.831129', 'dns_nameservers': [], 'updated_at': '2021-02-24T06:24:49.831129', 'ipv6_ra_mode': None, 'allocation_pools': [{'start': '27.5.226.194', 'end': '27.5.226.254'}], 'gateway_ip': '27.5.226.193', 'dns_server_address': '27.5.226.194', 'ipv6_address_mode': None, 'ip_version': 4, 'host_routes': [], 'cidr': '27.5.226.192/26', 'id': '4d11a507-b31a-4e6c-93aa-96e2f16cf3e5'}}
2021-02-24 06:24:48,399 - INFO - Created VN ctest-vn-25714786
2021-02-24 06:24:48,428 - DEBUG - VN ctest-vn-25714786 UUID is a6ecd8ef-340d-4379-be13-d935ca66847a
2021-02-24 06:24:48,605 - DEBUG - Policy np_rules : [rule_sequence = None, rule_uuid = None, direction = <>, protocol = icmp, src_addresses = [subnet = None, virtual_network = admin_domain:ctest-TestBasicPolicy-57660166:ctest-vn-44147984, security_group = None, network_policy = None, subnet_list = []], src_ports = [start_port = -1, end_port = -1], application = [], dst_addresses = [subnet = None, virtual_network = admin_domain:ctest-TestBasicPolicy-57660166:ctest-vn-25714786, security_group = None, network_policy = None, subnet_list = []], dst_ports = [start_port = -1, end_port = -1], action_list = simple_action = pass, gateway_name = None, apply_service = [], service_properties = None, mirror_to = None, assign_routing_instance = None, log = False, alert = False, qos_action = None, host_based_service = False, ethertype = None, created = None, last_modified = None]
2021-02-24 06:24:48,905 - DEBUG - Response for mapping policy(s) with vn {'network': {'status': 'ACTIVE', 'router:external': False, 'subnets': ['6e673066-9bba-43c9-8f14-861f11826568'], 'fq_name': ['admin_domain', 'ctest-TestBasicPolicy-57660166', 'ctest-vn-44147984'], 'name': 'ctest-vn-44147984', 'admin_state_up': True, 'tenant_id': '74efdb0cb51b486cbef3bb1dd3336b3e', 'created_at': '2021-02-24T06:24:45.820111', 'updated_at': '2021-02-24T06:24:46.511862', 'policys': [['admin_domain', 'ctest-TestBasicPolicy-57660166', 'ctest-policy-allow-all-15672784']], 'shared': False, 'port_security_enabled': True, 'project_id': '74efdb0cb51b486cbef3bb1dd3336b3e', 'subnet_ipam': [{'subnet_cidr': '193.48.202.64/26', 'ipam_fq_name': ['default-domain', 'default-project', 'default-network-ipam']}], 'id': '63f20fd4-b8f9-4a0d-a100-fcb4b4eedad2', 'description': ''}}
2021-02-24 06:24:49,185 - DEBUG - Response for mapping policy(s) with vn {'network': {'status': 'ACTIVE', 'router:external': False, 'subnets': ['4d11a507-b31a-4e6c-93aa-96e2f16cf3e5'], 'fq_name': ['admin_domain', 'ctest-TestBasicPolicy-57660166', 'ctest-vn-25714786'], 'name': 'ctest-vn-25714786', 'admin_state_up': True, 'tenant_id': '74efdb0cb51b486cbef3bb1dd3336b3e', 'created_at': '2021-02-24T06:24:47.168095', 'updated_at': '2021-02-24T06:24:49.869898', 'policys': [['admin_domain', 'ctest-TestBasicPolicy-57660166', 'ctest-policy-allow-all-15672784']], 'shared': False, 'port_security_enabled': True, 'project_id': '74efdb0cb51b486cbef3bb1dd3336b3e', 'subnet_ipam': [{'subnet_cidr': '27.5.226.192/26', 'ipam_fq_name': ['default-domain', 'default-project', 'default-network-ipam']}], 'id': 'a6ecd8ef-340d-4379-be13-d935ca66847a', 'description': ''}}
2021-02-24 06:24:49,297 - DEBUG - Requesting: https://192.168.7.20:8082/domains
2021-02-24 06:24:50,004 - DEBUG - Requesting: https://192.168.7.20:8082/domains
2021-02-24 06:24:50,106 - DEBUG - Requesting: https://192.168.7.20:8082/domain/f27c063f-c6c4-434f-a616-97e72e0043e5
2021-02-24 06:24:50,155 - DEBUG - Requesting: https://192.168.7.20:8082/project/74efdb0c-b51b-486c-bef3-bb1dd3336b3e
2021-02-24 06:24:50,221 - DEBUG - Requesting: https://192.168.7.20:8082/virtual-network/63f20fd4-b8f9-4a0d-a100-fcb4b4eedad2
2021-02-24 06:24:50,255 - DEBUG - Requesting: https://192.168.7.20:8082/virtual-network/63f20fd4-b8f9-4a0d-a100-fcb4b4eedad2
2021-02-24 06:24:50,285 - DEBUG - Requesting: https://192.168.7.20:8082/routing-instance/481f89c7-9ff0-4a88-9382-69b7b14ecc36
2021-02-24 06:24:50,313 - DEBUG - Requesting: https://192.168.7.20:8082/routing-instance/481f89c7-9ff0-4a88-9382-69b7b14ecc36
2021-02-24 06:24:50,342 - DEBUG - Requesting: https://192.168.7.20:8082/route-target/d92ceaa4-1838-4f40-8e72-525ecdf2f6be
2021-02-24 06:24:50,367 - DEBUG - Route Targets: ['target:64512:8000032']
2021-02-24 06:24:50,367 - DEBUG - Requesting: https://192.168.7.20:8082/virtual-network/63f20fd4-b8f9-4a0d-a100-fcb4b4eedad2
2021-02-24 06:24:50,395 - DEBUG - Requesting: https://192.168.7.20:8082/routing-instance/481f89c7-9ff0-4a88-9382-69b7b14ecc36
2021-02-24 06:24:50,435 - INFO - Verified VN network id 13 for VN 63f20fd4-b8f9-4a0d-a100-fcb4b4eedad2
2021-02-24 06:24:50,435 - INFO - Verifications in API Server for VN ctest-vn-44147984 passed
2021-02-24 06:24:50,435 - DEBUG - Requesting: https://192.168.7.20:8082/virtual-network/63f20fd4-b8f9-4a0d-a100-fcb4b4eedad2
2021-02-24 06:24:50,463 - DEBUG - Requesting: https://192.168.7.20:8082/routing-instance/481f89c7-9ff0-4a88-9382-69b7b14ecc36
2021-02-24 06:24:50,487 - DEBUG - Requesting: https://192.168.7.20:8082/routing-instance/481f89c7-9ff0-4a88-9382-69b7b14ecc36
2021-02-24 06:24:50,511 - DEBUG - Requesting: https://192.168.7.20:8082/route-target/d92ceaa4-1838-4f40-8e72-525ecdf2f6be
2021-02-24 06:24:50,553 - DEBUG - Control-node 192.168.7.20 : VN object is : {'node_name': 'virtual-network:admin_domain:ctest-TestBasicPolicy-57660166:ctest-vn-44147984', 'interests': '-', 'advertised': '-', 'dbentryflags': None, 'obj_info': {'sequence_number': '0', 'origin': 'Cassandra', 'data': {'id-perms': {'permissions': {'owner': 'ctest-TestBasicPolicy-57660166', 'owner-access': '7', 'group': 'admin', 'group-access': '7', 'other-access': '7'}, 'uuid': {'uuid-mslong': '7201836160429672973', 'uuid-lslong': '11601550493166262994'}, 'enable': 'true', 'created': '2021-02-24T06:24:45', 'last-modified': '2021-02-24T06:24:50', 'description': None, 'user-visible': 'true', 'creator': None}}}, 'neighbors': None, 'last_modified': '00:00:01.681958'}
2021-02-24 06:24:50,573 - DEBUG - Route Targets: ['target:64512:8000032']
2021-02-24 06:24:50,681 - DEBUG - Control-node 192.168.7.29 : VN object is : {'node_name': 'virtual-network:admin_domain:ctest-TestBasicPolicy-57660166:ctest-vn-44147984', 'interests': '-', 'advertised': '-', 'dbentryflags': None, 'obj_info': {'sequence_number': '0', 'origin': 'Cassandra', 'data': {'id-perms': {'permissions': {'owner': 'ctest-TestBasicPolicy-57660166', 'owner-access': '7', 'group': 'admin', 'group-access': '7', 'other-access': '7'}, 'uuid': {'uuid-mslong': '7201836160429672973', 'uuid-lslong': '11601550493166262994'}, 'enable': 'true', 'created': '2021-02-24T06:24:45', 'last-modified': '2021-02-24T06:24:50', 'description': None, 'user-visible': 'true', 'creator': None}}}, 'neighbors': None, 'last_modified': '00:00:01.809878'}
2021-02-24 06:24:50,787 - DEBUG - Route Targets: ['target:64512:8000032']
2021-02-24 06:24:50,810 - DEBUG - Control-node 192.168.7.34 : VN object is : {'node_name': 'virtual-network:admin_domain:ctest-TestBasicPolicy-57660166:ctest-vn-44147984', 'interests': '-', 'advertised': '-', 'dbentryflags': None, 'obj_info': {'sequence_number': '0', 'origin': 'Cassandra', 'data': {'id-perms': {'permissions': {'owner': 'ctest-TestBasicPolicy-57660166', 'owner-access': '7', 'group': 'admin', 'group-access': '7', 'other-access': '7'}, 'uuid': {'uuid-mslong': '7201836160429672973', 'uuid-lslong': '11601550493166262994'}, 'enable': 'true', 'created': '2021-02-24T06:24:45', 'last-modified': '2021-02-24T06:24:50', 'description': None, 'user-visible': 'true', 'creator': None}}}, 'neighbors': None, 'last_modified': '00:00:01.939251'}
2021-02-24 06:24:50,826 - DEBUG - Route Targets: ['target:64512:8000032']
2021-02-24 06:24:50,826 - INFO - On all control nodes, Config, RI and RT verification for VN ctest-vn-44147984 passed
2021-02-24 06:24:50,827 - DEBUG - ====Verifying policy data for ctest-vn-44147984 in API_Server ======
2021-02-24 06:24:50,827 - DEBUG - Requesting: https://192.168.7.20:8082/domains
2021-02-24 06:24:50,850 - DEBUG - Requesting: https://192.168.7.20:8082/domain/f27c063f-c6c4-434f-a616-97e72e0043e5
2021-02-24 06:24:50,897 - DEBUG - Requesting: https://192.168.7.20:8082/project/74efdb0c-b51b-486c-bef3-bb1dd3336b3e
2021-02-24 06:24:50,966 - DEBUG - Requesting: https://192.168.7.20:8082/virtual-network/63f20fd4-b8f9-4a0d-a100-fcb4b4eedad2
2021-02-24 06:24:50,993 - DEBUG - ==>Verifying data for policy with id: c48a8e7d-0766-4161-abd1-c666f60b5c38, fqn: ['admin_domain', 'ctest-TestBasicPolicy-57660166', 'ctest-policy-allow-all-15672784']
2021-02-24 06:24:50,993 - INFO - VN ctest-vn-44147984 Policy verification: verify_vn_policy_in_api_server, status: True
2021-02-24 06:24:50,994 - DEBUG - Verifying the vn in opserver
2021-02-24 06:24:50,994 - DEBUG - Verifying the admin_domain:ctest-TestBasicPolicy-57660166:ctest-vn-44147984 virtual network link  through opserver 192.168.7.20
2021-02-24 06:24:50,994 - DEBUG - Requesting: https://192.168.7.20:8081/analytics/uves/virtual-networks
2021-02-24 06:24:52,123 - DEBUG - Requesting: https://192.168.7.20:8081/analytics/uves/virtual-networks
2021-02-24 06:24:52,280 - DEBUG - vn link and name as {'href': 'https://192.168.7.20:8081/analytics/uves/virtual-network/admin_domain:ctest-TestBasicPolicy-57660166:ctest-vn-44147984?flat', 'name': 'admin_domain:ctest-TestBasicPolicy-57660166:ctest-vn-44147984'}
2021-02-24 06:24:52,280 - DEBUG - Verifying the admin_domain:ctest-TestBasicPolicy-57660166:ctest-vn-44147984 virtual network link  through opserver 192.168.7.29
2021-02-24 06:24:52,281 - DEBUG - Requesting: https://192.168.7.29:8081/analytics/uves/virtual-networks
2021-02-24 06:24:52,743 - DEBUG - Requesting: https://192.168.7.29:8081/analytics/uves/virtual-networks
2021-02-24 06:24:52,877 - DEBUG - vn link and name as {'href': 'https://192.168.7.29:8081/analytics/uves/virtual-network/admin_domain:ctest-TestBasicPolicy-57660166:ctest-vn-44147984?flat', 'name': 'admin_domain:ctest-TestBasicPolicy-57660166:ctest-vn-44147984'}
2021-02-24 06:24:52,877 - DEBUG - Verifying the admin_domain:ctest-TestBasicPolicy-57660166:ctest-vn-44147984 virtual network link  through opserver 192.168.7.34
2021-02-24 06:24:52,878 - DEBUG - Requesting: https://192.168.7.34:8081/analytics/uves/virtual-networks
2021-02-24 06:24:53,459 - DEBUG - Requesting: https://192.168.7.34:8081/analytics/uves/virtual-networks
2021-02-24 06:24:53,592 - DEBUG - vn link and name as {'href': 'https://192.168.7.34:8081/analytics/uves/virtual-network/admin_domain:ctest-TestBasicPolicy-57660166:ctest-vn-44147984?flat', 'name': 'admin_domain:ctest-TestBasicPolicy-57660166:ctest-vn-44147984'}
2021-02-24 06:24:53,592 - INFO - Validated that VN admin_domain:ctest-TestBasicPolicy-57660166:ctest-vn-44147984 is found in opserver
2021-02-24 06:24:53,832 - DEBUG - Do not have enough data to verify VN in agent
2021-02-24 06:24:53,948 - DEBUG - VRF ids for VN ctest-vn-44147984: {}
2021-02-24 06:24:53,949 - DEBUG - Requesting: https://192.168.7.20:8082/domains
2021-02-24 06:24:53,975 - DEBUG - Requesting: https://192.168.7.20:8082/domain/f27c063f-c6c4-434f-a616-97e72e0043e5
2021-02-24 06:24:54,019 - DEBUG - Requesting: https://192.168.7.20:8082/project/74efdb0c-b51b-486c-bef3-bb1dd3336b3e
2021-02-24 06:24:54,087 - DEBUG - Requesting: https://192.168.7.20:8082/virtual-network/a6ecd8ef-340d-4379-be13-d935ca66847a
2021-02-24 06:24:54,119 - DEBUG - Requesting: https://192.168.7.20:8082/virtual-network/a6ecd8ef-340d-4379-be13-d935ca66847a
2021-02-24 06:24:54,149 - DEBUG - Requesting: https://192.168.7.20:8082/routing-instance/9a806454-7e85-4197-b9b3-b2832d270c24
2021-02-24 06:24:54,178 - DEBUG - Requesting: https://192.168.7.20:8082/routing-instance/9a806454-7e85-4197-b9b3-b2832d270c24
2021-02-24 06:24:54,202 - DEBUG - Requesting: https://192.168.7.20:8082/route-target/ea101526-f6a5-4607-b45f-05f111f244fb
2021-02-24 06:24:54,228 - DEBUG - Route Targets: ['target:64512:8000033']
2021-02-24 06:24:54,228 - DEBUG - Requesting: https://192.168.7.20:8082/virtual-network/a6ecd8ef-340d-4379-be13-d935ca66847a
2021-02-24 06:24:54,260 - DEBUG - Requesting: https://192.168.7.20:8082/routing-instance/9a806454-7e85-4197-b9b3-b2832d270c24
2021-02-24 06:24:54,300 - INFO - Verified VN network id 44 for VN a6ecd8ef-340d-4379-be13-d935ca66847a
2021-02-24 06:24:54,300 - INFO - Verifications in API Server for VN ctest-vn-25714786 passed
2021-02-24 06:24:54,301 - DEBUG - Requesting: https://192.168.7.20:8082/virtual-network/a6ecd8ef-340d-4379-be13-d935ca66847a
2021-02-24 06:24:54,331 - DEBUG - Requesting: https://192.168.7.20:8082/routing-instance/9a806454-7e85-4197-b9b3-b2832d270c24
2021-02-24 06:24:54,354 - DEBUG - Requesting: https://192.168.7.20:8082/routing-instance/9a806454-7e85-4197-b9b3-b2832d270c24
2021-02-24 06:24:54,380 - DEBUG - Requesting: https://192.168.7.20:8082/route-target/ea101526-f6a5-4607-b45f-05f111f244fb
2021-02-24 06:24:54,423 - DEBUG - Control-node 192.168.7.20 : VN object is : {'node_name': 'virtual-network:admin_domain:ctest-TestBasicPolicy-57660166:ctest-vn-25714786', 'interests': '-', 'advertised': '-', 'dbentryflags': None, 'obj_info': {'sequence_number': '0', 'origin': 'Cassandra', 'data': {'id-perms': {'permissions': {'owner': 'ctest-TestBasicPolicy-57660166', 'owner-access': '7', 'group': 'admin', 'group-access': '7', 'other-access': '7'}, 'uuid': {'uuid-mslong': '12028227226681820025', 'uuid-lslong': '13696529716816020602'}, 'enable': 'true', 'created': '2021-02-24T06:24:47', 'last-modified': '2021-02-24T06:24:50', 'description': None, 'user-visible': 'true', 'creator': None}}}, 'neighbors': None, 'last_modified': '00:00:05.281338'}
2021-02-24 06:24:54,443 - DEBUG - Route Targets: ['target:64512:8000033']
2021-02-24 06:24:54,541 - DEBUG - Control-node 192.168.7.29 : VN object is : {'node_name': 'virtual-network:admin_domain:ctest-TestBasicPolicy-57660166:ctest-vn-25714786', 'interests': '-', 'advertised': '-', 'dbentryflags': None, 'obj_info': {'sequence_number': '0', 'origin': 'Cassandra', 'data': {'id-perms': {'permissions': {'owner': 'ctest-TestBasicPolicy-57660166', 'owner-access': '7', 'group': 'admin', 'group-access': '7', 'other-access': '7'}, 'uuid': {'uuid-mslong': '12028227226681820025', 'uuid-lslong': '13696529716816020602'}, 'enable': 'true', 'created': '2021-02-24T06:24:47', 'last-modified': '2021-02-24T06:24:50', 'description': None, 'user-visible': 'true', 'creator': None}}}, 'neighbors': None, 'last_modified': '00:00:05.398767'}
2021-02-24 06:24:54,662 - DEBUG - Route Targets: ['target:64512:8000033']
2021-02-24 06:24:54,679 - DEBUG - Control-node 192.168.7.34 : VN object is : {'node_name': 'virtual-network:admin_domain:ctest-TestBasicPolicy-57660166:ctest-vn-25714786', 'interests': '-', 'advertised': '-', 'dbentryflags': None, 'obj_info': {'sequence_number': '0', 'origin': 'Cassandra', 'data': {'id-perms': {'permissions': {'owner': 'ctest-TestBasicPolicy-57660166', 'owner-access': '7', 'group': 'admin', 'group-access': '7', 'other-access': '7'}, 'uuid': {'uuid-mslong': '12028227226681820025', 'uuid-lslong': '13696529716816020602'}, 'enable': 'true', 'created': '2021-02-24T06:24:47', 'last-modified': '2021-02-24T06:24:50', 'description': None, 'user-visible': 'true', 'creator': None}}}, 'neighbors': None, 'last_modified': '00:00:05.537051'}
2021-02-24 06:24:54,697 - DEBUG - Route Targets: ['target:64512:8000033']
2021-02-24 06:24:54,697 - INFO - On all control nodes, Config, RI and RT verification for VN ctest-vn-25714786 passed
2021-02-24 06:24:54,698 - DEBUG - ====Verifying policy data for ctest-vn-25714786 in API_Server ======
2021-02-24 06:24:54,698 - DEBUG - Requesting: https://192.168.7.20:8082/domains
2021-02-24 06:24:54,722 - DEBUG - Requesting: https://192.168.7.20:8082/domain/f27c063f-c6c4-434f-a616-97e72e0043e5
2021-02-24 06:24:54,769 - DEBUG - Requesting: https://192.168.7.20:8082/project/74efdb0c-b51b-486c-bef3-bb1dd3336b3e
2021-02-24 06:24:54,834 - DEBUG - Requesting: https://192.168.7.20:8082/virtual-network/a6ecd8ef-340d-4379-be13-d935ca66847a
2021-02-24 06:24:54,865 - DEBUG - ==>Verifying data for policy with id: c48a8e7d-0766-4161-abd1-c666f60b5c38, fqn: ['admin_domain', 'ctest-TestBasicPolicy-57660166', 'ctest-policy-allow-all-15672784']
2021-02-24 06:24:54,865 - INFO - VN ctest-vn-25714786 Policy verification: verify_vn_policy_in_api_server, status: True
2021-02-24 06:24:54,866 - DEBUG - Verifying the vn in opserver
2021-02-24 06:24:54,866 - DEBUG - Verifying the admin_domain:ctest-TestBasicPolicy-57660166:ctest-vn-25714786 virtual network link  through opserver 192.168.7.20
2021-02-24 06:24:54,866 - DEBUG - Requesting: https://192.168.7.20:8081/analytics/uves/virtual-networks
2021-02-24 06:24:55,104 - DEBUG - vn link and name as {'href': 'https://192.168.7.20:8081/analytics/uves/virtual-network/admin_domain:ctest-TestBasicPolicy-57660166:ctest-vn-25714786?flat', 'name': 'admin_domain:ctest-TestBasicPolicy-57660166:ctest-vn-25714786'}
2021-02-24 06:24:55,105 - DEBUG - Verifying the admin_domain:ctest-TestBasicPolicy-57660166:ctest-vn-25714786 virtual network link  through opserver 192.168.7.29
2021-02-24 06:24:55,105 - DEBUG - Requesting: https://192.168.7.29:8081/analytics/uves/virtual-networks
2021-02-24 06:24:55,264 - DEBUG - vn link and name as {'href': 'https://192.168.7.29:8081/analytics/uves/virtual-network/admin_domain:ctest-TestBasicPolicy-57660166:ctest-vn-25714786?flat', 'name': 'admin_domain:ctest-TestBasicPolicy-57660166:ctest-vn-25714786'}
2021-02-24 06:24:55,264 - DEBUG - Verifying the admin_domain:ctest-TestBasicPolicy-57660166:ctest-vn-25714786 virtual network link  through opserver 192.168.7.34
2021-02-24 06:24:55,265 - DEBUG - Requesting: https://192.168.7.34:8081/analytics/uves/virtual-networks
2021-02-24 06:24:55,421 - DEBUG - vn link and name as {'href': 'https://192.168.7.34:8081/analytics/uves/virtual-network/admin_domain:ctest-TestBasicPolicy-57660166:ctest-vn-25714786?flat', 'name': 'admin_domain:ctest-TestBasicPolicy-57660166:ctest-vn-25714786'}
2021-02-24 06:24:55,422 - INFO - Validated that VN admin_domain:ctest-TestBasicPolicy-57660166:ctest-vn-25714786 is found in opserver
2021-02-24 06:24:55,668 - DEBUG - Do not have enough data to verify VN in agent
2021-02-24 06:24:55,788 - DEBUG - VRF ids for VN ctest-vn-25714786: {}
2021-02-24 06:24:56,149 - DEBUG - Services list from nova: [<Service: 1>, <Service: 3>, <Service: 4>, <Service: 16>]
2021-02-24 06:24:57,382 - INFO - VM ([<Server: ctest-TestBasicPolicy-57660166-12389189>]) created on node: (nodec9), Zone: (nova:nodec9)
2021-02-24 06:24:59,504 - INFO - VM ([<Server: ctest-TestBasicPolicy-57660166-60249790>]) created on node: (nodec9), Zone: (nova:nodec9)
2021-02-24 06:24:59,505 - INFO - Waiting for VM ctest-TestBasicPolicy-57660166-12389189 to be up..
2021-02-24 06:24:59,645 - DEBUG - VM <Server: ctest-TestBasicPolicy-57660166-12389189> is still in BUILD state, Expected: ACTIVE
2021-02-24 06:25:04,872 - DEBUG - VM <Server: ctest-TestBasicPolicy-57660166-12389189> is still in BUILD state, Expected: ACTIVE
2021-02-24 06:25:10,056 - DEBUG - VM <Server: ctest-TestBasicPolicy-57660166-12389189> is in ACTIVE state now
2021-02-24 06:25:10,056 - INFO - VM name : ctest-TestBasicPolicy-57660166-12389189
2021-02-24 06:25:10,239 - DEBUG - VM ctest-TestBasicPolicy-57660166-12389189 ID is 5118e74c-cb97-4c79-990c-cc2771ddcab1
2021-02-24 06:25:10,269 - DEBUG - VM ctest-TestBasicPolicy-57660166-12389189 launched on Node nodec9.maas
2021-02-24 06:25:10,440 - DEBUG - Requesting: https://192.168.7.34:8082/virtual-machine/5118e74c-cb97-4c79-990c-cc2771ddcab1
2021-02-24 06:25:11,660 - DEBUG - Requesting: https://192.168.7.34:8082/virtual-machine/5118e74c-cb97-4c79-990c-cc2771ddcab1
2021-02-24 06:25:11,760 - DEBUG - Requesting: https://192.168.7.34:8082/virtual-machine-interface/56d3cb39-b9da-4e25-926a-72b2df5e2dc4
2021-02-24 06:25:15,007 - DEBUG - (True, 'PING 169.254.0.3 (169.254.0.3) 56(84) bytes of data.\r\n\r\n--- 169.254.0.3 ping statistics ---\r\n2 packets transmitted, 0 received, 100% packet loss, time 1030ms')
2021-02-24 06:25:15,007 - DEBUG - Ping to Metadata IP 169.254.0.3 of VM ctest-TestBasicPolicy-57660166-12389189 failed!
2021-02-24 06:25:15,043 - DEBUG - Gateway for vn admin_domain:ctest-TestBasicPolicy-57660166:ctest-vn-44147984 is 193.48.202.65 and allocation pool is NOT set
2021-02-24 06:25:19,141 - DEBUG - (True, 'PING 169.254.0.3 (169.254.0.3) 56(84) bytes of data.\r\n\r\n--- 169.254.0.3 ping statistics ---\r\n2 packets transmitted, 0 received, 100% packet loss, time 1031ms')
2021-02-24 06:25:19,141 - DEBUG - Ping to Metadata IP 169.254.0.3 of VM ctest-TestBasicPolicy-57660166-12389189 failed!
2021-02-24 06:25:19,173 - DEBUG - Gateway for vn admin_domain:ctest-TestBasicPolicy-57660166:ctest-vn-44147984 is 193.48.202.65 and allocation pool is NOT set
2021-02-24 06:25:23,205 - DEBUG - (True, 'PING 169.254.0.3 (169.254.0.3) 56(84) bytes of data.\r\n\r\n--- 169.254.0.3 ping statistics ---\r\n2 packets transmitted, 0 received, 100% packet loss, time 1001ms')
2021-02-24 06:25:23,205 - DEBUG - Ping to Metadata IP 169.254.0.3 of VM ctest-TestBasicPolicy-57660166-12389189 failed!
2021-02-24 06:25:23,238 - DEBUG - Gateway for vn admin_domain:ctest-TestBasicPolicy-57660166:ctest-vn-44147984 is 193.48.202.65 and allocation pool is NOT set
2021-02-24 06:25:27,265 - DEBUG - (True, 'PING 169.254.0.3 (169.254.0.3) 56(84) bytes of data.\r\n\r\n--- 169.254.0.3 ping statistics ---\r\n2 packets transmitted, 0 received, 100% packet loss, time 1000ms')
2021-02-24 06:25:27,266 - DEBUG - Ping to Metadata IP 169.254.0.3 of VM ctest-TestBasicPolicy-57660166-12389189 failed!
2021-02-24 06:25:27,298 - DEBUG - Gateway for vn admin_domain:ctest-TestBasicPolicy-57660166:ctest-vn-44147984 is 193.48.202.65 and allocation pool is NOT set
2021-02-24 06:25:31,338 - DEBUG - (True, 'PING 169.254.0.3 (169.254.0.3) 56(84) bytes of data.\r\n\r\n--- 169.254.0.3 ping statistics ---\r\n2 packets transmitted, 0 received, 100% packet loss, time 1005ms')
2021-02-24 06:25:31,338 - DEBUG - Ping to Metadata IP 169.254.0.3 of VM ctest-TestBasicPolicy-57660166-12389189 failed!
2021-02-24 06:25:31,369 - DEBUG - Gateway for vn admin_domain:ctest-TestBasicPolicy-57660166:ctest-vn-44147984 is 193.48.202.65 and allocation pool is NOT set
2021-02-24 06:25:35,422 - DEBUG - (True, 'PING 169.254.0.3 (169.254.0.3) 56(84) bytes of data.\r\n\r\n--- 169.254.0.3 ping statistics ---\r\n2 packets transmitted, 0 received, 100% packet loss, time 1028ms')
2021-02-24 06:25:35,422 - DEBUG - Ping to Metadata IP 169.254.0.3 of VM ctest-TestBasicPolicy-57660166-12389189 failed!
2021-02-24 06:25:35,452 - DEBUG - Gateway for vn admin_domain:ctest-TestBasicPolicy-57660166:ctest-vn-44147984 is 193.48.202.65 and allocation pool is NOT set
2021-02-24 06:25:39,491 - DEBUG - (True, 'PING 169.254.0.3 (169.254.0.3) 56(84) bytes of data.\r\n\r\n--- 169.254.0.3 ping statistics ---\r\n2 packets transmitted, 0 received, 100% packet loss, time 1001ms')
2021-02-24 06:25:39,492 - DEBUG - Ping to Metadata IP 169.254.0.3 of VM ctest-TestBasicPolicy-57660166-12389189 failed!
2021-02-24 06:25:39,528 - DEBUG - Gateway for vn admin_domain:ctest-TestBasicPolicy-57660166:ctest-vn-44147984 is 193.48.202.65 and allocation pool is NOT set
2021-02-24 06:25:43,588 - DEBUG - (True, 'PING 169.254.0.3 (169.254.0.3) 56(84) bytes of data.\r\n\r\n--- 169.254.0.3 ping statistics ---\r\n2 packets transmitted, 0 received, 100% packet loss, time 1029ms')
2021-02-24 06:25:43,589 - DEBUG - Ping to Metadata IP 169.254.0.3 of VM ctest-TestBasicPolicy-57660166-12389189 failed!
2021-02-24 06:25:43,618 - DEBUG - Gateway for vn admin_domain:ctest-TestBasicPolicy-57660166:ctest-vn-44147984 is 193.48.202.65 and allocation pool is NOT set
2021-02-24 06:25:47,653 - DEBUG - (True, 'PING 169.254.0.3 (169.254.0.3) 56(84) bytes of data.\r\n\r\n--- 169.254.0.3 ping statistics ---\r\n2 packets transmitted, 0 received, 100% packet loss, time 1004ms')
2021-02-24 06:25:47,653 - DEBUG - Ping to Metadata IP 169.254.0.3 of VM ctest-TestBasicPolicy-57660166-12389189 failed!
2021-02-24 06:25:47,693 - DEBUG - Gateway for vn admin_domain:ctest-TestBasicPolicy-57660166:ctest-vn-44147984 is 193.48.202.65 and allocation pool is NOT set
2021-02-24 06:25:51,744 - DEBUG - (True, 'PING 169.254.0.3 (169.254.0.3) 56(84) bytes of data.\r\n\r\n--- 169.254.0.3 ping statistics ---\r\n2 packets transmitted, 0 received, 100% packet loss, time 1024ms')
2021-02-24 06:25:51,744 - DEBUG - Ping to Metadata IP 169.254.0.3 of VM ctest-TestBasicPolicy-57660166-12389189 failed!
2021-02-24 06:25:51,780 - DEBUG - Gateway for vn admin_domain:ctest-TestBasicPolicy-57660166:ctest-vn-44147984 is 193.48.202.65 and allocation pool is NOT set
2021-02-24 06:25:53,812 - DEBUG - (True, 'PING 169.254.0.3 (169.254.0.3) 56(84) bytes of data.\r\n64 bytes from 169.254.0.3: icmp_seq=1 ttl=63 time=3.27 ms\r\n64 bytes from 169.254.0.3: icmp_seq=2 ttl=63 time=1.53 ms\r\n\r\n--- 169.254.0.3 ping statistics ---\r\n2 packets transmitted, 2 received, 0% packet loss, time 1001ms\r\nrtt min/avg/max/mdev = 1.535/2.405/3.276/0.871 ms')
2021-02-24 06:25:53,812 - INFO - Ping to Metadata IP 169.254.0.3 of VM ctest-TestBasicPolicy-57660166-12389189 passed
2021-02-24 06:25:53,884 - DEBUG - verify_vm_launched is skipped since self.vm_launch_flag is set
2021-02-24 06:25:53,884 - DEBUG - Waiting to SSH to VM ctest-TestBasicPolicy-57660166-12389189, IP 193.48.202.67, Port 22
2021-02-24 06:25:53,921 - DEBUG - Error on ssh to ubuntu@169.254.0.3:22, result: /bin/bash: connect: Connection refused
/bin/bash: /dev/tcp/169.254.0.3/22: Connection refused {'failed': True, 'command': '(echo > /dev/tcp/169.254.0.3/22)', 'real_command': '/bin/bash -l -c "(echo > /dev/tcp/169.254.0.3/22)"', 'return_code': 1, 'succeeded': False, 'stderr': ''}
2021-02-24 06:25:54,174 - DEBUG - VM ctest-TestBasicPolicy-57660166-12389189 is NOT ready for SSH connections, VM status: ACTIVE
2021-02-24 06:25:59,175 - DEBUG - verify_vm_launched is skipped since self.vm_launch_flag is set
2021-02-24 06:25:59,176 - DEBUG - Waiting to SSH to VM ctest-TestBasicPolicy-57660166-12389189, IP 193.48.202.67, Port 22
2021-02-24 06:25:59,204 - DEBUG - Error on ssh to ubuntu@169.254.0.3:22, result: /bin/bash: connect: Connection refused
/bin/bash: /dev/tcp/169.254.0.3/22: Connection refused {'failed': True, 'command': '(echo > /dev/tcp/169.254.0.3/22)', 'real_command': '/bin/bash -l -c "(echo > /dev/tcp/169.254.0.3/22)"', 'return_code': 1, 'succeeded': False, 'stderr': ''}
2021-02-24 06:25:59,403 - DEBUG - VM ctest-TestBasicPolicy-57660166-12389189 is NOT ready for SSH connections, VM status: ACTIVE
2021-02-24 06:26:04,404 - DEBUG - verify_vm_launched is skipped since self.vm_launch_flag is set
2021-02-24 06:26:04,404 - DEBUG - Waiting to SSH to VM ctest-TestBasicPolicy-57660166-12389189, IP 193.48.202.67, Port 22
2021-02-24 06:26:04,442 - DEBUG - Error on ssh to ubuntu@169.254.0.3:22, result: /bin/bash: connect: Connection refused
/bin/bash: /dev/tcp/169.254.0.3/22: Connection refused {'failed': True, 'command': '(echo > /dev/tcp/169.254.0.3/22)', 'real_command': '/bin/bash -l -c "(echo > /dev/tcp/169.254.0.3/22)"', 'return_code': 1, 'succeeded': False, 'stderr': ''}
2021-02-24 06:26:04,657 - DEBUG - VM ctest-TestBasicPolicy-57660166-12389189 is NOT ready for SSH connections, VM status: ACTIVE
2021-02-24 06:26:09,658 - DEBUG - verify_vm_launched is skipped since self.vm_launch_flag is set
2021-02-24 06:26:09,658 - DEBUG - Waiting to SSH to VM ctest-TestBasicPolicy-57660166-12389189, IP 193.48.202.67, Port 22
2021-02-24 06:26:09,686 - DEBUG - Error on ssh to ubuntu@169.254.0.3:22, result: /bin/bash: connect: Connection refused
/bin/bash: /dev/tcp/169.254.0.3/22: Connection refused {'failed': True, 'command': '(echo > /dev/tcp/169.254.0.3/22)', 'real_command': '/bin/bash -l -c "(echo > /dev/tcp/169.254.0.3/22)"', 'return_code': 1, 'succeeded': False, 'stderr': ''}
2021-02-24 06:26:09,898 - DEBUG - VM ctest-TestBasicPolicy-57660166-12389189 is NOT ready for SSH connections, VM status: ACTIVE
2021-02-24 06:26:14,899 - DEBUG - verify_vm_launched is skipped since self.vm_launch_flag is set
2021-02-24 06:26:14,899 - DEBUG - Waiting to SSH to VM ctest-TestBasicPolicy-57660166-12389189, IP 193.48.202.67, Port 22
2021-02-24 06:26:14,939 - DEBUG - Error on ssh to ubuntu@169.254.0.3:22, result: /bin/bash: connect: Connection refused
/bin/bash: /dev/tcp/169.254.0.3/22: Connection refused {'failed': True, 'command': '(echo > /dev/tcp/169.254.0.3/22)', 'real_command': '/bin/bash -l -c "(echo > /dev/tcp/169.254.0.3/22)"', 'return_code': 1, 'succeeded': False, 'stderr': ''}
2021-02-24 06:26:15,128 - DEBUG - VM ctest-TestBasicPolicy-57660166-12389189 is NOT ready for SSH connections, VM status: ACTIVE
2021-02-24 06:26:20,129 - DEBUG - verify_vm_launched is skipped since self.vm_launch_flag is set
2021-02-24 06:26:20,130 - DEBUG - Waiting to SSH to VM ctest-TestBasicPolicy-57660166-12389189, IP 193.48.202.67, Port 22
2021-02-24 06:26:20,156 - DEBUG - Error on ssh to ubuntu@169.254.0.3:22, result: /bin/bash: connect: Connection refused
/bin/bash: /dev/tcp/169.254.0.3/22: Connection refused {'failed': True, 'command': '(echo > /dev/tcp/169.254.0.3/22)', 'real_command': '/bin/bash -l -c "(echo > /dev/tcp/169.254.0.3/22)"', 'return_code': 1, 'succeeded': False, 'stderr': ''}
2021-02-24 06:26:20,519 - DEBUG - VM ctest-TestBasicPolicy-57660166-12389189 is NOT ready for SSH connections, VM status: ACTIVE
2021-02-24 06:26:25,520 - DEBUG - verify_vm_launched is skipped since self.vm_launch_flag is set
2021-02-24 06:26:25,520 - DEBUG - Waiting to SSH to VM ctest-TestBasicPolicy-57660166-12389189, IP 193.48.202.67, Port 22
2021-02-24 06:26:25,548 - DEBUG - Error on ssh to ubuntu@169.254.0.3:22, result: /bin/bash: connect: Connection refused
/bin/bash: /dev/tcp/169.254.0.3/22: Connection refused {'failed': True, 'command': '(echo > /dev/tcp/169.254.0.3/22)', 'real_command': '/bin/bash -l -c "(echo > /dev/tcp/169.254.0.3/22)"', 'return_code': 1, 'succeeded': False, 'stderr': ''}
2021-02-24 06:26:25,733 - DEBUG - VM ctest-TestBasicPolicy-57660166-12389189 is NOT ready for SSH connections, VM status: ACTIVE
2021-02-24 06:26:30,734 - DEBUG - verify_vm_launched is skipped since self.vm_launch_flag is set
2021-02-24 06:26:30,734 - DEBUG - Waiting to SSH to VM ctest-TestBasicPolicy-57660166-12389189, IP 193.48.202.67, Port 22
2021-02-24 06:26:30,762 - DEBUG - Error on ssh to ubuntu@169.254.0.3:22, result: /bin/bash: connect: Connection refused
/bin/bash: /dev/tcp/169.254.0.3/22: Connection refused {'failed': True, 'command': '(echo > /dev/tcp/169.254.0.3/22)', 'real_command': '/bin/bash -l -c "(echo > /dev/tcp/169.254.0.3/22)"', 'return_code': 1, 'succeeded': False, 'stderr': ''}
2021-02-24 06:26:30,967 - DEBUG - VM ctest-TestBasicPolicy-57660166-12389189 is NOT ready for SSH connections, VM status: ACTIVE
2021-02-24 06:26:35,968 - DEBUG - verify_vm_launched is skipped since self.vm_launch_flag is set
2021-02-24 06:26:35,969 - DEBUG - Waiting to SSH to VM ctest-TestBasicPolicy-57660166-12389189, IP 193.48.202.67, Port 22
2021-02-24 06:26:35,997 - DEBUG - Error on ssh to ubuntu@169.254.0.3:22, result: /bin/bash: connect: Connection refused
/bin/bash: /dev/tcp/169.254.0.3/22: Connection refused {'failed': True, 'command': '(echo > /dev/tcp/169.254.0.3/22)', 'real_command': '/bin/bash -l -c "(echo > /dev/tcp/169.254.0.3/22)"', 'return_code': 1, 'succeeded': False, 'stderr': ''}
2021-02-24 06:26:36,189 - DEBUG - VM ctest-TestBasicPolicy-57660166-12389189 is NOT ready for SSH connections, VM status: ACTIVE
2021-02-24 06:26:41,190 - DEBUG - verify_vm_launched is skipped since self.vm_launch_flag is set
2021-02-24 06:26:41,190 - DEBUG - Waiting to SSH to VM ctest-TestBasicPolicy-57660166-12389189, IP 193.48.202.67, Port 22
2021-02-24 06:26:41,298 - DEBUG - VM ctest-TestBasicPolicy-57660166-12389189 is ready for SSH connections
2021-02-24 06:26:41,299 - INFO - Waiting for VM ctest-TestBasicPolicy-57660166-60249790 to be up..
2021-02-24 06:26:41,511 - DEBUG - VM <Server: ctest-TestBasicPolicy-57660166-60249790> is in ACTIVE state now
2021-02-24 06:26:41,512 - INFO - VM name : ctest-TestBasicPolicy-57660166-60249790
2021-02-24 06:26:41,737 - DEBUG - VM ctest-TestBasicPolicy-57660166-60249790 ID is 7519498e-4132-4ff3-97d1-90bee2daeb58
2021-02-24 06:26:41,737 - DEBUG - VM ctest-TestBasicPolicy-57660166-60249790 launched on Node nodec9.maas
2021-02-24 06:26:41,941 - DEBUG - Requesting: https://192.168.7.34:8082/virtual-machine/7519498e-4132-4ff3-97d1-90bee2daeb58
2021-02-24 06:26:41,974 - DEBUG - Requesting: https://192.168.7.34:8082/virtual-machine-interface/828c6706-006d-45ae-9faf-88c5c1c22250
2021-02-24 06:26:43,184 - DEBUG - (True, 'PING 169.254.0.5 (169.254.0.5) 56(84) bytes of data.\r\n64 bytes from 169.254.0.5: icmp_seq=1 ttl=63 time=4.82 ms\r\n64 bytes from 169.254.0.5: icmp_seq=2 ttl=63 time=1.49 ms\r\n\r\n--- 169.254.0.5 ping statistics ---\r\n2 packets transmitted, 2 received, 0% packet loss, time 1001ms\r\nrtt min/avg/max/mdev = 1.492/3.159/4.827/1.668 ms')
2021-02-24 06:26:43,184 - INFO - Ping to Metadata IP 169.254.0.5 of VM ctest-TestBasicPolicy-57660166-60249790 passed
2021-02-24 06:26:43,248 - DEBUG - verify_vm_launched is skipped since self.vm_launch_flag is set
2021-02-24 06:26:43,248 - DEBUG - Waiting to SSH to VM ctest-TestBasicPolicy-57660166-60249790, IP 27.5.226.195, Port 22
2021-02-24 06:26:43,344 - DEBUG - VM ctest-TestBasicPolicy-57660166-60249790 is ready for SSH connections
2021-02-24 06:26:43,344 - DEBUG - verify_vm_launched is skipped since self.vm_launch_flag is set
2021-02-24 06:26:43,344 - DEBUG - Running remote_cmd, Cmd : ping -s 56 -c 3 -W 1  27.5.226.195, host_string: ubuntu@169.254.0.3, password: ubuntugateway: root@192.168.7.9, gateway password: c0ntrail123
2021-02-24 06:26:43,345 - DEBUG - ping -s 56 -c 3 -W 1  27.5.226.195
2021-02-24 06:27:05,753 - DEBUG - PING 27.5.226.195 (27.5.226.195) 56(84) bytes of data.
64 bytes from 27.5.226.195: icmp_req=1 ttl=63 time=10.3 ms
64 bytes from 27.5.226.195: icmp_req=2 ttl=63 time=1.83 ms
64 bytes from 27.5.226.195: icmp_req=3 ttl=63 time=3.36 ms

--- 27.5.226.195 ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2003ms
rtt min/avg/max/mdev = 1.830/5.190/10.375/3.720 ms
2021-02-24 06:27:05,753 - INFO - Ping to IP 27.5.226.195 from VM ctest-TestBasicPolicy-57660166-12389189 passed
2021-02-24 06:27:05,882 - DEBUG - Policy Update Response {"network-policy": {"href": "https://192.168.7.34:8082/network-policy/c48a8e7d-0766-4161-abd1-c666f60b5c38", "uuid": "c48a8e7d-0766-4161-abd1-c666f60b5c38"}}
2021-02-24 06:27:05,882 - DEBUG - verify_vm_launched is skipped since self.vm_launch_flag is set
2021-02-24 06:27:05,883 - DEBUG - Running remote_cmd, Cmd : ping -s 56 -c 3 -W 1  27.5.226.195, host_string: ubuntu@169.254.0.3, password: ubuntugateway: root@192.168.7.9, gateway password: c0ntrail123
2021-02-24 06:27:05,883 - DEBUG - ping -s 56 -c 3 -W 1  27.5.226.195
2021-02-24 06:27:09,632 - DEBUG - PING 27.5.226.195 (27.5.226.195) 56(84) bytes of data.

--- 27.5.226.195 ping statistics ---
3 packets transmitted, 0 received, 100% packet loss, time 1999ms
2021-02-24 06:27:09,633 - WARNING - Ping to IP 27.5.226.195 from VM ctest-TestBasicPolicy-57660166-12389189 failed
2021-02-24 06:27:09,633 - INFO - Deleting VM ctest-TestBasicPolicy-57660166-60249790
2021-02-24 06:27:10,006 - INFO - Deleting VM ctest-TestBasicPolicy-57660166-12389189
2021-02-24 06:27:11,644 - INFO - Deleted policy ctest-policy-allow-all-15672784
2021-02-24 06:27:11,645 - INFO - Deleting VN ctest-vn-25714786 
2021-02-24 06:27:11,955 - DEBUG - Response for deleting network ()
2021-02-24 06:27:11,956 - DEBUG - Requesting: https://192.168.7.20:8082/routing-instance/9a806454-7e85-4197-b9b3-b2832d270c24
2021-02-24 06:27:11,978 - DEBUG - Response Code: 404
2021-02-24 06:27:11,978 - DEBUG - Requesting: https://192.168.7.20:8082/domains
2021-02-24 06:27:11,997 - DEBUG - Requesting: https://192.168.7.20:8082/domain/f27c063f-c6c4-434f-a616-97e72e0043e5
2021-02-24 06:27:12,047 - DEBUG - Requesting: https://192.168.7.20:8082/project/74efdb0c-b51b-486c-bef3-bb1dd3336b3e
2021-02-24 06:27:12,110 - INFO - Validated that VN ctest-vn-25714786 is not found in API Server
2021-02-24 06:27:12,228 - DEBUG - VN ctest-vn-25714786 is not present in Agent 192.168.7.19 
2021-02-24 06:27:12,336 - DEBUG - VN ctest-vn-25714786 is not present in Agent 192.168.7.9 
2021-02-24 06:27:12,336 - INFO - Validated that VN ctest-vn-25714786 is not in any agent
2021-02-24 06:27:12,785 - INFO - Validated that Routing instances and Config db in Control-nodes does not have VN ctest-vn-25714786 info
2021-02-24 06:27:12,786 - INFO - Deleting VN ctest-vn-44147984 
2021-02-24 06:27:13,057 - DEBUG - Response for deleting network ()
2021-02-24 06:27:13,058 - DEBUG - Requesting: https://192.168.7.20:8082/routing-instance/481f89c7-9ff0-4a88-9382-69b7b14ecc36
2021-02-24 06:27:13,081 - DEBUG - Response Code: 404
2021-02-24 06:27:13,081 - DEBUG - Requesting: https://192.168.7.20:8082/domains
2021-02-24 06:27:13,103 - DEBUG - Requesting: https://192.168.7.20:8082/domain/f27c063f-c6c4-434f-a616-97e72e0043e5
2021-02-24 06:27:13,152 - DEBUG - Requesting: https://192.168.7.20:8082/project/74efdb0c-b51b-486c-bef3-bb1dd3336b3e
2021-02-24 06:27:13,214 - INFO - Validated that VN ctest-vn-44147984 is not found in API Server
2021-02-24 06:27:13,336 - DEBUG - VN ctest-vn-44147984 is not present in Agent 192.168.7.19 
2021-02-24 06:27:13,443 - DEBUG - VN ctest-vn-44147984 is not present in Agent 192.168.7.9 
2021-02-24 06:27:13,443 - INFO - Validated that VN ctest-vn-44147984 is not in any agent
2021-02-24 06:27:13,881 - INFO - Validated that Routing instances and Config db in Control-nodes does not have VN ctest-vn-44147984 info
2021-02-24 06:27:15,898 - DEBUG - No XMPP flaps were noticed during the test
2021-02-24 06:27:15,898 - INFO - END TEST : test_basic_policy_allow_deny : PASSED[0:02:31]
2021-02-24 06:27:15,898 - INFO - --------------------------------------------------------------------------------
2021-02-24 06:27:17,566 - INFO - Deleted project: ctest-TestBasicPolicy-57660166, ID : 74efdb0c-b51b-486c-bef3-bb1dd3336b3e 
