<link href="txtsyle.css" rel="stylesheet" type="text/css" />2021-02-22 05:01:35,398 - INFO - Reading existing Domain with UUID f27c063f-c6c4-434f-a616-97e72e0043e5
2021-02-22 05:01:35,428 - INFO - Using existing domain ['admin_domain'](f27c063f-c6c4-434f-a616-97e72e0043e5)
2021-02-22 05:01:36,084 - INFO - Project ctest-TestSvcRegr-09180439 not found, creating it
2021-02-22 05:01:37,293 - INFO - Created Project:ctest-TestSvcRegr-09180439, ID : 1a1af943-d322-454c-b9cc-25c937c193eb 
2021-02-22 05:01:43,098 - INFO - ================================================================================
2021-02-22 05:01:43,098 - INFO - STARTING TEST    : test_svc_in_network_datapath
2021-02-22 05:01:44,452 - DEBUG - Nothing to compare xmpp stats {'192.168.7.19': {'192.168.27.20': '0', '192.168.27.34': '0'}, '192.168.7.9': {'192.168.27.20': '0', '192.168.27.34': '0'}} with
2021-02-22 05:01:44,453 - INFO - Initial checks done. Running the testcase now
2021-02-22 05:01:44,453 - INFO - 
2021-02-22 05:01:45,520 - DEBUG - Response for create_network : {'network': {'status': 'ACTIVE', 'router:external': False, 'subnets': [], 'fq_name': ['admin_domain', 'ctest-TestSvcRegr-09180439', 'ctest-mgmt_vn-31287329'], 'name': 'ctest-mgmt_vn-31287329', 'admin_state_up': True, 'tenant_id': '1a1af943d322454cb9cc25c937c193eb', 'created_at': None, 'updated_at': None, 'shared': False, 'port_security_enabled': True, 'project_id': '1a1af943d322454cb9cc25c937c193eb', 'id': '6d4ba4ae-8840-47bf-aac4-99df7c2fa076', 'description': ''}}
2021-02-22 05:01:45,870 - DEBUG - Response for create_subnet : {'subnet': {'name': '', 'enable_dhcp': True, 'network_id': '6d4ba4ae-8840-47bf-aac4-99df7c2fa076', 'tenant_id': '1a1af943d322454cb9cc25c937c193eb', 'created_at': '2021-02-22T05:01:45.210741', 'dns_nameservers': [], 'updated_at': '2021-02-22T05:01:45.210741', 'ipv6_ra_mode': None, 'allocation_pools': [{'start': '17.176.3.130', 'end': '17.176.3.190'}], 'gateway_ip': '17.176.3.129', 'dns_server_address': '17.176.3.130', 'ipv6_address_mode': None, 'ip_version': 4, 'host_routes': [], 'cidr': '17.176.3.128/26', 'id': '9e48899e-eed4-431f-96ed-58d453836c84'}}
2021-02-22 05:01:45,922 - INFO - Created VN ctest-mgmt_vn-31287329
2021-02-22 05:01:45,958 - DEBUG - VN ctest-mgmt_vn-31287329 UUID is 6d4ba4ae-8840-47bf-aac4-99df7c2fa076
2021-02-22 05:01:46,111 - DEBUG - Requesting: https://192.168.7.20:8082/domains
2021-02-22 05:01:46,632 - DEBUG - Requesting: https://192.168.7.20:8082/domains
2021-02-22 05:01:46,710 - DEBUG - Requesting: https://192.168.7.20:8082/domain/f27c063f-c6c4-434f-a616-97e72e0043e5
2021-02-22 05:01:46,760 - DEBUG - Requesting: https://192.168.7.20:8082/project/1a1af943-d322-454c-b9cc-25c937c193eb
2021-02-22 05:01:46,827 - DEBUG - Requesting: https://192.168.7.20:8082/virtual-network/6d4ba4ae-8840-47bf-aac4-99df7c2fa076
2021-02-22 05:01:46,858 - DEBUG - Requesting: https://192.168.7.20:8082/virtual-network/6d4ba4ae-8840-47bf-aac4-99df7c2fa076
2021-02-22 05:01:46,885 - DEBUG - Requesting: https://192.168.7.20:8082/routing-instance/13b64360-05ea-4842-8c22-778cc23d31f6
2021-02-22 05:01:46,910 - DEBUG - Requesting: https://192.168.7.20:8082/routing-instance/13b64360-05ea-4842-8c22-778cc23d31f6
2021-02-22 05:01:46,936 - DEBUG - Requesting: https://192.168.7.20:8082/route-target/4c793638-cfb7-43a5-98bf-8a30b3abf7e0
2021-02-22 05:01:46,961 - DEBUG - Route Targets: ['target:64512:8000017']
2021-02-22 05:01:46,961 - DEBUG - Requesting: https://192.168.7.20:8082/virtual-network/6d4ba4ae-8840-47bf-aac4-99df7c2fa076
2021-02-22 05:01:46,984 - DEBUG - Requesting: https://192.168.7.20:8082/routing-instance/13b64360-05ea-4842-8c22-778cc23d31f6
2021-02-22 05:01:47,025 - INFO - Verified VN network id 28 for VN 6d4ba4ae-8840-47bf-aac4-99df7c2fa076
2021-02-22 05:01:47,025 - INFO - Verifications in API Server for VN ctest-mgmt_vn-31287329 passed
2021-02-22 05:01:47,026 - DEBUG - Requesting: https://192.168.7.20:8082/virtual-network/6d4ba4ae-8840-47bf-aac4-99df7c2fa076
2021-02-22 05:01:47,053 - DEBUG - Requesting: https://192.168.7.20:8082/routing-instance/13b64360-05ea-4842-8c22-778cc23d31f6
2021-02-22 05:01:47,077 - DEBUG - Requesting: https://192.168.7.20:8082/routing-instance/13b64360-05ea-4842-8c22-778cc23d31f6
2021-02-22 05:01:47,102 - DEBUG - Requesting: https://192.168.7.20:8082/route-target/4c793638-cfb7-43a5-98bf-8a30b3abf7e0
2021-02-22 05:01:47,125 - DEBUG - Requesting: https://192.168.7.20:8083/Snh_IFMapTableShowReq?table_name=virtual-network&search_string=virtual-network:admin_domain:ctest-TestSvcRegr-09180439:ctest-mgmt_vn-31287329
2021-02-22 05:01:47,142 - DEBUG - Control-node 192.168.7.20 : VN object is : {'node_name': 'virtual-network:admin_domain:ctest-TestSvcRegr-09180439:ctest-mgmt_vn-31287329', 'interests': '-', 'advertised': '-', 'dbentryflags': None, 'obj_info': {'sequence_number': '0', 'origin': 'Cassandra', 'data': {'id-perms': {'permissions': {'owner': 'ctest-TestSvcRegr-09180439', 'owner-access': '7', 'group': 'admin', 'group-access': '7', 'other-access': '7'}, 'uuid': {'uuid-mslong': '7875569442904623039', 'uuid-lslong': '12305129267023290486'}, 'enable': 'true', 'created': '2021-02-22T05:01:44', 'last-modified': '2021-02-22T05:01:45', 'description': None, 'user-visible': 'true', 'creator': None}}}, 'neighbors': None, 'last_modified': '00:00:01.353921'}
2021-02-22 05:01:47,142 - DEBUG - Requesting: https://192.168.7.20:8083/Snh_ShowRoutingInstanceReq?name=admin_domain:ctest-TestSvcRegr-09180439:ctest-mgmt_vn-31287329:ctest-mgmt_vn-31287329
2021-02-22 05:01:47,163 - DEBUG - Route Targets: ['target:64512:8000017']
2021-02-22 05:01:47,163 - DEBUG - Requesting: https://192.168.7.29:8083/Snh_IFMapTableShowReq?table_name=virtual-network&search_string=virtual-network:admin_domain:ctest-TestSvcRegr-09180439:ctest-mgmt_vn-31287329
2021-02-22 05:01:47,186 - DEBUG - Control-node 192.168.7.29 : VN object is : {'node_name': 'virtual-network:admin_domain:ctest-TestSvcRegr-09180439:ctest-mgmt_vn-31287329', 'interests': '-', 'advertised': '-', 'dbentryflags': None, 'obj_info': {'sequence_number': '0', 'origin': 'Cassandra', 'data': {'id-perms': {'permissions': {'owner': 'ctest-TestSvcRegr-09180439', 'owner-access': '7', 'group': 'admin', 'group-access': '7', 'other-access': '7'}, 'uuid': {'uuid-mslong': '7875569442904623039', 'uuid-lslong': '12305129267023290486'}, 'enable': 'true', 'created': '2021-02-22T05:01:44', 'last-modified': '2021-02-22T05:01:45', 'description': None, 'user-visible': 'true', 'creator': None}}}, 'neighbors': None, 'last_modified': '00:00:01.397988'}
2021-02-22 05:01:47,186 - DEBUG - Requesting: https://192.168.7.29:8083/Snh_ShowRoutingInstanceReq?name=admin_domain:ctest-TestSvcRegr-09180439:ctest-mgmt_vn-31287329:ctest-mgmt_vn-31287329
2021-02-22 05:01:47,210 - DEBUG - Route Targets: ['target:64512:8000017']
2021-02-22 05:01:47,211 - DEBUG - Requesting: https://192.168.7.34:8083/Snh_IFMapTableShowReq?table_name=virtual-network&search_string=virtual-network:admin_domain:ctest-TestSvcRegr-09180439:ctest-mgmt_vn-31287329
2021-02-22 05:01:47,230 - DEBUG - Control-node 192.168.7.34 : VN object is : {'node_name': 'virtual-network:admin_domain:ctest-TestSvcRegr-09180439:ctest-mgmt_vn-31287329', 'interests': '-', 'advertised': '-', 'dbentryflags': None, 'obj_info': {'sequence_number': '0', 'origin': 'Cassandra', 'data': {'id-perms': {'permissions': {'owner': 'ctest-TestSvcRegr-09180439', 'owner-access': '7', 'group': 'admin', 'group-access': '7', 'other-access': '7'}, 'uuid': {'uuid-mslong': '7875569442904623039', 'uuid-lslong': '12305129267023290486'}, 'enable': 'true', 'created': '2021-02-22T05:01:44', 'last-modified': '2021-02-22T05:01:45', 'description': None, 'user-visible': 'true', 'creator': None}}}, 'neighbors': None, 'last_modified': '00:00:01.440968'}
2021-02-22 05:01:47,230 - DEBUG - Requesting: https://192.168.7.34:8083/Snh_ShowRoutingInstanceReq?name=admin_domain:ctest-TestSvcRegr-09180439:ctest-mgmt_vn-31287329:ctest-mgmt_vn-31287329
2021-02-22 05:01:47,249 - DEBUG - Route Targets: ['target:64512:8000017']
2021-02-22 05:01:47,249 - INFO - On all control nodes, Config, RI and RT verification for VN ctest-mgmt_vn-31287329 passed
2021-02-22 05:01:47,250 - DEBUG - ====Verifying policy data for ctest-mgmt_vn-31287329 in API_Server ======
2021-02-22 05:01:47,250 - DEBUG - Requesting: https://192.168.7.20:8082/domains
2021-02-22 05:01:47,278 - DEBUG - Requesting: https://192.168.7.20:8082/domain/f27c063f-c6c4-434f-a616-97e72e0043e5
2021-02-22 05:01:47,315 - DEBUG - Requesting: https://192.168.7.20:8082/project/1a1af943-d322-454c-b9cc-25c937c193eb
2021-02-22 05:01:47,382 - DEBUG - Requesting: https://192.168.7.20:8082/virtual-network/6d4ba4ae-8840-47bf-aac4-99df7c2fa076
2021-02-22 05:01:47,407 - DEBUG - =>VN ctest-mgmt_vn-31287329 has no policy to be verified
2021-02-22 05:01:47,408 - DEBUG - Verifying the vn in opserver
2021-02-22 05:01:47,408 - DEBUG - Verifying the admin_domain:ctest-TestSvcRegr-09180439:ctest-mgmt_vn-31287329 virtual network link  through opserver 192.168.7.20
2021-02-22 05:01:47,409 - DEBUG - Requesting: https://192.168.7.20:8081/analytics/uves/virtual-networks
2021-02-22 05:01:47,960 - DEBUG - Requesting: https://192.168.7.20:8081/analytics/uves/virtual-networks
2021-02-22 05:01:48,104 - DEBUG - vn link and name as {'href': 'https://192.168.7.20:8081/analytics/uves/virtual-network/admin_domain:ctest-TestSvcRegr-09180439:ctest-mgmt_vn-31287329?flat', 'name': 'admin_domain:ctest-TestSvcRegr-09180439:ctest-mgmt_vn-31287329'}
2021-02-22 05:01:48,104 - DEBUG - Verifying the admin_domain:ctest-TestSvcRegr-09180439:ctest-mgmt_vn-31287329 virtual network link  through opserver 192.168.7.29
2021-02-22 05:01:48,105 - DEBUG - Requesting: https://192.168.7.29:8081/analytics/uves/virtual-networks
2021-02-22 05:01:48,618 - DEBUG - Requesting: https://192.168.7.29:8081/analytics/uves/virtual-networks
2021-02-22 05:01:48,752 - DEBUG - Verifying the admin_domain:ctest-TestSvcRegr-09180439:ctest-mgmt_vn-31287329 virtual network link  through opserver 192.168.7.34
2021-02-22 05:01:48,752 - DEBUG - Requesting: https://192.168.7.34:8081/analytics/uves/virtual-networks
2021-02-22 05:01:49,228 - DEBUG - Requesting: https://192.168.7.34:8081/analytics/uves/virtual-networks
2021-02-22 05:01:49,360 - DEBUG - vn link and name as {'href': 'https://192.168.7.34:8081/analytics/uves/virtual-network/admin_domain:ctest-TestSvcRegr-09180439:ctest-mgmt_vn-31287329?flat', 'name': 'admin_domain:ctest-TestSvcRegr-09180439:ctest-mgmt_vn-31287329'}
2021-02-22 05:01:49,360 - INFO - Validated that VN admin_domain:ctest-TestSvcRegr-09180439:ctest-mgmt_vn-31287329 is found in opserver
2021-02-22 05:01:49,600 - DEBUG - Do not have enough data to verify VN in agent
2021-02-22 05:01:49,716 - DEBUG - VRF ids for VN ctest-mgmt_vn-31287329: {}
2021-02-22 05:01:50,060 - DEBUG - Response for create_network : {'network': {'status': 'ACTIVE', 'router:external': False, 'subnets': [], 'fq_name': ['admin_domain', 'ctest-TestSvcRegr-09180439', 'ctest-left_vn-14165758'], 'name': 'ctest-left_vn-14165758', 'admin_state_up': True, 'tenant_id': '1a1af943d322454cb9cc25c937c193eb', 'created_at': None, 'updated_at': None, 'shared': False, 'port_security_enabled': True, 'project_id': '1a1af943d322454cb9cc25c937c193eb', 'id': 'aae1c310-0eaf-4064-ac0a-cf1b06b43cdb', 'description': ''}}
2021-02-22 05:03:20,091 - INFO - Deleting VN ctest-mgmt_vn-31287329 
2021-02-22 05:03:20,313 - DEBUG - Response for deleting network ()
2021-02-22 05:03:20,314 - DEBUG - Requesting: https://192.168.7.20:8082/routing-instance/13b64360-05ea-4842-8c22-778cc23d31f6
2021-02-22 05:03:20,334 - DEBUG - Response Code: 404
2021-02-22 05:03:20,335 - DEBUG - Requesting: https://192.168.7.20:8082/domains
2021-02-22 05:03:20,359 - DEBUG - Requesting: https://192.168.7.20:8082/domain/f27c063f-c6c4-434f-a616-97e72e0043e5
2021-02-22 05:03:20,395 - DEBUG - Requesting: https://192.168.7.20:8082/project/1a1af943-d322-454c-b9cc-25c937c193eb
2021-02-22 05:03:20,466 - INFO - Validated that VN ctest-mgmt_vn-31287329 is not found in API Server
2021-02-22 05:03:20,584 - DEBUG - VN ctest-mgmt_vn-31287329 is not present in Agent 192.168.7.19 
2021-02-22 05:03:20,700 - DEBUG - VN ctest-mgmt_vn-31287329 is not present in Agent 192.168.7.9 
2021-02-22 05:03:20,700 - INFO - Validated that VN ctest-mgmt_vn-31287329 is not in any agent
2021-02-22 05:03:20,824 - DEBUG - Requesting: https://192.168.7.20:8083/Snh_ShowRoutingInstanceReq?name=admin_domain:ctest-TestSvcRegr-09180439:ctest-mgmt_vn-31287329:ctest-mgmt_vn-31287329
2021-02-22 05:03:20,885 - DEBUG - Requesting: https://192.168.7.29:8083/Snh_ShowRoutingInstanceReq?name=admin_domain:ctest-TestSvcRegr-09180439:ctest-mgmt_vn-31287329:ctest-mgmt_vn-31287329
2021-02-22 05:03:21,025 - DEBUG - Requesting: https://192.168.7.34:8083/Snh_ShowRoutingInstanceReq?name=admin_domain:ctest-TestSvcRegr-09180439:ctest-mgmt_vn-31287329:ctest-mgmt_vn-31287329
2021-02-22 05:03:21,088 - DEBUG - Requesting: https://192.168.7.34:8083/Snh_IFMapTableShowReq?table_name=virtual-network&search_string=virtual-network:admin_domain:ctest-TestSvcRegr-09180439:ctest-mgmt_vn-31287329
2021-02-22 05:03:21,148 - INFO - Validated that Routing instances and Config db in Control-nodes does not have VN ctest-mgmt_vn-31287329 info
2021-02-22 05:03:22,480 - ERROR - ConnectFailure
Python 3.6.8: /usr/bin/python3
Mon Feb 22 05:03:20 2021

A problem occurred in a Python script.  Here is the sequence of
function calls leading up to the error, in the order they occurred.

 /contrail-test/tcutils/wrappers.py in wrapper(self=<scripts.svc_firewall.test_svc_fw.TestSvcRegr.te...rk_datapath[ci_sanity,vcenter] id=0x7fdfb2f7c438>, *args=(), **kwargs={})
   80             log.info('Initial checks done. Running the testcase now')
   81             log.info('')
   82             result = function(self, *args, **kwargs)
   83             if self.inputs.upgrade:
   84                 pid = os.getpid()
result = None
function = <function TestSvcRegr.test_svc_in_network_datapath>
self = <scripts.svc_firewall.test_svc_fw.TestSvcRegr.te...rk_datapath[ci_sanity,vcenter] id=0x7fdfb2f7c438>
args = ()
kwargs = {}

 /contrail-test/scripts/svc_firewall/test_svc_fw.py in test_svc_in_network_datapath(self=<scripts.svc_firewall.test_svc_fw.TestSvcRegr.te...rk_datapath[ci_sanity,vcenter] id=0x7fdfb2f7c438>)
   31     def test_svc_in_network_datapath(self):
   32         return self.verify_svc_chain(svc_img_name='cirros_in_net', service_mode='in-network',
   33                                      create_svms=True)
   34 
   35 
create_svms undefined

 /contrail-test/common/servicechain/verify.py in verify_svc_chain(self=<scripts.svc_firewall.test_svc_fw.TestSvcRegr.te...rk_datapath[ci_sanity,vcenter] id=0x7fdfb2f7c438>, *args=(), **kwargs={'create_svms': True, 'service_mode': 'in-network', 'svc_img_name': 'cirros_in_net'})
  326     def verify_svc_chain(self, *args, **kwargs):
  327         svc_chain_info = kwargs.get('svc_chain_info')
  328         ret_dict = svc_chain_info or self.config_svc_chain(*args, **kwargs)
  329         proto = kwargs.get('proto', 'any')
  330         left_vn_fq_name = ret_dict.get('left_vn_fixture').vn_fq_name
ret_dict undefined
svc_chain_info = None
self = <scripts.svc_firewall.test_svc_fw.TestSvcRegr.te...rk_datapath[ci_sanity,vcenter] id=0x7fdfb2f7c438>
self.config_svc_chain = <bound method ConfigSvcChain.config_svc_chain of...k_datapath[ci_sanity,vcenter] id=0x7fdfb2f7c438>>
args = ()
kwargs = {'create_svms': True, 'service_mode': 'in-network', 'svc_img_name': 'cirros_in_net'}

 /contrail-test/common/servicechain/config.py in config_svc_chain(self=<scripts.svc_firewall.test_svc_fw.TestSvcRegr.te...rk_datapath[ci_sanity,vcenter] id=0x7fdfb2f7c438>, service_mode='in-network', service_type='firewall', max_inst=1, proto='any', svc_chain_type='parallel', src_ports=[0, 65535], dst_ports=[0, 65535], svc_img_name='cirros_in_net', st_version=2, mgmt_vn_name='ctest-mgmt_vn-31287329', mgmt_vn_subnets=['17.176.3.128/26'], mgmt_vn_fixture=<vn_test.VNFixture object>, left_vn_name=None, left_vn_subnets=[], left_vn_fixture=None, right_vn_name=None, right_vn_subnets=[], right_vn_fixture=None, left_lr_child_vn_fixture=None, right_lr_child_vn_fixture=None, left_vm_name=None, left_vm_fixture=None, right_vm_name=None, right_vm_fixture=None, image_name='ubuntu-traffic', policy_fixture=None, st_fixture=None, si_fixture=None, port_tuples_props=None, static_route=None, svm_fixtures=[], create_svms=True, evpn=False, modify_rules=False, policy_action='pass', hosts=[], **kwargs={})
  482                                                     left_vn_fixture,
  483                                                     'left_vn',
  484                                                     **kwargs)
  485 
  486         # Right
kwargs = {}

 /contrail-test/common/servicechain/config.py in _get_vn_for_config(self=<scripts.svc_firewall.test_svc_fw.TestSvcRegr.te...rk_datapath[ci_sanity,vcenter] id=0x7fdfb2f7c438>, vn_name='ctest-left_vn-14165758', vn_subnets=['191.96.77.64/26'], vn_fixture=None, vn_name_prefix='left_vn', **kwargs={})
  373             vn_subnets = vn_subnets or \
  374                                   [get_random_cidr(af=self.inputs.get_af())]
  375             vn_fixture = vn_fixture or self.config_vn(vn_name, vn_subnets, **kwargs)
  376         vn_fq_name = vn_fixture.vn_fq_name
  377         return (vn_name, vn_subnets, vn_fixture, vn_fq_name)
vn_fixture = None
self = <scripts.svc_firewall.test_svc_fw.TestSvcRegr.te...rk_datapath[ci_sanity,vcenter] id=0x7fdfb2f7c438>
self.config_vn = <bound method ConfigSvcChain.config_vn of <scrip...k_datapath[ci_sanity,vcenter] id=0x7fdfb2f7c438>>
vn_name = 'ctest-left_vn-14165758'
vn_subnets = ['191.96.77.64/26']
kwargs = {}

 /contrail-test/common/servicechain/config.py in config_vn(self=<scripts.svc_firewall.test_svc_fw.TestSvcRegr.te...rk_datapath[ci_sanity,vcenter] id=0x7fdfb2f7c438>, vn_name='ctest-left_vn-14165758', vn_net=['191.96.77.64/26'], **kwargs={})
  154         vn_fixture = self.useFixture(VNFixture(
  155             project_name=self.inputs.project_name, connections=self.connections,
  156             vn_name=vn_name, inputs=self.inputs, subnets=vn_net, **kwargs))
  157         assert vn_fixture.verify_on_setup()
  158         return vn_fixture
vn_name = 'ctest-left_vn-14165758'
inputs undefined
self = <scripts.svc_firewall.test_svc_fw.TestSvcRegr.te...rk_datapath[ci_sanity,vcenter] id=0x7fdfb2f7c438>
self.inputs = <common.contrail_test_init.ContrailTestInit object>
subnets undefined
vn_net = ['191.96.77.64/26']
kwargs = {}

 /usr/local/lib/python3.6/site-packages/testtools/testcase.py in useFixture(self=<scripts.svc_firewall.test_svc_fw.TestSvcRegr.te...rk_datapath[ci_sanity,vcenter] id=0x7fdfb2f7c438>, fixture=<vn_test.VNFixture object>)
  754                 # Gather_details worked, so raise the exception setUp
  755                 # encountered.
  756                 reraise(*exc_info)
  757         else:
  758             self.addCleanup(fixture.cleanUp)
global reraise = <function reraise>
exc_info = (<class 'keystoneauth1.exceptions.connection.ConnectFailure'>, ConnectFailure("Unable to establish connection t...ote end closed connection without response',))",), <traceback object>)

 /usr/local/lib/python3.6/site-packages/testtools/_compat3x.py in reraise(exc_class=<class 'keystoneauth1.exceptions.connection.ConnectFailure'>, exc_obj=ConnectFailure("Unable to establish connection t...ote end closed connection without response',))",), exc_tb=<traceback object>, _marker=<object object>)
   13 
   14 def reraise(exc_class, exc_obj, exc_tb, _marker=object()):
   15     """Re-raise an exception received from sys.exc_info() or similar."""
   16     raise exc_obj.with_traceback(exc_tb)
   17 
exc_obj = ConnectFailure("Unable to establish connection t...ote end closed connection without response',))",)
exc_obj.with_traceback = <built-in method with_traceback of ConnectFailure object>
exc_tb = <traceback object>

 /usr/local/lib/python3.6/site-packages/testtools/testcase.py in useFixture(self=<scripts.svc_firewall.test_svc_fw.TestSvcRegr.te...rk_datapath[ci_sanity,vcenter] id=0x7fdfb2f7c438>, fixture=<vn_test.VNFixture object>)
  729         """
  730         try:
  731             fixture.setUp()
  732         except MultipleExceptions as e:
  733             if (fixtures is not None and
fixture = <vn_test.VNFixture object>
fixture.setUp = <bound method VNFixture.setUp of <vn_test.VNFixture object>>

 /contrail-test/fixtures/vn_test.py in setUp(self=<vn_test.VNFixture object>)
  442     def setUp(self):
  443         super(VNFixture, self).setUp()
  444         self.create()
  445 
  446     def create(self):
self = <vn_test.VNFixture object>
self.create = <bound method VNFixture.create of <vn_test.VNFixture object>>

 /contrail-test/fixtures/vn_test.py in create(self=<vn_test.VNFixture object>)
  455             self._create_vn_api(self.vn_name, self.project_obj)
  456         else:
  457             self._create_vn_orch()
  458         if not self.obj:
  459              self.logger.debug('VN %s not present' % (self.vn_name))
self = <vn_test.VNFixture object>
self._create_vn_orch = <bound method VNFixture._create_vn_orch of <vn_test.VNFixture object>>

 /contrail-test/fixtures/vn_test.py in _create_vn_orch(self=<vn_test.VNFixture object>)
  313                                                 sriov_provider_network=self.sriov_provider_network,
  314                                                 disable_gateway=self.disable_gateway,
  315                                                 dns_nameservers_list=self.dns_nameservers_list)
  316                 if self.obj:
  317                     self.logger.info('Created VN %s' %(self.vn_name))
dns_nameservers_list undefined
self = <vn_test.VNFixture object>
self.dns_nameservers_list = None

 /contrail-test/fixtures/openstack.py in create_vn(self=<openstack.OpenstackOrchestrator object>, name='ctest-left_vn-14165758', subnets=[{'cidr': '191.96.77.64/26', 'enable_dhcp': True, 'ip_version': '4', 'ipam_fq_name': ['default-domain', 'default-project', 'default-network-ipam'], 'network_id': 'aae1c310-0eaf-4064-ac0a-cf1b06b43cdb'}], option='orch', **kwargs={'disable_gateway': False, 'dns_nameservers_list': None, 'enable_dhcp': True, 'ipam_fq_name': ['default-domain', 'default-project', 'default-network-ipam'], 'router_external': False, 'shared': False, 'sriov_enable': False, 'sriov_provider_network': None, 'sriov_vlan': None})
  184 
  185    def create_vn(self, name, subnets, option='orch', **kwargs):
  186        return self.quantum_h.create_network(name, subnets, **kwargs)
  187 
  188    def delete_vn(self, vn_obj, option='orch', **kwargs):
self = <openstack.OpenstackOrchestrator object>
self.quantum_h = <quantum_test.QuantumHelper object>
self.quantum_h.create_network = <bound method QuantumHelper.create_network of <quantum_test.QuantumHelper object>>
name = 'ctest-left_vn-14165758'
subnets = [{'cidr': '191.96.77.64/26', 'enable_dhcp': True, 'ip_version': '4', 'ipam_fq_name': ['default-domain', 'default-project', 'default-network-ipam'], 'network_id': 'aae1c310-0eaf-4064-ac0a-cf1b06b43cdb'}]
kwargs = {'disable_gateway': False, 'dns_nameservers_list': None, 'enable_dhcp': True, 'ipam_fq_name': ['default-domain', 'default-project', 'default-network-ipam'], 'router_external': False, 'shared': False, 'sriov_enable': False, 'sriov_provider_network': None, 'sriov_vlan': None}

 /contrail-test/fixtures/quantum_test.py in create_network(self=<quantum_test.QuantumHelper object>, vn_name='ctest-left_vn-14165758', vn_subnets=[{'cidr': '191.96.77.64/26', 'enable_dhcp': True, 'ip_version': '4', 'ipam_fq_name': ['default-domain', 'default-project', 'default-network-ipam'], 'network_id': 'aae1c310-0eaf-4064-ac0a-cf1b06b43cdb'}], ipam_fq_name=['default-domain', 'default-project', 'default-network-ipam'], shared=False, router_external=False, enable_dhcp=True, sriov_enable=False, sriov_vlan=None, sriov_provider_network=None, dns_nameservers_list=None, disable_gateway=False)
  107                 for subnet in vn_subnets:
  108                     net_rsp = self.create_subnet(
  109                         subnet, net_id, ipam_fq_name, enable_dhcp, disable_gateway,dns_nameservers_list)
  110             # end for
  111             return self.obj.show_network(network=net_id)
subnet = {'cidr': '191.96.77.64/26', 'enable_dhcp': True, 'ip_version': '4', 'ipam_fq_name': ['default-domain', 'default-project', 'default-network-ipam'], 'network_id': 'aae1c310-0eaf-4064-ac0a-cf1b06b43cdb'}
net_id = 'aae1c310-0eaf-4064-ac0a-cf1b06b43cdb'
ipam_fq_name = ['default-domain', 'default-project', 'default-network-ipam']
enable_dhcp = True
disable_gateway = False
dns_nameservers_list = None

 /contrail-test/fixtures/quantum_test.py in create_subnet(self=<quantum_test.QuantumHelper object>, subnet={'cidr': '191.96.77.64/26', 'enable_dhcp': True, 'ip_version': '4', 'ipam_fq_name': ['default-domain', 'default-project', 'default-network-ipam'], 'network_id': 'aae1c310-0eaf-4064-ac0a-cf1b06b43cdb'}, net_id='aae1c310-0eaf-4064-ac0a-cf1b06b43cdb', ipam_fq_name=['default-domain', 'default-project', 'default-network-ipam'], enable_dhcp=True, disable_gateway=False, dns_nameservers_list=None)
  127            subnet_req['gateway_ip'] = None
  128         try:
  129             subnet_rsp = self.obj.create_subnet({'subnet': subnet_req})
  130             self.logger.debug(
  131                 'Response for create_subnet : ' +
subnet_rsp undefined
self = <quantum_test.QuantumHelper object>
self.obj = <neutronclient.v2_0.client.Client object>
self.obj.create_subnet = <bound method Client.create_subnet of <neutronclient.v2_0.client.Client object>>
subnet_req = {'cidr': '191.96.77.64/26', 'enable_dhcp': True, 'ip_version': '4', 'ipam_fq_name': ['default-domain', 'default-project', 'default-network-ipam'], 'network_id': 'aae1c310-0eaf-4064-ac0a-cf1b06b43cdb'}

 /usr/local/lib/python3.6/site-packages/neutronclient/v2_0/client.py in create_subnet(self=<neutronclient.v2_0.client.Client object>, body={'subnet': {'cidr': '191.96.77.64/26', 'enable_dhcp': True, 'ip_version': '4', 'ipam_fq_name': ['default-domain', 'default-project', 'default-network-ipam'], 'network_id': 'aae1c310-0eaf-4064-ac0a-cf1b06b43cdb'}})
  846     def create_subnet(self, body=None):
  847         """Creates a new subnet."""
  848         return self.post(self.subnets_path, body=body)
  849 
  850     def update_subnet(self, subnet, body=None, revision_number=None):
self = <neutronclient.v2_0.client.Client object>
self.post = <bound method ClientBase.post of <neutronclient.v2_0.client.Client object>>
self.subnets_path = '/subnets'
body = {'subnet': {'cidr': '191.96.77.64/26', 'enable_dhcp': True, 'ip_version': '4', 'ipam_fq_name': ['default-domain', 'default-project', 'default-network-ipam'], 'network_id': 'aae1c310-0eaf-4064-ac0a-cf1b06b43cdb'}}

 /usr/local/lib/python3.6/site-packages/neutronclient/v2_0/client.py in post(self=<neutronclient.v2_0.client.Client object>, action='/subnets', body={'subnet': {'cidr': '191.96.77.64/26', 'enable_dhcp': True, 'ip_version': '4', 'ipam_fq_name': ['default-domain', 'default-project', 'default-network-ipam'], 'network_id': 'aae1c310-0eaf-4064-ac0a-cf1b06b43cdb'}}, headers=None, params=None)
  357         # Do not retry POST requests to avoid the orphan objects problem.
  358         return self.do_request("POST", action, body=body,
  359                                headers=headers, params=params)
  360 
  361     def put(self, action, body=None, headers=None, params=None):
headers = None
params = None

 /usr/local/lib/python3.6/site-packages/neutronclient/v2_0/client.py in do_request(self=<neutronclient.v2_0.client.Client object>, method='POST', action='/v2.0/subnets', body='{"subnet": {"cidr": "191.96.77.64/26", "network_...in", "default-project", "default-network-ipam"]}}', headers=None, params=None)
  280 
  281         resp, replybody = self.httpclient.do_request(action, method, body=body,
  282                                                      headers=headers)
  283 
  284         status_code = resp.status_code
headers = None

 /usr/local/lib/python3.6/site-packages/neutronclient/client.py in do_request(self=<neutronclient.client.SessionClient object>, url='/v2.0/subnets', method='POST', **kwargs={'authenticated': True, 'body': '{"subnet": {"cidr": "191.96.77.64/26", "network_...in", "default-project", "default-network-ipam"]}}', 'headers': None})
  338         kwargs.setdefault('authenticated', True)
  339         self._check_uri_length(url)
  340         return self.request(url, method, **kwargs)
  341 
  342     @property
self = <neutronclient.client.SessionClient object>
self.request = <bound method SessionClient.request of <neutronclient.client.SessionClient object>>
url = '/v2.0/subnets'
method = 'POST'
kwargs = {'authenticated': True, 'body': '{"subnet": {"cidr": "191.96.77.64/26", "network_...in", "default-project", "default-network-ipam"]}}', 'headers': None}

 /usr/local/lib/python3.6/site-packages/neutronclient/client.py in request(self=<neutronclient.client.SessionClient object>, *args=('/v2.0/subnets', 'POST'), **kwargs={'authenticated': True, 'data': '{"subnet": {"cidr": "191.96.77.64/26", "network_...in", "default-project", "default-network-ipam"]}}', 'headers': {'Accept': 'application/json', 'Content-Type': 'application/json', 'User-Agent': 'python-neutronclient', 'X-Auth-Token': '4d8c98bde9b44455b7f4068f9e05fb68'}, 'raise_exc': False})
  326 
  327         kwargs['headers'] = headers
  328         resp = super(SessionClient, self).request(*args, **kwargs)
  329         return resp, resp.text
  330 
resp undefined
builtinsuper = <class 'super'>
global SessionClient = <class 'neutronclient.client.SessionClient'>
self = <neutronclient.client.SessionClient object>
).request = <bound method SessionClient.request of <neutronclient.client.SessionClient object>>
args = ('/v2.0/subnets', 'POST')
kwargs = {'authenticated': True, 'data': '{"subnet": {"cidr": "191.96.77.64/26", "network_...in", "default-project", "default-network-ipam"]}}', 'headers': {'Accept': 'application/json', 'Content-Type': 'application/json', 'User-Agent': 'python-neutronclient', 'X-Auth-Token': '4d8c98bde9b44455b7f4068f9e05fb68'}, 'raise_exc': False}

 /usr/local/lib/python3.6/site-packages/keystoneauth1/adapter.py in request(self=<neutronclient.client.SessionClient object>, url='/v2.0/subnets', method='POST', **kwargs={'authenticated': True, 'data': '{"subnet": {"cidr": "191.96.77.64/26", "network_...in", "default-project", "default-network-ipam"]}}', 'endpoint_filter': {'interface': 'public', 'region_name': 'RegionOne', 'service_type': 'network'}, 'headers': {'Accept': 'application/json', 'Content-Type': 'application/json', 'User-Agent': 'python-neutronclient', 'X-Auth-Token': '4d8c98bde9b44455b7f4068f9e05fb68'}, 'raise_exc': False, 'rate_semaphore': <keystoneauth1._fair_semaphore.FairSemaphore object>, 'user_agent': 'python-neutronclient'})
  246             kwargs.setdefault('raise_exc', self.raise_exc)
  247 
  248         return self.session.request(url, method, **kwargs)
  249 
  250     def get_token(self, auth=None):
self = <neutronclient.client.SessionClient object>
self.session = <keystoneauth1.session.Session object>
self.session.request = <bound method Session.request of <keystoneauth1.session.Session object>>
url = '/v2.0/subnets'
method = 'POST'
kwargs = {'authenticated': True, 'data': '{"subnet": {"cidr": "191.96.77.64/26", "network_...in", "default-project", "default-network-ipam"]}}', 'endpoint_filter': {'interface': 'public', 'region_name': 'RegionOne', 'service_type': 'network'}, 'headers': {'Accept': 'application/json', 'Content-Type': 'application/json', 'User-Agent': 'python-neutronclient', 'X-Auth-Token': '4d8c98bde9b44455b7f4068f9e05fb68'}, 'raise_exc': False, 'rate_semaphore': <keystoneauth1._fair_semaphore.FairSemaphore object>, 'user_agent': 'python-neutronclient'}

 /usr/local/lib/python3.6/site-packages/keystoneauth1/session.py in request(self=<keystoneauth1.session.Session object>, url='http://192.168.7.31:9696/v2.0/subnets', method='POST', json=None, original_ip=None, user_agent='python-neutronclient', redirect=30, authenticated=True, endpoint_filter={'interface': 'public', 'region_name': 'RegionOne', 'service_type': 'network'}, auth=None, requests_auth=None, raise_exc=False, allow_reauth=True, log=True, endpoint_override=None, connect_retries=0, logger=<Logger keystoneauth.session (WARNING)>, allow=None, client_name=None, client_version=None, microversion=None, microversion_service_type=None, status_code_retries=0, retriable_status_codes=[503], rate_semaphore=<keystoneauth1._fair_semaphore.FairSemaphore object>, global_request_id=None, connect_retry_delay=None, status_code_retry_delay=None, **kwargs={'allow_redirects': False, 'cert': (None, None), 'data': '{"subnet": {"cidr": "191.96.77.64/26", "network_...in", "default-project", "default-network-ipam"]}}', 'headers': {'Accept': 'application/json', 'Content-Type': 'application/json', 'User-Agent': 'python-neutronclient', 'X-Auth-Token': '4d8c98bde9b44455b7f4068f9e05fb68'}, 'verify': False})
  911                 kwargs.update(connection_params)
  912 
  913         resp = send(**kwargs)
  914 
  915         # log callee and caller request-id for each api call
resp undefined
send = functools.partial(<bound method Session._send_re...auth1.session._Retries object at 0x7fdfb15f9b00>)
kwargs = {'allow_redirects': False, 'cert': (None, None), 'data': '{"subnet": {"cidr": "191.96.77.64/26", "network_...in", "default-project", "default-network-ipam"]}}', 'headers': {'Accept': 'application/json', 'Content-Type': 'application/json', 'User-Agent': 'python-neutronclient', 'X-Auth-Token': '4d8c98bde9b44455b7f4068f9e05fb68'}, 'verify': False}

 /usr/local/lib/python3.6/site-packages/keystoneauth1/session.py in _send_request(self=<keystoneauth1.session.Session object>, url='http://192.168.7.31:9696/v2.0/subnets', method='POST', redirect=30, log=True, logger=<Logger keystoneauth.session (WARNING)>, split_loggers=None, connect_retries=0, status_code_retries=0, retriable_status_codes=[503], rate_semaphore=<keystoneauth1._fair_semaphore.FairSemaphore object>, connect_retry_delays=<keystoneauth1.session._Retries object>, status_code_retry_delays=<keystoneauth1.session._Retries object>, **kwargs={'allow_redirects': False, 'cert': (None, None), 'data': '{"subnet": {"cidr": "191.96.77.64/26", "network_...in", "default-project", "default-network-ipam"]}}', 'headers': {'Accept': 'application/json', 'Content-Type': 'application/json', 'User-Agent': 'python-neutronclient', 'X-Auth-Token': '4d8c98bde9b44455b7f4068f9e05fb68'}, 'verify': False})
 1018                 # and firewall blocking.
 1019                 msg = 'Unable to establish connection to %s: %s' % (url, e)
 1020                 raise exceptions.ConnectFailure(msg)
 1021             except requests.exceptions.RequestException as e:
 1022                 msg = 'Unexpected exception for %(url)s: %(error)s' % {
global exceptions = <module 'keystoneauth1.exceptions' from '/usr/lo...e-packages/keystoneauth1/exceptions/__init__.py'>
exceptions.ConnectFailure = <class 'keystoneauth1.exceptions.connection.ConnectFailure'>
msg = "Unable to establish connection to http://192.168...Remote end closed connection without response',))"
ConnectFailure: Unable to establish connection to http://192.168.7.31:9696/v2.0/subnets: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
    __cause__ = None
    __class__ = <class 'keystoneauth1.exceptions.connection.ConnectFailure'>
    __context__ = ConnectionError(ProtocolError('Connection aborte...mote end closed connection without response',)),)
    __delattr__ = <method-wrapper '__delattr__' of ConnectFailure object>
    __dict__ = {'message': "Unable to establish connection to http://192.168...Remote end closed connection without response',))"}
    __dir__ = <built-in method __dir__ of ConnectFailure object>
    __doc__ = None
    __eq__ = <method-wrapper '__eq__' of ConnectFailure object>
    __format__ = <built-in method __format__ of ConnectFailure object>
    __ge__ = <method-wrapper '__ge__' of ConnectFailure object>
    __getattribute__ = <method-wrapper '__getattribute__' of ConnectFailure object>
    __gt__ = <method-wrapper '__gt__' of ConnectFailure object>
    __hash__ = <method-wrapper '__hash__' of ConnectFailure object>
    __init__ = <bound method ClientException.__init__ of Connec...te end closed connection without response',))",)>
    __init_subclass__ = <built-in method __init_subclass__ of type object>
    __le__ = <method-wrapper '__le__' of ConnectFailure object>
    __lt__ = <method-wrapper '__lt__' of ConnectFailure object>
    __module__ = 'keystoneauth1.exceptions.connection'
    __ne__ = <method-wrapper '__ne__' of ConnectFailure object>
    __new__ = <built-in method __new__ of type object>
    __reduce__ = <built-in method __reduce__ of ConnectFailure object>
    __reduce_ex__ = <built-in method __reduce_ex__ of ConnectFailure object>
    __repr__ = <method-wrapper '__repr__' of ConnectFailure object>
    __setattr__ = <method-wrapper '__setattr__' of ConnectFailure object>
    __setstate__ = <built-in method __setstate__ of ConnectFailure object>
    __sizeof__ = <built-in method __sizeof__ of ConnectFailure object>
    __str__ = <method-wrapper '__str__' of ConnectFailure object>
    __subclasshook__ = <built-in method __subclasshook__ of type object>
    __suppress_context__ = False
    __traceback__ = <traceback object>
    __weakref__ = None
    args = ("Unable to establish connection to http://192.168...Remote end closed connection without response',))",)
    message = "Unable to establish connection to http://192.168...Remote end closed connection without response',))"
    with_traceback = <built-in method with_traceback of ConnectFailure object>

The above is a description of an error in a Python program.  Here is
the original traceback:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib64/python3.6/http/client.py", line 1346, in getresponse
    response.begin()
  File "/usr/lib64/python3.6/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python3.6/http/client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/retry.py", line 400, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.6/site-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib64/python3.6/http/client.py", line 1346, in getresponse
    response.begin()
  File "/usr/lib64/python3.6/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python3.6/http/client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/keystoneauth1/session.py", line 1004, in _send_request
    resp = self.session.request(method, url, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/contrail-test/tcutils/wrappers.py", line 82, in wrapper
    result = function(self, *args, **kwargs)
  File "/contrail-test/scripts/svc_firewall/test_svc_fw.py", line 33, in test_svc_in_network_datapath
    create_svms=True)
  File "/contrail-test/common/servicechain/verify.py", line 328, in verify_svc_chain
    ret_dict = svc_chain_info or self.config_svc_chain(*args, **kwargs)
  File "/contrail-test/common/servicechain/config.py", line 484, in config_svc_chain
    **kwargs)
  File "/contrail-test/common/servicechain/config.py", line 375, in _get_vn_for_config
    vn_fixture = vn_fixture or self.config_vn(vn_name, vn_subnets, **kwargs)
  File "/contrail-test/common/servicechain/config.py", line 156, in config_vn
    vn_name=vn_name, inputs=self.inputs, subnets=vn_net, **kwargs))
  File "/usr/local/lib/python3.6/site-packages/testtools/testcase.py", line 756, in useFixture
    reraise(*exc_info)
  File "/usr/local/lib/python3.6/site-packages/testtools/_compat3x.py", line 16, in reraise
    raise exc_obj.with_traceback(exc_tb)
  File "/usr/local/lib/python3.6/site-packages/testtools/testcase.py", line 731, in useFixture
    fixture.setUp()
  File "/contrail-test/fixtures/vn_test.py", line 444, in setUp
    self.create()
  File "/contrail-test/fixtures/vn_test.py", line 457, in create
    self._create_vn_orch()
  File "/contrail-test/fixtures/vn_test.py", line 315, in _create_vn_orch
    dns_nameservers_list=self.dns_nameservers_list)
  File "/contrail-test/fixtures/openstack.py", line 186, in create_vn
    return self.quantum_h.create_network(name, subnets, **kwargs)
  File "/contrail-test/fixtures/quantum_test.py", line 109, in create_network
    subnet, net_id, ipam_fq_name, enable_dhcp, disable_gateway,dns_nameservers_list)
  File "/contrail-test/fixtures/quantum_test.py", line 129, in create_subnet
    subnet_rsp = self.obj.create_subnet({'subnet': subnet_req})
  File "/usr/local/lib/python3.6/site-packages/neutronclient/v2_0/client.py", line 848, in create_subnet
    return self.post(self.subnets_path, body=body)
  File "/usr/local/lib/python3.6/site-packages/neutronclient/v2_0/client.py", line 359, in post
    headers=headers, params=params)
  File "/usr/local/lib/python3.6/site-packages/neutronclient/v2_0/client.py", line 282, in do_request
    headers=headers)
  File "/usr/local/lib/python3.6/site-packages/neutronclient/client.py", line 340, in do_request
    return self.request(url, method, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/neutronclient/client.py", line 328, in request
    resp = super(SessionClient, self).request(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/keystoneauth1/adapter.py", line 248, in request
    return self.session.request(url, method, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/keystoneauth1/session.py", line 913, in request
    resp = send(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/keystoneauth1/session.py", line 1020, in _send_request
    raise exceptions.ConnectFailure(msg)
keystoneauth1.exceptions.connection.ConnectFailure: Unable to establish connection to http://192.168.7.31:9696/v2.0/subnets: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))



2021-02-22 05:03:22,519 - DEBUG - No XMPP flaps were noticed during the test
2021-02-22 05:03:22,519 - INFO - 
<div id=test_svc_in_network_datapath>2021-02-22 05:03:22,519 - INFO - END TEST : test_svc_in_network_datapath : FAILED[0:01:39]
</div>2021-02-22 05:03:22,519 - INFO - --------------------------------------------------------------------------------
2021-02-22 05:03:22,770 - WARNING - Project ctest-TestSvcRegr-09180439 still has VNs [{'to': ['admin_domain', 'ctest-TestSvcRegr-09180439', 'ctest-left_vn-14165758'], 'href': 'https://192.168.7.34:8082/virtual-network/aae1c310-0eaf-4064-ac0a-cf1b06b43cdb', 'uuid': 'aae1c310-0eaf-4064-ac0a-cf1b06b43cdb'}] before deletion
2021-02-22 05:03:24,898 - WARNING - Project ctest-TestSvcRegr-09180439 still has VNs [{'to': ['admin_domain', 'ctest-TestSvcRegr-09180439', 'ctest-left_vn-14165758'], 'href': 'https://192.168.7.34:8082/virtual-network/aae1c310-0eaf-4064-ac0a-cf1b06b43cdb', 'uuid': 'aae1c310-0eaf-4064-ac0a-cf1b06b43cdb'}] before deletion
2021-02-22 05:03:27,025 - WARNING - Project ctest-TestSvcRegr-09180439 still has VNs [{'to': ['admin_domain', 'ctest-TestSvcRegr-09180439', 'ctest-left_vn-14165758'], 'href': 'https://192.168.7.34:8082/virtual-network/aae1c310-0eaf-4064-ac0a-cf1b06b43cdb', 'uuid': 'aae1c310-0eaf-4064-ac0a-cf1b06b43cdb'}] before deletion
2021-02-22 05:03:29,149 - WARNING - Project ctest-TestSvcRegr-09180439 still has VNs [{'to': ['admin_domain', 'ctest-TestSvcRegr-09180439', 'ctest-left_vn-14165758'], 'href': 'https://192.168.7.34:8082/virtual-network/aae1c310-0eaf-4064-ac0a-cf1b06b43cdb', 'uuid': 'aae1c310-0eaf-4064-ac0a-cf1b06b43cdb'}] before deletion
2021-02-22 05:03:31,266 - WARNING - Project ctest-TestSvcRegr-09180439 still has VNs [{'to': ['admin_domain', 'ctest-TestSvcRegr-09180439', 'ctest-left_vn-14165758'], 'href': 'https://192.168.7.34:8082/virtual-network/aae1c310-0eaf-4064-ac0a-cf1b06b43cdb', 'uuid': 'aae1c310-0eaf-4064-ac0a-cf1b06b43cdb'}] before deletion
2021-02-22 05:03:33,383 - WARNING - Project ctest-TestSvcRegr-09180439 still has VNs [{'to': ['admin_domain', 'ctest-TestSvcRegr-09180439', 'ctest-left_vn-14165758'], 'href': 'https://192.168.7.34:8082/virtual-network/aae1c310-0eaf-4064-ac0a-cf1b06b43cdb', 'uuid': 'aae1c310-0eaf-4064-ac0a-cf1b06b43cdb'}] before deletion
2021-02-22 05:03:35,486 - WARNING - Project ctest-TestSvcRegr-09180439 still has VNs [{'to': ['admin_domain', 'ctest-TestSvcRegr-09180439', 'ctest-left_vn-14165758'], 'href': 'https://192.168.7.34:8082/virtual-network/aae1c310-0eaf-4064-ac0a-cf1b06b43cdb', 'uuid': 'aae1c310-0eaf-4064-ac0a-cf1b06b43cdb'}] before deletion
2021-02-22 05:03:37,590 - WARNING - Project ctest-TestSvcRegr-09180439 still has VNs [{'to': ['admin_domain', 'ctest-TestSvcRegr-09180439', 'ctest-left_vn-14165758'], 'href': 'https://192.168.7.34:8082/virtual-network/aae1c310-0eaf-4064-ac0a-cf1b06b43cdb', 'uuid': 'aae1c310-0eaf-4064-ac0a-cf1b06b43cdb'}] before deletion
2021-02-22 05:03:39,711 - WARNING - Project ctest-TestSvcRegr-09180439 still has VNs [{'to': ['admin_domain', 'ctest-TestSvcRegr-09180439', 'ctest-left_vn-14165758'], 'href': 'https://192.168.7.34:8082/virtual-network/aae1c310-0eaf-4064-ac0a-cf1b06b43cdb', 'uuid': 'aae1c310-0eaf-4064-ac0a-cf1b06b43cdb'}] before deletion
2021-02-22 05:03:41,840 - WARNING - Project ctest-TestSvcRegr-09180439 still has VNs [{'to': ['admin_domain', 'ctest-TestSvcRegr-09180439', 'ctest-left_vn-14165758'], 'href': 'https://192.168.7.34:8082/virtual-network/aae1c310-0eaf-4064-ac0a-cf1b06b43cdb', 'uuid': 'aae1c310-0eaf-4064-ac0a-cf1b06b43cdb'}] before deletion
2021-02-22 05:03:43,973 - WARNING - Project ctest-TestSvcRegr-09180439 still has VNs [{'to': ['admin_domain', 'ctest-TestSvcRegr-09180439', 'ctest-left_vn-14165758'], 'href': 'https://192.168.7.34:8082/virtual-network/aae1c310-0eaf-4064-ac0a-cf1b06b43cdb', 'uuid': 'aae1c310-0eaf-4064-ac0a-cf1b06b43cdb'}] before deletion
2021-02-22 05:03:46,094 - WARNING - Project ctest-TestSvcRegr-09180439 still has VNs [{'to': ['admin_domain', 'ctest-TestSvcRegr-09180439', 'ctest-left_vn-14165758'], 'href': 'https://192.168.7.34:8082/virtual-network/aae1c310-0eaf-4064-ac0a-cf1b06b43cdb', 'uuid': 'aae1c310-0eaf-4064-ac0a-cf1b06b43cdb'}] before deletion
2021-02-22 05:03:48,215 - WARNING - Project ctest-TestSvcRegr-09180439 still has VNs [{'to': ['admin_domain', 'ctest-TestSvcRegr-09180439', 'ctest-left_vn-14165758'], 'href': 'https://192.168.7.34:8082/virtual-network/aae1c310-0eaf-4064-ac0a-cf1b06b43cdb', 'uuid': 'aae1c310-0eaf-4064-ac0a-cf1b06b43cdb'}] before deletion
2021-02-22 05:03:50,326 - WARNING - Project ctest-TestSvcRegr-09180439 still has VNs [{'to': ['admin_domain', 'ctest-TestSvcRegr-09180439', 'ctest-left_vn-14165758'], 'href': 'https://192.168.7.34:8082/virtual-network/aae1c310-0eaf-4064-ac0a-cf1b06b43cdb', 'uuid': 'aae1c310-0eaf-4064-ac0a-cf1b06b43cdb'}] before deletion
2021-02-22 05:03:52,483 - WARNING - Project ctest-TestSvcRegr-09180439 still has VNs [{'to': ['admin_domain', 'ctest-TestSvcRegr-09180439', 'ctest-left_vn-14165758'], 'href': 'https://192.168.7.34:8082/virtual-network/aae1c310-0eaf-4064-ac0a-cf1b06b43cdb', 'uuid': 'aae1c310-0eaf-4064-ac0a-cf1b06b43cdb'}] before deletion
2021-02-22 05:03:54,639 - WARNING - Project ctest-TestSvcRegr-09180439 still has VNs [{'to': ['admin_domain', 'ctest-TestSvcRegr-09180439', 'ctest-left_vn-14165758'], 'href': 'https://192.168.7.34:8082/virtual-network/aae1c310-0eaf-4064-ac0a-cf1b06b43cdb', 'uuid': 'aae1c310-0eaf-4064-ac0a-cf1b06b43cdb'}] before deletion
2021-02-22 05:03:56,795 - WARNING - Project ctest-TestSvcRegr-09180439 still has VNs [{'to': ['admin_domain', 'ctest-TestSvcRegr-09180439', 'ctest-left_vn-14165758'], 'href': 'https://192.168.7.34:8082/virtual-network/aae1c310-0eaf-4064-ac0a-cf1b06b43cdb', 'uuid': 'aae1c310-0eaf-4064-ac0a-cf1b06b43cdb'}] before deletion
2021-02-22 05:03:58,948 - WARNING - Project ctest-TestSvcRegr-09180439 still has VNs [{'to': ['admin_domain', 'ctest-TestSvcRegr-09180439', 'ctest-left_vn-14165758'], 'href': 'https://192.168.7.34:8082/virtual-network/aae1c310-0eaf-4064-ac0a-cf1b06b43cdb', 'uuid': 'aae1c310-0eaf-4064-ac0a-cf1b06b43cdb'}] before deletion
2021-02-22 05:04:01,120 - WARNING - Project ctest-TestSvcRegr-09180439 still has VNs [{'to': ['admin_domain', 'ctest-TestSvcRegr-09180439', 'ctest-left_vn-14165758'], 'href': 'https://192.168.7.34:8082/virtual-network/aae1c310-0eaf-4064-ac0a-cf1b06b43cdb', 'uuid': 'aae1c310-0eaf-4064-ac0a-cf1b06b43cdb'}] before deletion
2021-02-22 05:04:03,286 - WARNING - Project ctest-TestSvcRegr-09180439 still has VNs [{'to': ['admin_domain', 'ctest-TestSvcRegr-09180439', 'ctest-left_vn-14165758'], 'href': 'https://192.168.7.34:8082/virtual-network/aae1c310-0eaf-4064-ac0a-cf1b06b43cdb', 'uuid': 'aae1c310-0eaf-4064-ac0a-cf1b06b43cdb'}] before deletion
2021-02-22 05:04:05,436 - WARNING - Project ctest-TestSvcRegr-09180439 still has VNs [{'to': ['admin_domain', 'ctest-TestSvcRegr-09180439', 'ctest-left_vn-14165758'], 'href': 'https://192.168.7.34:8082/virtual-network/aae1c310-0eaf-4064-ac0a-cf1b06b43cdb', 'uuid': 'aae1c310-0eaf-4064-ac0a-cf1b06b43cdb'}] before deletion
2021-02-22 05:04:07,603 - WARNING - Project ctest-TestSvcRegr-09180439 still has VNs [{'to': ['admin_domain', 'ctest-TestSvcRegr-09180439', 'ctest-left_vn-14165758'], 'href': 'https://192.168.7.34:8082/virtual-network/aae1c310-0eaf-4064-ac0a-cf1b06b43cdb', 'uuid': 'aae1c310-0eaf-4064-ac0a-cf1b06b43cdb'}] before deletion
2021-02-22 05:04:09,758 - WARNING - Project ctest-TestSvcRegr-09180439 still has VNs [{'to': ['admin_domain', 'ctest-TestSvcRegr-09180439', 'ctest-left_vn-14165758'], 'href': 'https://192.168.7.34:8082/virtual-network/aae1c310-0eaf-4064-ac0a-cf1b06b43cdb', 'uuid': 'aae1c310-0eaf-4064-ac0a-cf1b06b43cdb'}] before deletion
2021-02-22 05:04:11,912 - WARNING - Project ctest-TestSvcRegr-09180439 still has VNs [{'to': ['admin_domain', 'ctest-TestSvcRegr-09180439', 'ctest-left_vn-14165758'], 'href': 'https://192.168.7.34:8082/virtual-network/aae1c310-0eaf-4064-ac0a-cf1b06b43cdb', 'uuid': 'aae1c310-0eaf-4064-ac0a-cf1b06b43cdb'}] before deletion
2021-02-22 05:04:14,063 - WARNING - Project ctest-TestSvcRegr-09180439 still has VNs [{'to': ['admin_domain', 'ctest-TestSvcRegr-09180439', 'ctest-left_vn-14165758'], 'href': 'https://192.168.7.34:8082/virtual-network/aae1c310-0eaf-4064-ac0a-cf1b06b43cdb', 'uuid': 'aae1c310-0eaf-4064-ac0a-cf1b06b43cdb'}] before deletion
2021-02-22 05:04:16,224 - WARNING - Project ctest-TestSvcRegr-09180439 still has VNs [{'to': ['admin_domain', 'ctest-TestSvcRegr-09180439', 'ctest-left_vn-14165758'], 'href': 'https://192.168.7.34:8082/virtual-network/aae1c310-0eaf-4064-ac0a-cf1b06b43cdb', 'uuid': 'aae1c310-0eaf-4064-ac0a-cf1b06b43cdb'}] before deletion
2021-02-22 05:04:18,364 - WARNING - Project ctest-TestSvcRegr-09180439 still has VNs [{'to': ['admin_domain', 'ctest-TestSvcRegr-09180439', 'ctest-left_vn-14165758'], 'href': 'https://192.168.7.34:8082/virtual-network/aae1c310-0eaf-4064-ac0a-cf1b06b43cdb', 'uuid': 'aae1c310-0eaf-4064-ac0a-cf1b06b43cdb'}] before deletion
2021-02-22 05:04:20,507 - WARNING - Project ctest-TestSvcRegr-09180439 still has VNs [{'to': ['admin_domain', 'ctest-TestSvcRegr-09180439', 'ctest-left_vn-14165758'], 'href': 'https://192.168.7.34:8082/virtual-network/aae1c310-0eaf-4064-ac0a-cf1b06b43cdb', 'uuid': 'aae1c310-0eaf-4064-ac0a-cf1b06b43cdb'}] before deletion
2021-02-22 05:04:22,658 - WARNING - Project ctest-TestSvcRegr-09180439 still has VNs [{'to': ['admin_domain', 'ctest-TestSvcRegr-09180439', 'ctest-left_vn-14165758'], 'href': 'https://192.168.7.34:8082/virtual-network/aae1c310-0eaf-4064-ac0a-cf1b06b43cdb', 'uuid': 'aae1c310-0eaf-4064-ac0a-cf1b06b43cdb'}] before deletion
2021-02-22 05:04:24,828 - WARNING - Project ctest-TestSvcRegr-09180439 still has VNs [{'to': ['admin_domain', 'ctest-TestSvcRegr-09180439', 'ctest-left_vn-14165758'], 'href': 'https://192.168.7.34:8082/virtual-network/aae1c310-0eaf-4064-ac0a-cf1b06b43cdb', 'uuid': 'aae1c310-0eaf-4064-ac0a-cf1b06b43cdb'}] before deletion
2021-02-22 05:04:27,002 - WARNING - Project ctest-TestSvcRegr-09180439 still has VNs [{'to': ['admin_domain', 'ctest-TestSvcRegr-09180439', 'ctest-left_vn-14165758'], 'href': 'https://192.168.7.34:8082/virtual-network/aae1c310-0eaf-4064-ac0a-cf1b06b43cdb', 'uuid': 'aae1c310-0eaf-4064-ac0a-cf1b06b43cdb'}] before deletion
2021-02-22 05:04:27,002 - WARNING - One or more references still present, will not delete the project ctest-TestSvcRegr-09180439
2021-02-22 05:23:27,388 - INFO - Reading existing Domain with UUID f27c063f-c6c4-434f-a616-97e72e0043e5
2021-02-22 05:23:27,426 - INFO - Using existing domain ['admin_domain'](f27c063f-c6c4-434f-a616-97e72e0043e5)
2021-02-22 05:23:27,873 - INFO - Project ctest-TestSvcRegr-67366984 not found, creating it
2021-02-22 05:23:29,123 - INFO - Created Project:ctest-TestSvcRegr-67366984, ID : 0e58f3ad-081e-4bc8-b28f-56e344a4d1bb 
2021-02-22 05:23:34,183 - INFO - ================================================================================
2021-02-22 05:23:34,183 - INFO - STARTING TEST    : test_svc_in_network_datapath
2021-02-22 05:23:35,503 - DEBUG - Nothing to compare xmpp stats {'192.168.7.19': {'192.168.27.20': '0', '192.168.27.34': '0'}, '192.168.7.9': {'192.168.27.20': '0', '192.168.27.34': '0'}} with
2021-02-22 05:23:35,503 - INFO - Initial checks done. Running the testcase now
2021-02-22 05:23:35,503 - INFO - 
2021-02-22 05:23:36,800 - DEBUG - Response for create_network : {'network': {'status': 'ACTIVE', 'router:external': False, 'subnets': [], 'fq_name': ['admin_domain', 'ctest-TestSvcRegr-67366984', 'ctest-mgmt_vn-51304077'], 'name': 'ctest-mgmt_vn-51304077', 'admin_state_up': True, 'tenant_id': '0e58f3ad081e4bc8b28f56e344a4d1bb', 'created_at': None, 'updated_at': None, 'shared': False, 'port_security_enabled': True, 'project_id': '0e58f3ad081e4bc8b28f56e344a4d1bb', 'id': '2c00d40d-5a2f-4508-9951-5a0ac8d5b41d', 'description': ''}}
2021-02-22 05:25:08,137 - ERROR - ConnectFailure
Python 3.6.8: /usr/bin/python3
Mon Feb 22 05:25:06 2021

A problem occurred in a Python script.  Here is the sequence of
function calls leading up to the error, in the order they occurred.

 /contrail-test/tcutils/wrappers.py in wrapper(self=<scripts.svc_firewall.test_svc_fw.TestSvcRegr.te...rk_datapath[ci_sanity,vcenter] id=0x7f7165904400>, *args=(), **kwargs={})
   80             log.info('Initial checks done. Running the testcase now')
   81             log.info('')
   82             result = function(self, *args, **kwargs)
   83             if self.inputs.upgrade:
   84                 pid = os.getpid()
result = None
function = <function TestSvcRegr.test_svc_in_network_datapath>
self = <scripts.svc_firewall.test_svc_fw.TestSvcRegr.te...rk_datapath[ci_sanity,vcenter] id=0x7f7165904400>
args = ()
kwargs = {}

 /contrail-test/scripts/svc_firewall/test_svc_fw.py in test_svc_in_network_datapath(self=<scripts.svc_firewall.test_svc_fw.TestSvcRegr.te...rk_datapath[ci_sanity,vcenter] id=0x7f7165904400>)
   31     def test_svc_in_network_datapath(self):
   32         return self.verify_svc_chain(svc_img_name='cirros_in_net', service_mode='in-network',
   33                                      create_svms=True)
   34 
   35 
create_svms undefined

 /contrail-test/common/servicechain/verify.py in verify_svc_chain(self=<scripts.svc_firewall.test_svc_fw.TestSvcRegr.te...rk_datapath[ci_sanity,vcenter] id=0x7f7165904400>, *args=(), **kwargs={'create_svms': True, 'service_mode': 'in-network', 'svc_img_name': 'cirros_in_net'})
  326     def verify_svc_chain(self, *args, **kwargs):
  327         svc_chain_info = kwargs.get('svc_chain_info')
  328         ret_dict = svc_chain_info or self.config_svc_chain(*args, **kwargs)
  329         proto = kwargs.get('proto', 'any')
  330         left_vn_fq_name = ret_dict.get('left_vn_fixture').vn_fq_name
ret_dict undefined
svc_chain_info = None
self = <scripts.svc_firewall.test_svc_fw.TestSvcRegr.te...rk_datapath[ci_sanity,vcenter] id=0x7f7165904400>
self.config_svc_chain = <bound method ConfigSvcChain.config_svc_chain of...k_datapath[ci_sanity,vcenter] id=0x7f7165904400>>
args = ()
kwargs = {'create_svms': True, 'service_mode': 'in-network', 'svc_img_name': 'cirros_in_net'}

 /contrail-test/common/servicechain/config.py in config_svc_chain(self=<scripts.svc_firewall.test_svc_fw.TestSvcRegr.te...rk_datapath[ci_sanity,vcenter] id=0x7f7165904400>, service_mode='in-network', service_type='firewall', max_inst=1, proto='any', svc_chain_type='parallel', src_ports=[0, 65535], dst_ports=[0, 65535], svc_img_name='cirros_in_net', st_version=2, mgmt_vn_name=None, mgmt_vn_subnets=[], mgmt_vn_fixture=None, left_vn_name=None, left_vn_subnets=[], left_vn_fixture=None, right_vn_name=None, right_vn_subnets=[], right_vn_fixture=None, left_lr_child_vn_fixture=None, right_lr_child_vn_fixture=None, left_vm_name=None, left_vm_fixture=None, right_vm_name=None, right_vm_fixture=None, image_name='ubuntu-traffic', policy_fixture=None, st_fixture=None, si_fixture=None, port_tuples_props=None, static_route=None, svm_fixtures=[], create_svms=True, evpn=False, modify_rules=False, policy_action='pass', hosts=[], **kwargs={})
  472                                                     mgmt_vn_fixture,
  473                                                     'mgmt_vn',
  474                                                     **kwargs)
  475 
  476         # Left
kwargs = {}

 /contrail-test/common/servicechain/config.py in _get_vn_for_config(self=<scripts.svc_firewall.test_svc_fw.TestSvcRegr.te...rk_datapath[ci_sanity,vcenter] id=0x7f7165904400>, vn_name='ctest-mgmt_vn-51304077', vn_subnets=['35.129.130.0/26'], vn_fixture=None, vn_name_prefix='mgmt_vn', **kwargs={})
  373             vn_subnets = vn_subnets or \
  374                                   [get_random_cidr(af=self.inputs.get_af())]
  375             vn_fixture = vn_fixture or self.config_vn(vn_name, vn_subnets, **kwargs)
  376         vn_fq_name = vn_fixture.vn_fq_name
  377         return (vn_name, vn_subnets, vn_fixture, vn_fq_name)
vn_fixture = None
self = <scripts.svc_firewall.test_svc_fw.TestSvcRegr.te...rk_datapath[ci_sanity,vcenter] id=0x7f7165904400>
self.config_vn = <bound method ConfigSvcChain.config_vn of <scrip...k_datapath[ci_sanity,vcenter] id=0x7f7165904400>>
vn_name = 'ctest-mgmt_vn-51304077'
vn_subnets = ['35.129.130.0/26']
kwargs = {}

 /contrail-test/common/servicechain/config.py in config_vn(self=<scripts.svc_firewall.test_svc_fw.TestSvcRegr.te...rk_datapath[ci_sanity,vcenter] id=0x7f7165904400>, vn_name='ctest-mgmt_vn-51304077', vn_net=['35.129.130.0/26'], **kwargs={})
  154         vn_fixture = self.useFixture(VNFixture(
  155             project_name=self.inputs.project_name, connections=self.connections,
  156             vn_name=vn_name, inputs=self.inputs, subnets=vn_net, **kwargs))
  157         assert vn_fixture.verify_on_setup()
  158         return vn_fixture
vn_name = 'ctest-mgmt_vn-51304077'
inputs undefined
self = <scripts.svc_firewall.test_svc_fw.TestSvcRegr.te...rk_datapath[ci_sanity,vcenter] id=0x7f7165904400>
self.inputs = <common.contrail_test_init.ContrailTestInit object>
subnets undefined
vn_net = ['35.129.130.0/26']
kwargs = {}

 /usr/local/lib/python3.6/site-packages/testtools/testcase.py in useFixture(self=<scripts.svc_firewall.test_svc_fw.TestSvcRegr.te...rk_datapath[ci_sanity,vcenter] id=0x7f7165904400>, fixture=<vn_test.VNFixture object>)
  754                 # Gather_details worked, so raise the exception setUp
  755                 # encountered.
  756                 reraise(*exc_info)
  757         else:
  758             self.addCleanup(fixture.cleanUp)
global reraise = <function reraise>
exc_info = (<class 'keystoneauth1.exceptions.connection.ConnectFailure'>, ConnectFailure("Unable to establish connection t...ote end closed connection without response',))",), <traceback object>)

 /usr/local/lib/python3.6/site-packages/testtools/_compat3x.py in reraise(exc_class=<class 'keystoneauth1.exceptions.connection.ConnectFailure'>, exc_obj=ConnectFailure("Unable to establish connection t...ote end closed connection without response',))",), exc_tb=<traceback object>, _marker=<object object>)
   13 
   14 def reraise(exc_class, exc_obj, exc_tb, _marker=object()):
   15     """Re-raise an exception received from sys.exc_info() or similar."""
   16     raise exc_obj.with_traceback(exc_tb)
   17 
exc_obj = ConnectFailure("Unable to establish connection t...ote end closed connection without response',))",)
exc_obj.with_traceback = <built-in method with_traceback of ConnectFailure object>
exc_tb = <traceback object>

 /usr/local/lib/python3.6/site-packages/testtools/testcase.py in useFixture(self=<scripts.svc_firewall.test_svc_fw.TestSvcRegr.te...rk_datapath[ci_sanity,vcenter] id=0x7f7165904400>, fixture=<vn_test.VNFixture object>)
  729         """
  730         try:
  731             fixture.setUp()
  732         except MultipleExceptions as e:
  733             if (fixtures is not None and
fixture = <vn_test.VNFixture object>
fixture.setUp = <bound method VNFixture.setUp of <vn_test.VNFixture object>>

 /contrail-test/fixtures/vn_test.py in setUp(self=<vn_test.VNFixture object>)
  442     def setUp(self):
  443         super(VNFixture, self).setUp()
  444         self.create()
  445 
  446     def create(self):
self = <vn_test.VNFixture object>
self.create = <bound method VNFixture.create of <vn_test.VNFixture object>>

 /contrail-test/fixtures/vn_test.py in create(self=<vn_test.VNFixture object>)
  455             self._create_vn_api(self.vn_name, self.project_obj)
  456         else:
  457             self._create_vn_orch()
  458         if not self.obj:
  459              self.logger.debug('VN %s not present' % (self.vn_name))
self = <vn_test.VNFixture object>
self._create_vn_orch = <bound method VNFixture._create_vn_orch of <vn_test.VNFixture object>>

 /contrail-test/fixtures/vn_test.py in _create_vn_orch(self=<vn_test.VNFixture object>)
  313                                                 sriov_provider_network=self.sriov_provider_network,
  314                                                 disable_gateway=self.disable_gateway,
  315                                                 dns_nameservers_list=self.dns_nameservers_list)
  316                 if self.obj:
  317                     self.logger.info('Created VN %s' %(self.vn_name))
dns_nameservers_list undefined
self = <vn_test.VNFixture object>
self.dns_nameservers_list = None

 /contrail-test/fixtures/openstack.py in create_vn(self=<openstack.OpenstackOrchestrator object>, name='ctest-mgmt_vn-51304077', subnets=[{'cidr': '35.129.130.0/26', 'enable_dhcp': True, 'ip_version': '4', 'ipam_fq_name': ['default-domain', 'default-project', 'default-network-ipam'], 'network_id': '2c00d40d-5a2f-4508-9951-5a0ac8d5b41d'}], option='orch', **kwargs={'disable_gateway': False, 'dns_nameservers_list': None, 'enable_dhcp': True, 'ipam_fq_name': ['default-domain', 'default-project', 'default-network-ipam'], 'router_external': False, 'shared': False, 'sriov_enable': False, 'sriov_provider_network': None, 'sriov_vlan': None})
  184 
  185    def create_vn(self, name, subnets, option='orch', **kwargs):
  186        return self.quantum_h.create_network(name, subnets, **kwargs)
  187 
  188    def delete_vn(self, vn_obj, option='orch', **kwargs):
self = <openstack.OpenstackOrchestrator object>
self.quantum_h = <quantum_test.QuantumHelper object>
self.quantum_h.create_network = <bound method QuantumHelper.create_network of <quantum_test.QuantumHelper object>>
name = 'ctest-mgmt_vn-51304077'
subnets = [{'cidr': '35.129.130.0/26', 'enable_dhcp': True, 'ip_version': '4', 'ipam_fq_name': ['default-domain', 'default-project', 'default-network-ipam'], 'network_id': '2c00d40d-5a2f-4508-9951-5a0ac8d5b41d'}]
kwargs = {'disable_gateway': False, 'dns_nameservers_list': None, 'enable_dhcp': True, 'ipam_fq_name': ['default-domain', 'default-project', 'default-network-ipam'], 'router_external': False, 'shared': False, 'sriov_enable': False, 'sriov_provider_network': None, 'sriov_vlan': None}

 /contrail-test/fixtures/quantum_test.py in create_network(self=<quantum_test.QuantumHelper object>, vn_name='ctest-mgmt_vn-51304077', vn_subnets=[{'cidr': '35.129.130.0/26', 'enable_dhcp': True, 'ip_version': '4', 'ipam_fq_name': ['default-domain', 'default-project', 'default-network-ipam'], 'network_id': '2c00d40d-5a2f-4508-9951-5a0ac8d5b41d'}], ipam_fq_name=['default-domain', 'default-project', 'default-network-ipam'], shared=False, router_external=False, enable_dhcp=True, sriov_enable=False, sriov_vlan=None, sriov_provider_network=None, dns_nameservers_list=None, disable_gateway=False)
  107                 for subnet in vn_subnets:
  108                     net_rsp = self.create_subnet(
  109                         subnet, net_id, ipam_fq_name, enable_dhcp, disable_gateway,dns_nameservers_list)
  110             # end for
  111             return self.obj.show_network(network=net_id)
subnet = {'cidr': '35.129.130.0/26', 'enable_dhcp': True, 'ip_version': '4', 'ipam_fq_name': ['default-domain', 'default-project', 'default-network-ipam'], 'network_id': '2c00d40d-5a2f-4508-9951-5a0ac8d5b41d'}
net_id = '2c00d40d-5a2f-4508-9951-5a0ac8d5b41d'
ipam_fq_name = ['default-domain', 'default-project', 'default-network-ipam']
enable_dhcp = True
disable_gateway = False
dns_nameservers_list = None

 /contrail-test/fixtures/quantum_test.py in create_subnet(self=<quantum_test.QuantumHelper object>, subnet={'cidr': '35.129.130.0/26', 'enable_dhcp': True, 'ip_version': '4', 'ipam_fq_name': ['default-domain', 'default-project', 'default-network-ipam'], 'network_id': '2c00d40d-5a2f-4508-9951-5a0ac8d5b41d'}, net_id='2c00d40d-5a2f-4508-9951-5a0ac8d5b41d', ipam_fq_name=['default-domain', 'default-project', 'default-network-ipam'], enable_dhcp=True, disable_gateway=False, dns_nameservers_list=None)
  127            subnet_req['gateway_ip'] = None
  128         try:
  129             subnet_rsp = self.obj.create_subnet({'subnet': subnet_req})
  130             self.logger.debug(
  131                 'Response for create_subnet : ' +
subnet_rsp undefined
self = <quantum_test.QuantumHelper object>
self.obj = <neutronclient.v2_0.client.Client object>
self.obj.create_subnet = <bound method Client.create_subnet of <neutronclient.v2_0.client.Client object>>
subnet_req = {'cidr': '35.129.130.0/26', 'enable_dhcp': True, 'ip_version': '4', 'ipam_fq_name': ['default-domain', 'default-project', 'default-network-ipam'], 'network_id': '2c00d40d-5a2f-4508-9951-5a0ac8d5b41d'}

 /usr/local/lib/python3.6/site-packages/neutronclient/v2_0/client.py in create_subnet(self=<neutronclient.v2_0.client.Client object>, body={'subnet': {'cidr': '35.129.130.0/26', 'enable_dhcp': True, 'ip_version': '4', 'ipam_fq_name': ['default-domain', 'default-project', 'default-network-ipam'], 'network_id': '2c00d40d-5a2f-4508-9951-5a0ac8d5b41d'}})
  846     def create_subnet(self, body=None):
  847         """Creates a new subnet."""
  848         return self.post(self.subnets_path, body=body)
  849 
  850     def update_subnet(self, subnet, body=None, revision_number=None):
self = <neutronclient.v2_0.client.Client object>
self.post = <bound method ClientBase.post of <neutronclient.v2_0.client.Client object>>
self.subnets_path = '/subnets'
body = {'subnet': {'cidr': '35.129.130.0/26', 'enable_dhcp': True, 'ip_version': '4', 'ipam_fq_name': ['default-domain', 'default-project', 'default-network-ipam'], 'network_id': '2c00d40d-5a2f-4508-9951-5a0ac8d5b41d'}}

 /usr/local/lib/python3.6/site-packages/neutronclient/v2_0/client.py in post(self=<neutronclient.v2_0.client.Client object>, action='/subnets', body={'subnet': {'cidr': '35.129.130.0/26', 'enable_dhcp': True, 'ip_version': '4', 'ipam_fq_name': ['default-domain', 'default-project', 'default-network-ipam'], 'network_id': '2c00d40d-5a2f-4508-9951-5a0ac8d5b41d'}}, headers=None, params=None)
  357         # Do not retry POST requests to avoid the orphan objects problem.
  358         return self.do_request("POST", action, body=body,
  359                                headers=headers, params=params)
  360 
  361     def put(self, action, body=None, headers=None, params=None):
headers = None
params = None

 /usr/local/lib/python3.6/site-packages/neutronclient/v2_0/client.py in do_request(self=<neutronclient.v2_0.client.Client object>, method='POST', action='/v2.0/subnets', body='{"subnet": {"cidr": "35.129.130.0/26", "network_...in", "default-project", "default-network-ipam"]}}', headers=None, params=None)
  280 
  281         resp, replybody = self.httpclient.do_request(action, method, body=body,
  282                                                      headers=headers)
  283 
  284         status_code = resp.status_code
headers = None

 /usr/local/lib/python3.6/site-packages/neutronclient/client.py in do_request(self=<neutronclient.client.SessionClient object>, url='/v2.0/subnets', method='POST', **kwargs={'authenticated': True, 'body': '{"subnet": {"cidr": "35.129.130.0/26", "network_...in", "default-project", "default-network-ipam"]}}', 'headers': None})
  338         kwargs.setdefault('authenticated', True)
  339         self._check_uri_length(url)
  340         return self.request(url, method, **kwargs)
  341 
  342     @property
self = <neutronclient.client.SessionClient object>
self.request = <bound method SessionClient.request of <neutronclient.client.SessionClient object>>
url = '/v2.0/subnets'
method = 'POST'
kwargs = {'authenticated': True, 'body': '{"subnet": {"cidr": "35.129.130.0/26", "network_...in", "default-project", "default-network-ipam"]}}', 'headers': None}

 /usr/local/lib/python3.6/site-packages/neutronclient/client.py in request(self=<neutronclient.client.SessionClient object>, *args=('/v2.0/subnets', 'POST'), **kwargs={'authenticated': True, 'data': '{"subnet": {"cidr": "35.129.130.0/26", "network_...in", "default-project", "default-network-ipam"]}}', 'headers': {'Accept': 'application/json', 'Content-Type': 'application/json', 'User-Agent': 'python-neutronclient', 'X-Auth-Token': '1959d1bdaf094797a1187e87117102f3'}, 'raise_exc': False})
  326 
  327         kwargs['headers'] = headers
  328         resp = super(SessionClient, self).request(*args, **kwargs)
  329         return resp, resp.text
  330 
resp undefined
builtinsuper = <class 'super'>
global SessionClient = <class 'neutronclient.client.SessionClient'>
self = <neutronclient.client.SessionClient object>
).request = <bound method SessionClient.request of <neutronclient.client.SessionClient object>>
args = ('/v2.0/subnets', 'POST')
kwargs = {'authenticated': True, 'data': '{"subnet": {"cidr": "35.129.130.0/26", "network_...in", "default-project", "default-network-ipam"]}}', 'headers': {'Accept': 'application/json', 'Content-Type': 'application/json', 'User-Agent': 'python-neutronclient', 'X-Auth-Token': '1959d1bdaf094797a1187e87117102f3'}, 'raise_exc': False}

 /usr/local/lib/python3.6/site-packages/keystoneauth1/adapter.py in request(self=<neutronclient.client.SessionClient object>, url='/v2.0/subnets', method='POST', **kwargs={'authenticated': True, 'data': '{"subnet": {"cidr": "35.129.130.0/26", "network_...in", "default-project", "default-network-ipam"]}}', 'endpoint_filter': {'interface': 'public', 'region_name': 'RegionOne', 'service_type': 'network'}, 'headers': {'Accept': 'application/json', 'Content-Type': 'application/json', 'User-Agent': 'python-neutronclient', 'X-Auth-Token': '1959d1bdaf094797a1187e87117102f3'}, 'raise_exc': False, 'rate_semaphore': <keystoneauth1._fair_semaphore.FairSemaphore object>, 'user_agent': 'python-neutronclient'})
  246             kwargs.setdefault('raise_exc', self.raise_exc)
  247 
  248         return self.session.request(url, method, **kwargs)
  249 
  250     def get_token(self, auth=None):
self = <neutronclient.client.SessionClient object>
self.session = <keystoneauth1.session.Session object>
self.session.request = <bound method Session.request of <keystoneauth1.session.Session object>>
url = '/v2.0/subnets'
method = 'POST'
kwargs = {'authenticated': True, 'data': '{"subnet": {"cidr": "35.129.130.0/26", "network_...in", "default-project", "default-network-ipam"]}}', 'endpoint_filter': {'interface': 'public', 'region_name': 'RegionOne', 'service_type': 'network'}, 'headers': {'Accept': 'application/json', 'Content-Type': 'application/json', 'User-Agent': 'python-neutronclient', 'X-Auth-Token': '1959d1bdaf094797a1187e87117102f3'}, 'raise_exc': False, 'rate_semaphore': <keystoneauth1._fair_semaphore.FairSemaphore object>, 'user_agent': 'python-neutronclient'}

 /usr/local/lib/python3.6/site-packages/keystoneauth1/session.py in request(self=<keystoneauth1.session.Session object>, url='http://192.168.7.31:9696/v2.0/subnets', method='POST', json=None, original_ip=None, user_agent='python-neutronclient', redirect=30, authenticated=True, endpoint_filter={'interface': 'public', 'region_name': 'RegionOne', 'service_type': 'network'}, auth=None, requests_auth=None, raise_exc=False, allow_reauth=True, log=True, endpoint_override=None, connect_retries=0, logger=<Logger keystoneauth.session (WARNING)>, allow=None, client_name=None, client_version=None, microversion=None, microversion_service_type=None, status_code_retries=0, retriable_status_codes=[503], rate_semaphore=<keystoneauth1._fair_semaphore.FairSemaphore object>, global_request_id=None, connect_retry_delay=None, status_code_retry_delay=None, **kwargs={'allow_redirects': False, 'cert': (None, None), 'data': '{"subnet": {"cidr": "35.129.130.0/26", "network_...in", "default-project", "default-network-ipam"]}}', 'headers': {'Accept': 'application/json', 'Content-Type': 'application/json', 'User-Agent': 'python-neutronclient', 'X-Auth-Token': '1959d1bdaf094797a1187e87117102f3'}, 'verify': False})
  911                 kwargs.update(connection_params)
  912 
  913         resp = send(**kwargs)
  914 
  915         # log callee and caller request-id for each api call
resp undefined
send = functools.partial(<bound method Session._send_re...auth1.session._Retries object at 0x7f715ff61a90>)
kwargs = {'allow_redirects': False, 'cert': (None, None), 'data': '{"subnet": {"cidr": "35.129.130.0/26", "network_...in", "default-project", "default-network-ipam"]}}', 'headers': {'Accept': 'application/json', 'Content-Type': 'application/json', 'User-Agent': 'python-neutronclient', 'X-Auth-Token': '1959d1bdaf094797a1187e87117102f3'}, 'verify': False}

 /usr/local/lib/python3.6/site-packages/keystoneauth1/session.py in _send_request(self=<keystoneauth1.session.Session object>, url='http://192.168.7.31:9696/v2.0/subnets', method='POST', redirect=30, log=True, logger=<Logger keystoneauth.session (WARNING)>, split_loggers=None, connect_retries=0, status_code_retries=0, retriable_status_codes=[503], rate_semaphore=<keystoneauth1._fair_semaphore.FairSemaphore object>, connect_retry_delays=<keystoneauth1.session._Retries object>, status_code_retry_delays=<keystoneauth1.session._Retries object>, **kwargs={'allow_redirects': False, 'cert': (None, None), 'data': '{"subnet": {"cidr": "35.129.130.0/26", "network_...in", "default-project", "default-network-ipam"]}}', 'headers': {'Accept': 'application/json', 'Content-Type': 'application/json', 'User-Agent': 'python-neutronclient', 'X-Auth-Token': '1959d1bdaf094797a1187e87117102f3'}, 'verify': False})
 1018                 # and firewall blocking.
 1019                 msg = 'Unable to establish connection to %s: %s' % (url, e)
 1020                 raise exceptions.ConnectFailure(msg)
 1021             except requests.exceptions.RequestException as e:
 1022                 msg = 'Unexpected exception for %(url)s: %(error)s' % {
global exceptions = <module 'keystoneauth1.exceptions' from '/usr/lo...e-packages/keystoneauth1/exceptions/__init__.py'>
exceptions.ConnectFailure = <class 'keystoneauth1.exceptions.connection.ConnectFailure'>
msg = "Unable to establish connection to http://192.168...Remote end closed connection without response',))"
ConnectFailure: Unable to establish connection to http://192.168.7.31:9696/v2.0/subnets: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
    __cause__ = None
    __class__ = <class 'keystoneauth1.exceptions.connection.ConnectFailure'>
    __context__ = ConnectionError(ProtocolError('Connection aborte...mote end closed connection without response',)),)
    __delattr__ = <method-wrapper '__delattr__' of ConnectFailure object>
    __dict__ = {'message': "Unable to establish connection to http://192.168...Remote end closed connection without response',))"}
    __dir__ = <built-in method __dir__ of ConnectFailure object>
    __doc__ = None
    __eq__ = <method-wrapper '__eq__' of ConnectFailure object>
    __format__ = <built-in method __format__ of ConnectFailure object>
    __ge__ = <method-wrapper '__ge__' of ConnectFailure object>
    __getattribute__ = <method-wrapper '__getattribute__' of ConnectFailure object>
    __gt__ = <method-wrapper '__gt__' of ConnectFailure object>
    __hash__ = <method-wrapper '__hash__' of ConnectFailure object>
    __init__ = <bound method ClientException.__init__ of Connec...te end closed connection without response',))",)>
    __init_subclass__ = <built-in method __init_subclass__ of type object>
    __le__ = <method-wrapper '__le__' of ConnectFailure object>
    __lt__ = <method-wrapper '__lt__' of ConnectFailure object>
    __module__ = 'keystoneauth1.exceptions.connection'
    __ne__ = <method-wrapper '__ne__' of ConnectFailure object>
    __new__ = <built-in method __new__ of type object>
    __reduce__ = <built-in method __reduce__ of ConnectFailure object>
    __reduce_ex__ = <built-in method __reduce_ex__ of ConnectFailure object>
    __repr__ = <method-wrapper '__repr__' of ConnectFailure object>
    __setattr__ = <method-wrapper '__setattr__' of ConnectFailure object>
    __setstate__ = <built-in method __setstate__ of ConnectFailure object>
    __sizeof__ = <built-in method __sizeof__ of ConnectFailure object>
    __str__ = <method-wrapper '__str__' of ConnectFailure object>
    __subclasshook__ = <built-in method __subclasshook__ of type object>
    __suppress_context__ = False
    __traceback__ = <traceback object>
    __weakref__ = None
    args = ("Unable to establish connection to http://192.168...Remote end closed connection without response',))",)
    message = "Unable to establish connection to http://192.168...Remote end closed connection without response',))"
    with_traceback = <built-in method with_traceback of ConnectFailure object>

The above is a description of an error in a Python program.  Here is
the original traceback:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib64/python3.6/http/client.py", line 1346, in getresponse
    response.begin()
  File "/usr/lib64/python3.6/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python3.6/http/client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/retry.py", line 400, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.6/site-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib64/python3.6/http/client.py", line 1346, in getresponse
    response.begin()
  File "/usr/lib64/python3.6/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python3.6/http/client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/keystoneauth1/session.py", line 1004, in _send_request
    resp = self.session.request(method, url, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/contrail-test/tcutils/wrappers.py", line 82, in wrapper
    result = function(self, *args, **kwargs)
  File "/contrail-test/scripts/svc_firewall/test_svc_fw.py", line 33, in test_svc_in_network_datapath
    create_svms=True)
  File "/contrail-test/common/servicechain/verify.py", line 328, in verify_svc_chain
    ret_dict = svc_chain_info or self.config_svc_chain(*args, **kwargs)
  File "/contrail-test/common/servicechain/config.py", line 474, in config_svc_chain
    **kwargs)
  File "/contrail-test/common/servicechain/config.py", line 375, in _get_vn_for_config
    vn_fixture = vn_fixture or self.config_vn(vn_name, vn_subnets, **kwargs)
  File "/contrail-test/common/servicechain/config.py", line 156, in config_vn
    vn_name=vn_name, inputs=self.inputs, subnets=vn_net, **kwargs))
  File "/usr/local/lib/python3.6/site-packages/testtools/testcase.py", line 756, in useFixture
    reraise(*exc_info)
  File "/usr/local/lib/python3.6/site-packages/testtools/_compat3x.py", line 16, in reraise
    raise exc_obj.with_traceback(exc_tb)
  File "/usr/local/lib/python3.6/site-packages/testtools/testcase.py", line 731, in useFixture
    fixture.setUp()
  File "/contrail-test/fixtures/vn_test.py", line 444, in setUp
    self.create()
  File "/contrail-test/fixtures/vn_test.py", line 457, in create
    self._create_vn_orch()
  File "/contrail-test/fixtures/vn_test.py", line 315, in _create_vn_orch
    dns_nameservers_list=self.dns_nameservers_list)
  File "/contrail-test/fixtures/openstack.py", line 186, in create_vn
    return self.quantum_h.create_network(name, subnets, **kwargs)
  File "/contrail-test/fixtures/quantum_test.py", line 109, in create_network
    subnet, net_id, ipam_fq_name, enable_dhcp, disable_gateway,dns_nameservers_list)
  File "/contrail-test/fixtures/quantum_test.py", line 129, in create_subnet
    subnet_rsp = self.obj.create_subnet({'subnet': subnet_req})
  File "/usr/local/lib/python3.6/site-packages/neutronclient/v2_0/client.py", line 848, in create_subnet
    return self.post(self.subnets_path, body=body)
  File "/usr/local/lib/python3.6/site-packages/neutronclient/v2_0/client.py", line 359, in post
    headers=headers, params=params)
  File "/usr/local/lib/python3.6/site-packages/neutronclient/v2_0/client.py", line 282, in do_request
    headers=headers)
  File "/usr/local/lib/python3.6/site-packages/neutronclient/client.py", line 340, in do_request
    return self.request(url, method, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/neutronclient/client.py", line 328, in request
    resp = super(SessionClient, self).request(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/keystoneauth1/adapter.py", line 248, in request
    return self.session.request(url, method, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/keystoneauth1/session.py", line 913, in request
    resp = send(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/keystoneauth1/session.py", line 1020, in _send_request
    raise exceptions.ConnectFailure(msg)
keystoneauth1.exceptions.connection.ConnectFailure: Unable to establish connection to http://192.168.7.31:9696/v2.0/subnets: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))



2021-02-22 05:25:08,180 - DEBUG - No XMPP flaps were noticed during the test
2021-02-22 05:25:08,181 - INFO - 
<div id=test_svc_in_network_datapath>2021-02-22 05:25:08,181 - INFO - END TEST : test_svc_in_network_datapath : FAILED[0:01:34]
</div>2021-02-22 05:25:08,181 - INFO - --------------------------------------------------------------------------------
2021-02-22 05:25:08,971 - WARNING - Project ctest-TestSvcRegr-67366984 still has VNs [{'to': ['admin_domain', 'ctest-TestSvcRegr-67366984', 'ctest-mgmt_vn-51304077'], 'href': 'https://192.168.7.34:8082/virtual-network/2c00d40d-5a2f-4508-9951-5a0ac8d5b41d', 'uuid': '2c00d40d-5a2f-4508-9951-5a0ac8d5b41d'}] before deletion
2021-02-22 05:25:11,091 - WARNING - Project ctest-TestSvcRegr-67366984 still has VNs [{'to': ['admin_domain', 'ctest-TestSvcRegr-67366984', 'ctest-mgmt_vn-51304077'], 'href': 'https://192.168.7.34:8082/virtual-network/2c00d40d-5a2f-4508-9951-5a0ac8d5b41d', 'uuid': '2c00d40d-5a2f-4508-9951-5a0ac8d5b41d'}] before deletion
2021-02-22 05:25:13,197 - WARNING - Project ctest-TestSvcRegr-67366984 still has VNs [{'to': ['admin_domain', 'ctest-TestSvcRegr-67366984', 'ctest-mgmt_vn-51304077'], 'href': 'https://192.168.7.34:8082/virtual-network/2c00d40d-5a2f-4508-9951-5a0ac8d5b41d', 'uuid': '2c00d40d-5a2f-4508-9951-5a0ac8d5b41d'}] before deletion
2021-02-22 05:25:15,307 - WARNING - Project ctest-TestSvcRegr-67366984 still has VNs [{'to': ['admin_domain', 'ctest-TestSvcRegr-67366984', 'ctest-mgmt_vn-51304077'], 'href': 'https://192.168.7.34:8082/virtual-network/2c00d40d-5a2f-4508-9951-5a0ac8d5b41d', 'uuid': '2c00d40d-5a2f-4508-9951-5a0ac8d5b41d'}] before deletion
2021-02-22 05:25:17,417 - WARNING - Project ctest-TestSvcRegr-67366984 still has VNs [{'to': ['admin_domain', 'ctest-TestSvcRegr-67366984', 'ctest-mgmt_vn-51304077'], 'href': 'https://192.168.7.34:8082/virtual-network/2c00d40d-5a2f-4508-9951-5a0ac8d5b41d', 'uuid': '2c00d40d-5a2f-4508-9951-5a0ac8d5b41d'}] before deletion
2021-02-22 05:25:19,540 - WARNING - Project ctest-TestSvcRegr-67366984 still has VNs [{'to': ['admin_domain', 'ctest-TestSvcRegr-67366984', 'ctest-mgmt_vn-51304077'], 'href': 'https://192.168.7.34:8082/virtual-network/2c00d40d-5a2f-4508-9951-5a0ac8d5b41d', 'uuid': '2c00d40d-5a2f-4508-9951-5a0ac8d5b41d'}] before deletion
2021-02-22 05:25:21,660 - WARNING - Project ctest-TestSvcRegr-67366984 still has VNs [{'to': ['admin_domain', 'ctest-TestSvcRegr-67366984', 'ctest-mgmt_vn-51304077'], 'href': 'https://192.168.7.34:8082/virtual-network/2c00d40d-5a2f-4508-9951-5a0ac8d5b41d', 'uuid': '2c00d40d-5a2f-4508-9951-5a0ac8d5b41d'}] before deletion
2021-02-22 05:25:23,780 - WARNING - Project ctest-TestSvcRegr-67366984 still has VNs [{'to': ['admin_domain', 'ctest-TestSvcRegr-67366984', 'ctest-mgmt_vn-51304077'], 'href': 'https://192.168.7.34:8082/virtual-network/2c00d40d-5a2f-4508-9951-5a0ac8d5b41d', 'uuid': '2c00d40d-5a2f-4508-9951-5a0ac8d5b41d'}] before deletion
2021-02-22 05:25:25,902 - WARNING - Project ctest-TestSvcRegr-67366984 still has VNs [{'to': ['admin_domain', 'ctest-TestSvcRegr-67366984', 'ctest-mgmt_vn-51304077'], 'href': 'https://192.168.7.34:8082/virtual-network/2c00d40d-5a2f-4508-9951-5a0ac8d5b41d', 'uuid': '2c00d40d-5a2f-4508-9951-5a0ac8d5b41d'}] before deletion
2021-02-22 05:25:28,022 - WARNING - Project ctest-TestSvcRegr-67366984 still has VNs [{'to': ['admin_domain', 'ctest-TestSvcRegr-67366984', 'ctest-mgmt_vn-51304077'], 'href': 'https://192.168.7.34:8082/virtual-network/2c00d40d-5a2f-4508-9951-5a0ac8d5b41d', 'uuid': '2c00d40d-5a2f-4508-9951-5a0ac8d5b41d'}] before deletion
2021-02-22 05:25:30,151 - WARNING - Project ctest-TestSvcRegr-67366984 still has VNs [{'to': ['admin_domain', 'ctest-TestSvcRegr-67366984', 'ctest-mgmt_vn-51304077'], 'href': 'https://192.168.7.34:8082/virtual-network/2c00d40d-5a2f-4508-9951-5a0ac8d5b41d', 'uuid': '2c00d40d-5a2f-4508-9951-5a0ac8d5b41d'}] before deletion
2021-02-22 05:25:32,259 - WARNING - Project ctest-TestSvcRegr-67366984 still has VNs [{'to': ['admin_domain', 'ctest-TestSvcRegr-67366984', 'ctest-mgmt_vn-51304077'], 'href': 'https://192.168.7.34:8082/virtual-network/2c00d40d-5a2f-4508-9951-5a0ac8d5b41d', 'uuid': '2c00d40d-5a2f-4508-9951-5a0ac8d5b41d'}] before deletion
2021-02-22 05:25:34,365 - WARNING - Project ctest-TestSvcRegr-67366984 still has VNs [{'to': ['admin_domain', 'ctest-TestSvcRegr-67366984', 'ctest-mgmt_vn-51304077'], 'href': 'https://192.168.7.34:8082/virtual-network/2c00d40d-5a2f-4508-9951-5a0ac8d5b41d', 'uuid': '2c00d40d-5a2f-4508-9951-5a0ac8d5b41d'}] before deletion
2021-02-22 05:25:36,483 - WARNING - Project ctest-TestSvcRegr-67366984 still has VNs [{'to': ['admin_domain', 'ctest-TestSvcRegr-67366984', 'ctest-mgmt_vn-51304077'], 'href': 'https://192.168.7.34:8082/virtual-network/2c00d40d-5a2f-4508-9951-5a0ac8d5b41d', 'uuid': '2c00d40d-5a2f-4508-9951-5a0ac8d5b41d'}] before deletion
2021-02-22 05:25:38,606 - WARNING - Project ctest-TestSvcRegr-67366984 still has VNs [{'to': ['admin_domain', 'ctest-TestSvcRegr-67366984', 'ctest-mgmt_vn-51304077'], 'href': 'https://192.168.7.34:8082/virtual-network/2c00d40d-5a2f-4508-9951-5a0ac8d5b41d', 'uuid': '2c00d40d-5a2f-4508-9951-5a0ac8d5b41d'}] before deletion
2021-02-22 05:25:40,741 - WARNING - Project ctest-TestSvcRegr-67366984 still has VNs [{'to': ['admin_domain', 'ctest-TestSvcRegr-67366984', 'ctest-mgmt_vn-51304077'], 'href': 'https://192.168.7.34:8082/virtual-network/2c00d40d-5a2f-4508-9951-5a0ac8d5b41d', 'uuid': '2c00d40d-5a2f-4508-9951-5a0ac8d5b41d'}] before deletion
2021-02-22 05:25:42,862 - WARNING - Project ctest-TestSvcRegr-67366984 still has VNs [{'to': ['admin_domain', 'ctest-TestSvcRegr-67366984', 'ctest-mgmt_vn-51304077'], 'href': 'https://192.168.7.34:8082/virtual-network/2c00d40d-5a2f-4508-9951-5a0ac8d5b41d', 'uuid': '2c00d40d-5a2f-4508-9951-5a0ac8d5b41d'}] before deletion
2021-02-22 05:25:44,981 - WARNING - Project ctest-TestSvcRegr-67366984 still has VNs [{'to': ['admin_domain', 'ctest-TestSvcRegr-67366984', 'ctest-mgmt_vn-51304077'], 'href': 'https://192.168.7.34:8082/virtual-network/2c00d40d-5a2f-4508-9951-5a0ac8d5b41d', 'uuid': '2c00d40d-5a2f-4508-9951-5a0ac8d5b41d'}] before deletion
2021-02-22 05:25:47,109 - WARNING - Project ctest-TestSvcRegr-67366984 still has VNs [{'to': ['admin_domain', 'ctest-TestSvcRegr-67366984', 'ctest-mgmt_vn-51304077'], 'href': 'https://192.168.7.34:8082/virtual-network/2c00d40d-5a2f-4508-9951-5a0ac8d5b41d', 'uuid': '2c00d40d-5a2f-4508-9951-5a0ac8d5b41d'}] before deletion
2021-02-22 05:25:49,232 - WARNING - Project ctest-TestSvcRegr-67366984 still has VNs [{'to': ['admin_domain', 'ctest-TestSvcRegr-67366984', 'ctest-mgmt_vn-51304077'], 'href': 'https://192.168.7.34:8082/virtual-network/2c00d40d-5a2f-4508-9951-5a0ac8d5b41d', 'uuid': '2c00d40d-5a2f-4508-9951-5a0ac8d5b41d'}] before deletion
2021-02-22 05:25:51,377 - WARNING - Project ctest-TestSvcRegr-67366984 still has VNs [{'to': ['admin_domain', 'ctest-TestSvcRegr-67366984', 'ctest-mgmt_vn-51304077'], 'href': 'https://192.168.7.34:8082/virtual-network/2c00d40d-5a2f-4508-9951-5a0ac8d5b41d', 'uuid': '2c00d40d-5a2f-4508-9951-5a0ac8d5b41d'}] before deletion
2021-02-22 05:25:53,494 - WARNING - Project ctest-TestSvcRegr-67366984 still has VNs [{'to': ['admin_domain', 'ctest-TestSvcRegr-67366984', 'ctest-mgmt_vn-51304077'], 'href': 'https://192.168.7.34:8082/virtual-network/2c00d40d-5a2f-4508-9951-5a0ac8d5b41d', 'uuid': '2c00d40d-5a2f-4508-9951-5a0ac8d5b41d'}] before deletion
2021-02-22 05:25:55,612 - WARNING - Project ctest-TestSvcRegr-67366984 still has VNs [{'to': ['admin_domain', 'ctest-TestSvcRegr-67366984', 'ctest-mgmt_vn-51304077'], 'href': 'https://192.168.7.34:8082/virtual-network/2c00d40d-5a2f-4508-9951-5a0ac8d5b41d', 'uuid': '2c00d40d-5a2f-4508-9951-5a0ac8d5b41d'}] before deletion
2021-02-22 05:25:57,725 - WARNING - Project ctest-TestSvcRegr-67366984 still has VNs [{'to': ['admin_domain', 'ctest-TestSvcRegr-67366984', 'ctest-mgmt_vn-51304077'], 'href': 'https://192.168.7.34:8082/virtual-network/2c00d40d-5a2f-4508-9951-5a0ac8d5b41d', 'uuid': '2c00d40d-5a2f-4508-9951-5a0ac8d5b41d'}] before deletion
2021-02-22 05:25:59,848 - WARNING - Project ctest-TestSvcRegr-67366984 still has VNs [{'to': ['admin_domain', 'ctest-TestSvcRegr-67366984', 'ctest-mgmt_vn-51304077'], 'href': 'https://192.168.7.34:8082/virtual-network/2c00d40d-5a2f-4508-9951-5a0ac8d5b41d', 'uuid': '2c00d40d-5a2f-4508-9951-5a0ac8d5b41d'}] before deletion
2021-02-22 05:26:01,967 - WARNING - Project ctest-TestSvcRegr-67366984 still has VNs [{'to': ['admin_domain', 'ctest-TestSvcRegr-67366984', 'ctest-mgmt_vn-51304077'], 'href': 'https://192.168.7.34:8082/virtual-network/2c00d40d-5a2f-4508-9951-5a0ac8d5b41d', 'uuid': '2c00d40d-5a2f-4508-9951-5a0ac8d5b41d'}] before deletion
2021-02-22 05:26:04,076 - WARNING - Project ctest-TestSvcRegr-67366984 still has VNs [{'to': ['admin_domain', 'ctest-TestSvcRegr-67366984', 'ctest-mgmt_vn-51304077'], 'href': 'https://192.168.7.34:8082/virtual-network/2c00d40d-5a2f-4508-9951-5a0ac8d5b41d', 'uuid': '2c00d40d-5a2f-4508-9951-5a0ac8d5b41d'}] before deletion
2021-02-22 05:26:06,231 - WARNING - Project ctest-TestSvcRegr-67366984 still has VNs [{'to': ['admin_domain', 'ctest-TestSvcRegr-67366984', 'ctest-mgmt_vn-51304077'], 'href': 'https://192.168.7.34:8082/virtual-network/2c00d40d-5a2f-4508-9951-5a0ac8d5b41d', 'uuid': '2c00d40d-5a2f-4508-9951-5a0ac8d5b41d'}] before deletion
2021-02-22 05:26:08,342 - WARNING - Project ctest-TestSvcRegr-67366984 still has VNs [{'to': ['admin_domain', 'ctest-TestSvcRegr-67366984', 'ctest-mgmt_vn-51304077'], 'href': 'https://192.168.7.34:8082/virtual-network/2c00d40d-5a2f-4508-9951-5a0ac8d5b41d', 'uuid': '2c00d40d-5a2f-4508-9951-5a0ac8d5b41d'}] before deletion
2021-02-22 05:26:10,467 - WARNING - Project ctest-TestSvcRegr-67366984 still has VNs [{'to': ['admin_domain', 'ctest-TestSvcRegr-67366984', 'ctest-mgmt_vn-51304077'], 'href': 'https://192.168.7.34:8082/virtual-network/2c00d40d-5a2f-4508-9951-5a0ac8d5b41d', 'uuid': '2c00d40d-5a2f-4508-9951-5a0ac8d5b41d'}] before deletion
2021-02-22 05:26:12,577 - WARNING - Project ctest-TestSvcRegr-67366984 still has VNs [{'to': ['admin_domain', 'ctest-TestSvcRegr-67366984', 'ctest-mgmt_vn-51304077'], 'href': 'https://192.168.7.34:8082/virtual-network/2c00d40d-5a2f-4508-9951-5a0ac8d5b41d', 'uuid': '2c00d40d-5a2f-4508-9951-5a0ac8d5b41d'}] before deletion
2021-02-22 05:26:12,581 - WARNING - One or more references still present, will not delete the project ctest-TestSvcRegr-67366984
2021-02-23 05:54:13,124 - INFO - Reading existing Domain with UUID f27c063f-c6c4-434f-a616-97e72e0043e5
2021-02-23 05:54:13,161 - INFO - Using existing domain ['admin_domain'](f27c063f-c6c4-434f-a616-97e72e0043e5)
2021-02-23 05:54:13,595 - INFO - Project ctest-TestSvcRegr-25072308 not found, creating it
2021-02-23 05:54:14,392 - INFO - Created Project:ctest-TestSvcRegr-25072308, ID : 411bf17d-5e50-4e55-be76-d5f32bad9c74 
2021-02-23 05:54:21,137 - INFO - ================================================================================
2021-02-23 05:54:21,137 - INFO - STARTING TEST    : test_svc_in_network_datapath
2021-02-23 05:54:21,422 - ERROR - [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/contrail-test/tcutils/cores.py", line 47, in get_cores_node
    if exists(CORE_DIR):
  File "/usr/local/lib64/python3.6/site-packages/fabric/contrib/files.py", line 31, in exists
    cmd = 'stat %s' % _expand_path(path)
  File "/usr/local/lib64/python3.6/site-packages/fabric/contrib/files.py", line 485, in _expand_path
    return path if is_win() else '"$(echo %s)"' % path
  File "/usr/local/lib64/python3.6/site-packages/fabric/contrib/files.py", line 472, in is_win
    return '"' in run('echo "Will you echo quotation marks"')
  File "/usr/local/lib64/python3.6/site-packages/fabric/network.py", line 692, in host_prompting_wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib64/python3.6/site-packages/fabric/operations.py", line 1095, in run
    shell_escape=shell_escape, capture_buffer_size=capture_buffer_size,
  File "/usr/local/lib64/python3.6/site-packages/fabric/operations.py", line 935, in _run_command
    channel=default_channel(), command=wrapped_command, pty=pty,
  File "/usr/local/lib64/python3.6/site-packages/fabric/state.py", line 435, in default_channel
    chan = _open_session()
  File "/usr/local/lib64/python3.6/site-packages/fabric/state.py", line 420, in _open_session
    session = transport.open_session(timeout=env.timeout)
  File "/usr/local/lib/python3.6/site-packages/paramiko/transport.py", line 879, in open_session
    timeout=timeout,
  File "/usr/local/lib/python3.6/site-packages/paramiko/transport.py", line 1006, in open_channel
    raise e
  File "/usr/local/lib/python3.6/site-packages/paramiko/transport.py", line 2055, in run
    ptype, m = self.packetizer.read_message()
  File "/usr/local/lib/python3.6/site-packages/paramiko/packet.py", line 459, in read_message
    header = self.read_all(self.__block_size_in, check_rekey=True)
  File "/usr/local/lib/python3.6/site-packages/paramiko/packet.py", line 301, in read_all
    x = self.__socket.recv(n)
  File "/usr/local/lib64/python3.6/site-packages/gevent/_socket3.py", line 378, in recv
    return _socket.socket.recv(self._sock, *args)
ConnectionResetError: [Errno 104] Connection reset by peer
2021-02-23 05:54:22,232 - DEBUG - Nothing to compare xmpp stats {'192.168.7.19': {'192.168.27.20': '0', '192.168.27.34': '0'}, '192.168.7.9': {'192.168.27.20': '0', '192.168.27.34': '0'}} with
2021-02-23 05:54:22,232 - INFO - Initial checks done. Running the testcase now
2021-02-23 05:54:22,232 - INFO - 
2021-02-23 05:54:24,080 - DEBUG - Response for create_network : {'network': {'status': 'ACTIVE', 'router:external': False, 'subnets': [], 'fq_name': ['admin_domain', 'ctest-TestSvcRegr-25072308', 'ctest-mgmt_vn-66178646'], 'name': 'ctest-mgmt_vn-66178646', 'admin_state_up': True, 'tenant_id': '411bf17d5e504e55be76d5f32bad9c74', 'created_at': None, 'updated_at': None, 'shared': False, 'port_security_enabled': True, 'project_id': '411bf17d5e504e55be76d5f32bad9c74', 'id': '4208a4a7-af0c-4c14-82c1-35616c4ab449', 'description': ''}}
2021-02-23 05:54:24,388 - DEBUG - Response for create_subnet : {'subnet': {'name': '', 'enable_dhcp': True, 'network_id': '4208a4a7-af0c-4c14-82c1-35616c4ab449', 'tenant_id': '411bf17d5e504e55be76d5f32bad9c74', 'created_at': '2021-02-23T05:54:23.609228', 'dns_nameservers': [], 'updated_at': '2021-02-23T05:54:23.609228', 'ipv6_ra_mode': None, 'allocation_pools': [{'start': '108.229.185.130', 'end': '108.229.185.190'}], 'gateway_ip': '108.229.185.129', 'dns_server_address': '108.229.185.130', 'ipv6_address_mode': None, 'ip_version': 4, 'host_routes': [], 'cidr': '108.229.185.128/26', 'id': 'e02a9456-9442-4a7f-a946-94f6cdd72de6'}}
2021-02-23 05:54:24,453 - INFO - Created VN ctest-mgmt_vn-66178646
2021-02-23 05:54:24,502 - DEBUG - VN ctest-mgmt_vn-66178646 UUID is 4208a4a7-af0c-4c14-82c1-35616c4ab449
2021-02-23 05:54:24,671 - DEBUG - Requesting: https://192.168.7.20:8082/domains
2021-02-23 05:54:26,386 - DEBUG - Requesting: https://192.168.7.20:8082/domains
2021-02-23 05:54:26,513 - DEBUG - Requesting: https://192.168.7.20:8082/domain/f27c063f-c6c4-434f-a616-97e72e0043e5
2021-02-23 05:54:26,570 - DEBUG - Requesting: https://192.168.7.20:8082/project/411bf17d-5e50-4e55-be76-d5f32bad9c74
2021-02-23 05:54:26,630 - DEBUG - Requesting: https://192.168.7.20:8082/virtual-network/4208a4a7-af0c-4c14-82c1-35616c4ab449
2021-02-23 05:54:26,660 - DEBUG - Requesting: https://192.168.7.20:8082/virtual-network/4208a4a7-af0c-4c14-82c1-35616c4ab449
2021-02-23 05:54:26,686 - DEBUG - Requesting: https://192.168.7.20:8082/routing-instance/20bd75a8-d4e1-4506-b347-01d81f10b909
2021-02-23 05:54:26,710 - DEBUG - Requesting: https://192.168.7.20:8082/routing-instance/20bd75a8-d4e1-4506-b347-01d81f10b909
2021-02-23 05:54:26,737 - DEBUG - Requesting: https://192.168.7.20:8082/route-target/c7ff94b6-b26c-49f0-acdc-06fa7d5a1391
2021-02-23 05:54:26,769 - DEBUG - Route Targets: ['target:64512:8000028']
2021-02-23 05:54:26,769 - DEBUG - Requesting: https://192.168.7.20:8082/virtual-network/4208a4a7-af0c-4c14-82c1-35616c4ab449
2021-02-23 05:54:26,801 - DEBUG - Requesting: https://192.168.7.20:8082/routing-instance/20bd75a8-d4e1-4506-b347-01d81f10b909
2021-02-23 05:54:26,847 - INFO - Verified VN network id 40 for VN 4208a4a7-af0c-4c14-82c1-35616c4ab449
2021-02-23 05:54:26,847 - INFO - Verifications in API Server for VN ctest-mgmt_vn-66178646 passed
2021-02-23 05:54:26,847 - DEBUG - Requesting: https://192.168.7.20:8082/virtual-network/4208a4a7-af0c-4c14-82c1-35616c4ab449
2021-02-23 05:54:26,876 - DEBUG - Requesting: https://192.168.7.20:8082/routing-instance/20bd75a8-d4e1-4506-b347-01d81f10b909
2021-02-23 05:54:26,905 - DEBUG - Requesting: https://192.168.7.20:8082/routing-instance/20bd75a8-d4e1-4506-b347-01d81f10b909
2021-02-23 05:54:26,927 - DEBUG - Requesting: https://192.168.7.20:8082/route-target/c7ff94b6-b26c-49f0-acdc-06fa7d5a1391
2021-02-23 05:54:26,960 - DEBUG - Requesting: https://192.168.7.20:8083/Snh_IFMapTableShowReq?table_name=virtual-network&search_string=virtual-network:admin_domain:ctest-TestSvcRegr-25072308:ctest-mgmt_vn-66178646
2021-02-23 05:54:26,979 - DEBUG - Control-node 192.168.7.20 : VN object is : {'node_name': 'virtual-network:admin_domain:ctest-TestSvcRegr-25072308:ctest-mgmt_vn-66178646', 'interests': '-', 'advertised': '-', 'dbentryflags': None, 'obj_info': {'sequence_number': '0', 'origin': 'Cassandra', 'data': {'id-perms': {'permissions': {'owner': 'ctest-TestSvcRegr-25072308', 'owner-access': '7', 'group': 'admin', 'group-access': '7', 'other-access': '7'}, 'uuid': {'uuid-mslong': '4758234046420241428', 'uuid-lslong': '9421870587980723273'}, 'enable': 'true', 'created': '2021-02-23T05:54:23', 'last-modified': '2021-02-23T05:54:23', 'description': None, 'user-visible': 'true', 'creator': None}}}, 'neighbors': None, 'last_modified': '00:00:02.658859'}
2021-02-23 05:54:26,979 - DEBUG - Requesting: https://192.168.7.20:8083/Snh_ShowRoutingInstanceReq?name=admin_domain:ctest-TestSvcRegr-25072308:ctest-mgmt_vn-66178646:ctest-mgmt_vn-66178646
2021-02-23 05:54:26,996 - DEBUG - Route Targets: ['target:64512:8000028']
2021-02-23 05:54:26,996 - DEBUG - Requesting: https://192.168.7.29:8083/Snh_IFMapTableShowReq?table_name=virtual-network&search_string=virtual-network:admin_domain:ctest-TestSvcRegr-25072308:ctest-mgmt_vn-66178646
2021-02-23 05:54:27,018 - DEBUG - Control-node 192.168.7.29 : VN object is : {'node_name': 'virtual-network:admin_domain:ctest-TestSvcRegr-25072308:ctest-mgmt_vn-66178646', 'interests': '-', 'advertised': '-', 'dbentryflags': None, 'obj_info': {'sequence_number': '0', 'origin': 'Cassandra', 'data': {'id-perms': {'permissions': {'owner': 'ctest-TestSvcRegr-25072308', 'owner-access': '7', 'group': 'admin', 'group-access': '7', 'other-access': '7'}, 'uuid': {'uuid-mslong': '4758234046420241428', 'uuid-lslong': '9421870587980723273'}, 'enable': 'true', 'created': '2021-02-23T05:54:23', 'last-modified': '2021-02-23T05:54:23', 'description': None, 'user-visible': 'true', 'creator': None}}}, 'neighbors': None, 'last_modified': '00:00:02.698745'}
2021-02-23 05:54:27,018 - DEBUG - Requesting: https://192.168.7.29:8083/Snh_ShowRoutingInstanceReq?name=admin_domain:ctest-TestSvcRegr-25072308:ctest-mgmt_vn-66178646:ctest-mgmt_vn-66178646
2021-02-23 05:54:27,216 - DEBUG - Route Targets: ['target:64512:8000028']
2021-02-23 05:54:27,216 - DEBUG - Requesting: https://192.168.7.34:8083/Snh_IFMapTableShowReq?table_name=virtual-network&search_string=virtual-network:admin_domain:ctest-TestSvcRegr-25072308:ctest-mgmt_vn-66178646
2021-02-23 05:54:27,234 - DEBUG - Control-node 192.168.7.34 : VN object is : {'node_name': 'virtual-network:admin_domain:ctest-TestSvcRegr-25072308:ctest-mgmt_vn-66178646', 'interests': '-', 'advertised': '-', 'dbentryflags': None, 'obj_info': {'sequence_number': '0', 'origin': 'Cassandra', 'data': {'id-perms': {'permissions': {'owner': 'ctest-TestSvcRegr-25072308', 'owner-access': '7', 'group': 'admin', 'group-access': '7', 'other-access': '7'}, 'uuid': {'uuid-mslong': '4758234046420241428', 'uuid-lslong': '9421870587980723273'}, 'enable': 'true', 'created': '2021-02-23T05:54:23', 'last-modified': '2021-02-23T05:54:23', 'description': None, 'user-visible': 'true', 'creator': None}}}, 'neighbors': None, 'last_modified': '00:00:02.914496'}
2021-02-23 05:54:27,234 - DEBUG - Requesting: https://192.168.7.34:8083/Snh_ShowRoutingInstanceReq?name=admin_domain:ctest-TestSvcRegr-25072308:ctest-mgmt_vn-66178646:ctest-mgmt_vn-66178646
2021-02-23 05:54:27,254 - DEBUG - Route Targets: ['target:64512:8000028']
2021-02-23 05:54:27,254 - INFO - On all control nodes, Config, RI and RT verification for VN ctest-mgmt_vn-66178646 passed
2021-02-23 05:54:27,255 - DEBUG - ====Verifying policy data for ctest-mgmt_vn-66178646 in API_Server ======
2021-02-23 05:54:27,255 - DEBUG - Requesting: https://192.168.7.20:8082/domains
2021-02-23 05:54:27,278 - DEBUG - Requesting: https://192.168.7.20:8082/domain/f27c063f-c6c4-434f-a616-97e72e0043e5
2021-02-23 05:54:27,326 - DEBUG - Requesting: https://192.168.7.20:8082/project/411bf17d-5e50-4e55-be76-d5f32bad9c74
2021-02-23 05:54:27,387 - DEBUG - Requesting: https://192.168.7.20:8082/virtual-network/4208a4a7-af0c-4c14-82c1-35616c4ab449
2021-02-23 05:54:27,420 - DEBUG - =>VN ctest-mgmt_vn-66178646 has no policy to be verified
2021-02-23 05:54:27,420 - DEBUG - Verifying the vn in opserver
2021-02-23 05:54:27,421 - DEBUG - Verifying the admin_domain:ctest-TestSvcRegr-25072308:ctest-mgmt_vn-66178646 virtual network link  through opserver 192.168.7.20
2021-02-23 05:54:27,421 - DEBUG - Requesting: https://192.168.7.20:8081/analytics/uves/virtual-networks
2021-02-23 05:54:27,936 - DEBUG - Requesting: https://192.168.7.20:8081/analytics/uves/virtual-networks
2021-02-23 05:54:28,073 - DEBUG - vn link and name as {'href': 'https://192.168.7.20:8081/analytics/uves/virtual-network/admin_domain:ctest-TestSvcRegr-25072308:ctest-mgmt_vn-66178646?flat', 'name': 'admin_domain:ctest-TestSvcRegr-25072308:ctest-mgmt_vn-66178646'}
2021-02-23 05:54:28,073 - DEBUG - Verifying the admin_domain:ctest-TestSvcRegr-25072308:ctest-mgmt_vn-66178646 virtual network link  through opserver 192.168.7.29
2021-02-23 05:54:28,073 - DEBUG - Requesting: https://192.168.7.29:8081/analytics/uves/virtual-networks
2021-02-23 05:54:28,605 - DEBUG - Requesting: https://192.168.7.29:8081/analytics/uves/virtual-networks
2021-02-23 05:54:28,745 - DEBUG - Verifying the admin_domain:ctest-TestSvcRegr-25072308:ctest-mgmt_vn-66178646 virtual network link  through opserver 192.168.7.34
2021-02-23 05:54:28,745 - DEBUG - Requesting: https://192.168.7.34:8081/analytics/uves/virtual-networks
2021-02-23 05:54:29,332 - DEBUG - Requesting: https://192.168.7.34:8081/analytics/uves/virtual-networks
2021-02-23 05:54:29,491 - DEBUG - vn link and name as {'href': 'https://192.168.7.34:8081/analytics/uves/virtual-network/admin_domain:ctest-TestSvcRegr-25072308:ctest-mgmt_vn-66178646?flat', 'name': 'admin_domain:ctest-TestSvcRegr-25072308:ctest-mgmt_vn-66178646'}
2021-02-23 05:54:29,491 - INFO - Validated that VN admin_domain:ctest-TestSvcRegr-25072308:ctest-mgmt_vn-66178646 is found in opserver
2021-02-23 05:54:29,732 - DEBUG - Do not have enough data to verify VN in agent
2021-02-23 05:54:29,848 - DEBUG - VRF ids for VN ctest-mgmt_vn-66178646: {}
2021-02-23 05:54:30,208 - DEBUG - Response for create_network : {'network': {'status': 'ACTIVE', 'router:external': False, 'subnets': [], 'fq_name': ['admin_domain', 'ctest-TestSvcRegr-25072308', 'ctest-left_vn-67489712'], 'name': 'ctest-left_vn-67489712', 'admin_state_up': True, 'tenant_id': '411bf17d5e504e55be76d5f32bad9c74', 'created_at': None, 'updated_at': None, 'shared': False, 'port_security_enabled': True, 'project_id': '411bf17d5e504e55be76d5f32bad9c74', 'id': 'ec593376-5b27-4eee-a80e-9e19e90af92e', 'description': ''}}
2021-02-23 05:56:00,241 - INFO - Deleting VN ctest-mgmt_vn-66178646 
2021-02-23 05:56:01,037 - DEBUG - Response for deleting network ()
2021-02-23 05:56:01,038 - DEBUG - Requesting: https://192.168.7.20:8082/routing-instance/20bd75a8-d4e1-4506-b347-01d81f10b909
2021-02-23 05:56:01,062 - DEBUG - Response Code: 404
2021-02-23 05:56:01,063 - DEBUG - Requesting: https://192.168.7.20:8082/domains
2021-02-23 05:56:01,083 - DEBUG - Requesting: https://192.168.7.20:8082/domain/f27c063f-c6c4-434f-a616-97e72e0043e5
2021-02-23 05:56:01,130 - DEBUG - Requesting: https://192.168.7.20:8082/project/411bf17d-5e50-4e55-be76-d5f32bad9c74
2021-02-23 05:56:01,200 - INFO - Validated that VN ctest-mgmt_vn-66178646 is not found in API Server
2021-02-23 05:56:01,320 - DEBUG - VN ctest-mgmt_vn-66178646 is not present in Agent 192.168.7.19 
2021-02-23 05:56:01,436 - DEBUG - VN ctest-mgmt_vn-66178646 is not present in Agent 192.168.7.9 
2021-02-23 05:56:01,436 - INFO - Validated that VN ctest-mgmt_vn-66178646 is not in any agent
2021-02-23 05:56:01,556 - DEBUG - Requesting: https://192.168.7.20:8083/Snh_ShowRoutingInstanceReq?name=admin_domain:ctest-TestSvcRegr-25072308:ctest-mgmt_vn-66178646:ctest-mgmt_vn-66178646
2021-02-23 05:56:01,617 - DEBUG - Requesting: https://192.168.7.29:8083/Snh_ShowRoutingInstanceReq?name=admin_domain:ctest-TestSvcRegr-25072308:ctest-mgmt_vn-66178646:ctest-mgmt_vn-66178646
2021-02-23 05:56:01,753 - DEBUG - Requesting: https://192.168.7.34:8083/Snh_ShowRoutingInstanceReq?name=admin_domain:ctest-TestSvcRegr-25072308:ctest-mgmt_vn-66178646:ctest-mgmt_vn-66178646
2021-02-23 05:56:01,817 - DEBUG - Requesting: https://192.168.7.34:8083/Snh_IFMapTableShowReq?table_name=virtual-network&search_string=virtual-network:admin_domain:ctest-TestSvcRegr-25072308:ctest-mgmt_vn-66178646
2021-02-23 05:56:01,877 - INFO - Validated that Routing instances and Config db in Control-nodes does not have VN ctest-mgmt_vn-66178646 info
2021-02-23 05:56:04,121 - ERROR - ConnectFailure
Python 3.6.8: /usr/bin/python3
Tue Feb 23 05:56:00 2021

A problem occurred in a Python script.  Here is the sequence of
function calls leading up to the error, in the order they occurred.

 /contrail-test/tcutils/wrappers.py in wrapper(self=<scripts.svc_firewall.test_svc_fw.TestSvcRegr.te...rk_datapath[ci_sanity,vcenter] id=0x7fc9f3ed4518>, *args=(), **kwargs={})
   80             log.info('Initial checks done. Running the testcase now')
   81             log.info('')
   82             result = function(self, *args, **kwargs)
   83             if self.inputs.upgrade:
   84                 pid = os.getpid()
result = None
function = <function TestSvcRegr.test_svc_in_network_datapath>
self = <scripts.svc_firewall.test_svc_fw.TestSvcRegr.te...rk_datapath[ci_sanity,vcenter] id=0x7fc9f3ed4518>
args = ()
kwargs = {}

 /contrail-test/scripts/svc_firewall/test_svc_fw.py in test_svc_in_network_datapath(self=<scripts.svc_firewall.test_svc_fw.TestSvcRegr.te...rk_datapath[ci_sanity,vcenter] id=0x7fc9f3ed4518>)
   31     def test_svc_in_network_datapath(self):
   32         return self.verify_svc_chain(svc_img_name='cirros_in_net', service_mode='in-network',
   33                                      create_svms=True)
   34 
   35 
create_svms undefined

 /contrail-test/common/servicechain/verify.py in verify_svc_chain(self=<scripts.svc_firewall.test_svc_fw.TestSvcRegr.te...rk_datapath[ci_sanity,vcenter] id=0x7fc9f3ed4518>, *args=(), **kwargs={'create_svms': True, 'service_mode': 'in-network', 'svc_img_name': 'cirros_in_net'})
  326     def verify_svc_chain(self, *args, **kwargs):
  327         svc_chain_info = kwargs.get('svc_chain_info')
  328         ret_dict = svc_chain_info or self.config_svc_chain(*args, **kwargs)
  329         proto = kwargs.get('proto', 'any')
  330         left_vn_fq_name = ret_dict.get('left_vn_fixture').vn_fq_name
ret_dict undefined
svc_chain_info = None
self = <scripts.svc_firewall.test_svc_fw.TestSvcRegr.te...rk_datapath[ci_sanity,vcenter] id=0x7fc9f3ed4518>
self.config_svc_chain = <bound method ConfigSvcChain.config_svc_chain of...k_datapath[ci_sanity,vcenter] id=0x7fc9f3ed4518>>
args = ()
kwargs = {'create_svms': True, 'service_mode': 'in-network', 'svc_img_name': 'cirros_in_net'}

 /contrail-test/common/servicechain/config.py in config_svc_chain(self=<scripts.svc_firewall.test_svc_fw.TestSvcRegr.te...rk_datapath[ci_sanity,vcenter] id=0x7fc9f3ed4518>, service_mode='in-network', service_type='firewall', max_inst=1, proto='any', svc_chain_type='parallel', src_ports=[0, 65535], dst_ports=[0, 65535], svc_img_name='cirros_in_net', st_version=2, mgmt_vn_name='ctest-mgmt_vn-66178646', mgmt_vn_subnets=['108.229.185.128/26'], mgmt_vn_fixture=<vn_test.VNFixture object>, left_vn_name=None, left_vn_subnets=[], left_vn_fixture=None, right_vn_name=None, right_vn_subnets=[], right_vn_fixture=None, left_lr_child_vn_fixture=None, right_lr_child_vn_fixture=None, left_vm_name=None, left_vm_fixture=None, right_vm_name=None, right_vm_fixture=None, image_name='ubuntu-traffic', policy_fixture=None, st_fixture=None, si_fixture=None, port_tuples_props=None, static_route=None, svm_fixtures=[], create_svms=True, evpn=False, modify_rules=False, policy_action='pass', hosts=[], **kwargs={})
  482                                                     left_vn_fixture,
  483                                                     'left_vn',
  484                                                     **kwargs)
  485 
  486         # Right
kwargs = {}

 /contrail-test/common/servicechain/config.py in _get_vn_for_config(self=<scripts.svc_firewall.test_svc_fw.TestSvcRegr.te...rk_datapath[ci_sanity,vcenter] id=0x7fc9f3ed4518>, vn_name='ctest-left_vn-67489712', vn_subnets=['41.108.153.64/26'], vn_fixture=None, vn_name_prefix='left_vn', **kwargs={})
  373             vn_subnets = vn_subnets or \
  374                                   [get_random_cidr(af=self.inputs.get_af())]
  375             vn_fixture = vn_fixture or self.config_vn(vn_name, vn_subnets, **kwargs)
  376         vn_fq_name = vn_fixture.vn_fq_name
  377         return (vn_name, vn_subnets, vn_fixture, vn_fq_name)
vn_fixture = None
self = <scripts.svc_firewall.test_svc_fw.TestSvcRegr.te...rk_datapath[ci_sanity,vcenter] id=0x7fc9f3ed4518>
self.config_vn = <bound method ConfigSvcChain.config_vn of <scrip...k_datapath[ci_sanity,vcenter] id=0x7fc9f3ed4518>>
vn_name = 'ctest-left_vn-67489712'
vn_subnets = ['41.108.153.64/26']
kwargs = {}

 /contrail-test/common/servicechain/config.py in config_vn(self=<scripts.svc_firewall.test_svc_fw.TestSvcRegr.te...rk_datapath[ci_sanity,vcenter] id=0x7fc9f3ed4518>, vn_name='ctest-left_vn-67489712', vn_net=['41.108.153.64/26'], **kwargs={})
  154         vn_fixture = self.useFixture(VNFixture(
  155             project_name=self.inputs.project_name, connections=self.connections,
  156             vn_name=vn_name, inputs=self.inputs, subnets=vn_net, **kwargs))
  157         assert vn_fixture.verify_on_setup()
  158         return vn_fixture
vn_name = 'ctest-left_vn-67489712'
inputs undefined
self = <scripts.svc_firewall.test_svc_fw.TestSvcRegr.te...rk_datapath[ci_sanity,vcenter] id=0x7fc9f3ed4518>
self.inputs = <common.contrail_test_init.ContrailTestInit object>
subnets undefined
vn_net = ['41.108.153.64/26']
kwargs = {}

 /usr/local/lib/python3.6/site-packages/testtools/testcase.py in useFixture(self=<scripts.svc_firewall.test_svc_fw.TestSvcRegr.te...rk_datapath[ci_sanity,vcenter] id=0x7fc9f3ed4518>, fixture=<vn_test.VNFixture object>)
  754                 # Gather_details worked, so raise the exception setUp
  755                 # encountered.
  756                 reraise(*exc_info)
  757         else:
  758             self.addCleanup(fixture.cleanUp)
global reraise = <function reraise>
exc_info = (<class 'keystoneauth1.exceptions.connection.ConnectFailure'>, ConnectFailure("Unable to establish connection t...ote end closed connection without response',))",), <traceback object>)

 /usr/local/lib/python3.6/site-packages/testtools/_compat3x.py in reraise(exc_class=<class 'keystoneauth1.exceptions.connection.ConnectFailure'>, exc_obj=ConnectFailure("Unable to establish connection t...ote end closed connection without response',))",), exc_tb=<traceback object>, _marker=<object object>)
   13 
   14 def reraise(exc_class, exc_obj, exc_tb, _marker=object()):
   15     """Re-raise an exception received from sys.exc_info() or similar."""
   16     raise exc_obj.with_traceback(exc_tb)
   17 
exc_obj = ConnectFailure("Unable to establish connection t...ote end closed connection without response',))",)
exc_obj.with_traceback = <built-in method with_traceback of ConnectFailure object>
exc_tb = <traceback object>

 /usr/local/lib/python3.6/site-packages/testtools/testcase.py in useFixture(self=<scripts.svc_firewall.test_svc_fw.TestSvcRegr.te...rk_datapath[ci_sanity,vcenter] id=0x7fc9f3ed4518>, fixture=<vn_test.VNFixture object>)
  729         """
  730         try:
  731             fixture.setUp()
  732         except MultipleExceptions as e:
  733             if (fixtures is not None and
fixture = <vn_test.VNFixture object>
fixture.setUp = <bound method VNFixture.setUp of <vn_test.VNFixture object>>

 /contrail-test/fixtures/vn_test.py in setUp(self=<vn_test.VNFixture object>)
  442     def setUp(self):
  443         super(VNFixture, self).setUp()
  444         self.create()
  445 
  446     def create(self):
self = <vn_test.VNFixture object>
self.create = <bound method VNFixture.create of <vn_test.VNFixture object>>

 /contrail-test/fixtures/vn_test.py in create(self=<vn_test.VNFixture object>)
  455             self._create_vn_api(self.vn_name, self.project_obj)
  456         else:
  457             self._create_vn_orch()
  458         if not self.obj:
  459              self.logger.debug('VN %s not present' % (self.vn_name))
self = <vn_test.VNFixture object>
self._create_vn_orch = <bound method VNFixture._create_vn_orch of <vn_test.VNFixture object>>

 /contrail-test/fixtures/vn_test.py in _create_vn_orch(self=<vn_test.VNFixture object>)
  313                                                 sriov_provider_network=self.sriov_provider_network,
  314                                                 disable_gateway=self.disable_gateway,
  315                                                 dns_nameservers_list=self.dns_nameservers_list)
  316                 if self.obj:
  317                     self.logger.info('Created VN %s' %(self.vn_name))
dns_nameservers_list undefined
self = <vn_test.VNFixture object>
self.dns_nameservers_list = None

 /contrail-test/fixtures/openstack.py in create_vn(self=<openstack.OpenstackOrchestrator object>, name='ctest-left_vn-67489712', subnets=[{'cidr': '41.108.153.64/26', 'enable_dhcp': True, 'ip_version': '4', 'ipam_fq_name': ['default-domain', 'default-project', 'default-network-ipam'], 'network_id': 'ec593376-5b27-4eee-a80e-9e19e90af92e'}], option='orch', **kwargs={'disable_gateway': False, 'dns_nameservers_list': None, 'enable_dhcp': True, 'ipam_fq_name': ['default-domain', 'default-project', 'default-network-ipam'], 'router_external': False, 'shared': False, 'sriov_enable': False, 'sriov_provider_network': None, 'sriov_vlan': None})
  184 
  185    def create_vn(self, name, subnets, option='orch', **kwargs):
  186        return self.quantum_h.create_network(name, subnets, **kwargs)
  187 
  188    def delete_vn(self, vn_obj, option='orch', **kwargs):
self = <openstack.OpenstackOrchestrator object>
self.quantum_h = <quantum_test.QuantumHelper object>
self.quantum_h.create_network = <bound method QuantumHelper.create_network of <quantum_test.QuantumHelper object>>
name = 'ctest-left_vn-67489712'
subnets = [{'cidr': '41.108.153.64/26', 'enable_dhcp': True, 'ip_version': '4', 'ipam_fq_name': ['default-domain', 'default-project', 'default-network-ipam'], 'network_id': 'ec593376-5b27-4eee-a80e-9e19e90af92e'}]
kwargs = {'disable_gateway': False, 'dns_nameservers_list': None, 'enable_dhcp': True, 'ipam_fq_name': ['default-domain', 'default-project', 'default-network-ipam'], 'router_external': False, 'shared': False, 'sriov_enable': False, 'sriov_provider_network': None, 'sriov_vlan': None}

 /contrail-test/fixtures/quantum_test.py in create_network(self=<quantum_test.QuantumHelper object>, vn_name='ctest-left_vn-67489712', vn_subnets=[{'cidr': '41.108.153.64/26', 'enable_dhcp': True, 'ip_version': '4', 'ipam_fq_name': ['default-domain', 'default-project', 'default-network-ipam'], 'network_id': 'ec593376-5b27-4eee-a80e-9e19e90af92e'}], ipam_fq_name=['default-domain', 'default-project', 'default-network-ipam'], shared=False, router_external=False, enable_dhcp=True, sriov_enable=False, sriov_vlan=None, sriov_provider_network=None, dns_nameservers_list=None, disable_gateway=False)
  107                 for subnet in vn_subnets:
  108                     net_rsp = self.create_subnet(
  109                         subnet, net_id, ipam_fq_name, enable_dhcp, disable_gateway,dns_nameservers_list)
  110             # end for
  111             return self.obj.show_network(network=net_id)
subnet = {'cidr': '41.108.153.64/26', 'enable_dhcp': True, 'ip_version': '4', 'ipam_fq_name': ['default-domain', 'default-project', 'default-network-ipam'], 'network_id': 'ec593376-5b27-4eee-a80e-9e19e90af92e'}
net_id = 'ec593376-5b27-4eee-a80e-9e19e90af92e'
ipam_fq_name = ['default-domain', 'default-project', 'default-network-ipam']
enable_dhcp = True
disable_gateway = False
dns_nameservers_list = None

 /contrail-test/fixtures/quantum_test.py in create_subnet(self=<quantum_test.QuantumHelper object>, subnet={'cidr': '41.108.153.64/26', 'enable_dhcp': True, 'ip_version': '4', 'ipam_fq_name': ['default-domain', 'default-project', 'default-network-ipam'], 'network_id': 'ec593376-5b27-4eee-a80e-9e19e90af92e'}, net_id='ec593376-5b27-4eee-a80e-9e19e90af92e', ipam_fq_name=['default-domain', 'default-project', 'default-network-ipam'], enable_dhcp=True, disable_gateway=False, dns_nameservers_list=None)
  127            subnet_req['gateway_ip'] = None
  128         try:
  129             subnet_rsp = self.obj.create_subnet({'subnet': subnet_req})
  130             self.logger.debug(
  131                 'Response for create_subnet : ' +
subnet_rsp undefined
self = <quantum_test.QuantumHelper object>
self.obj = <neutronclient.v2_0.client.Client object>
self.obj.create_subnet = <bound method Client.create_subnet of <neutronclient.v2_0.client.Client object>>
subnet_req = {'cidr': '41.108.153.64/26', 'enable_dhcp': True, 'ip_version': '4', 'ipam_fq_name': ['default-domain', 'default-project', 'default-network-ipam'], 'network_id': 'ec593376-5b27-4eee-a80e-9e19e90af92e'}

 /usr/local/lib/python3.6/site-packages/neutronclient/v2_0/client.py in create_subnet(self=<neutronclient.v2_0.client.Client object>, body={'subnet': {'cidr': '41.108.153.64/26', 'enable_dhcp': True, 'ip_version': '4', 'ipam_fq_name': ['default-domain', 'default-project', 'default-network-ipam'], 'network_id': 'ec593376-5b27-4eee-a80e-9e19e90af92e'}})
  846     def create_subnet(self, body=None):
  847         """Creates a new subnet."""
  848         return self.post(self.subnets_path, body=body)
  849 
  850     def update_subnet(self, subnet, body=None, revision_number=None):
self = <neutronclient.v2_0.client.Client object>
self.post = <bound method ClientBase.post of <neutronclient.v2_0.client.Client object>>
self.subnets_path = '/subnets'
body = {'subnet': {'cidr': '41.108.153.64/26', 'enable_dhcp': True, 'ip_version': '4', 'ipam_fq_name': ['default-domain', 'default-project', 'default-network-ipam'], 'network_id': 'ec593376-5b27-4eee-a80e-9e19e90af92e'}}

 /usr/local/lib/python3.6/site-packages/neutronclient/v2_0/client.py in post(self=<neutronclient.v2_0.client.Client object>, action='/subnets', body={'subnet': {'cidr': '41.108.153.64/26', 'enable_dhcp': True, 'ip_version': '4', 'ipam_fq_name': ['default-domain', 'default-project', 'default-network-ipam'], 'network_id': 'ec593376-5b27-4eee-a80e-9e19e90af92e'}}, headers=None, params=None)
  357         # Do not retry POST requests to avoid the orphan objects problem.
  358         return self.do_request("POST", action, body=body,
  359                                headers=headers, params=params)
  360 
  361     def put(self, action, body=None, headers=None, params=None):
headers = None
params = None

 /usr/local/lib/python3.6/site-packages/neutronclient/v2_0/client.py in do_request(self=<neutronclient.v2_0.client.Client object>, method='POST', action='/v2.0/subnets', body='{"subnet": {"cidr": "41.108.153.64/26", "network...in", "default-project", "default-network-ipam"]}}', headers=None, params=None)
  280 
  281         resp, replybody = self.httpclient.do_request(action, method, body=body,
  282                                                      headers=headers)
  283 
  284         status_code = resp.status_code
headers = None

 /usr/local/lib/python3.6/site-packages/neutronclient/client.py in do_request(self=<neutronclient.client.SessionClient object>, url='/v2.0/subnets', method='POST', **kwargs={'authenticated': True, 'body': '{"subnet": {"cidr": "41.108.153.64/26", "network...in", "default-project", "default-network-ipam"]}}', 'headers': None})
  338         kwargs.setdefault('authenticated', True)
  339         self._check_uri_length(url)
  340         return self.request(url, method, **kwargs)
  341 
  342     @property
self = <neutronclient.client.SessionClient object>
self.request = <bound method SessionClient.request of <neutronclient.client.SessionClient object>>
url = '/v2.0/subnets'
method = 'POST'
kwargs = {'authenticated': True, 'body': '{"subnet": {"cidr": "41.108.153.64/26", "network...in", "default-project", "default-network-ipam"]}}', 'headers': None}

 /usr/local/lib/python3.6/site-packages/neutronclient/client.py in request(self=<neutronclient.client.SessionClient object>, *args=('/v2.0/subnets', 'POST'), **kwargs={'authenticated': True, 'data': '{"subnet": {"cidr": "41.108.153.64/26", "network...in", "default-project", "default-network-ipam"]}}', 'headers': {'Accept': 'application/json', 'Content-Type': 'application/json', 'User-Agent': 'python-neutronclient', 'X-Auth-Token': 'fd286dd29b3c413f832b61158492e3fa'}, 'raise_exc': False})
  326 
  327         kwargs['headers'] = headers
  328         resp = super(SessionClient, self).request(*args, **kwargs)
  329         return resp, resp.text
  330 
resp undefined
builtinsuper = <class 'super'>
global SessionClient = <class 'neutronclient.client.SessionClient'>
self = <neutronclient.client.SessionClient object>
).request = <bound method SessionClient.request of <neutronclient.client.SessionClient object>>
args = ('/v2.0/subnets', 'POST')
kwargs = {'authenticated': True, 'data': '{"subnet": {"cidr": "41.108.153.64/26", "network...in", "default-project", "default-network-ipam"]}}', 'headers': {'Accept': 'application/json', 'Content-Type': 'application/json', 'User-Agent': 'python-neutronclient', 'X-Auth-Token': 'fd286dd29b3c413f832b61158492e3fa'}, 'raise_exc': False}

 /usr/local/lib/python3.6/site-packages/keystoneauth1/adapter.py in request(self=<neutronclient.client.SessionClient object>, url='/v2.0/subnets', method='POST', **kwargs={'authenticated': True, 'data': '{"subnet": {"cidr": "41.108.153.64/26", "network...in", "default-project", "default-network-ipam"]}}', 'endpoint_filter': {'interface': 'public', 'region_name': 'RegionOne', 'service_type': 'network'}, 'headers': {'Accept': 'application/json', 'Content-Type': 'application/json', 'User-Agent': 'python-neutronclient', 'X-Auth-Token': 'fd286dd29b3c413f832b61158492e3fa'}, 'raise_exc': False, 'rate_semaphore': <keystoneauth1._fair_semaphore.FairSemaphore object>, 'user_agent': 'python-neutronclient'})
  246             kwargs.setdefault('raise_exc', self.raise_exc)
  247 
  248         return self.session.request(url, method, **kwargs)
  249 
  250     def get_token(self, auth=None):
self = <neutronclient.client.SessionClient object>
self.session = <keystoneauth1.session.Session object>
self.session.request = <bound method Session.request of <keystoneauth1.session.Session object>>
url = '/v2.0/subnets'
method = 'POST'
kwargs = {'authenticated': True, 'data': '{"subnet": {"cidr": "41.108.153.64/26", "network...in", "default-project", "default-network-ipam"]}}', 'endpoint_filter': {'interface': 'public', 'region_name': 'RegionOne', 'service_type': 'network'}, 'headers': {'Accept': 'application/json', 'Content-Type': 'application/json', 'User-Agent': 'python-neutronclient', 'X-Auth-Token': 'fd286dd29b3c413f832b61158492e3fa'}, 'raise_exc': False, 'rate_semaphore': <keystoneauth1._fair_semaphore.FairSemaphore object>, 'user_agent': 'python-neutronclient'}

 /usr/local/lib/python3.6/site-packages/keystoneauth1/session.py in request(self=<keystoneauth1.session.Session object>, url='http://192.168.7.31:9696/v2.0/subnets', method='POST', json=None, original_ip=None, user_agent='python-neutronclient', redirect=30, authenticated=True, endpoint_filter={'interface': 'public', 'region_name': 'RegionOne', 'service_type': 'network'}, auth=None, requests_auth=None, raise_exc=False, allow_reauth=True, log=True, endpoint_override=None, connect_retries=0, logger=<Logger keystoneauth.session (WARNING)>, allow=None, client_name=None, client_version=None, microversion=None, microversion_service_type=None, status_code_retries=0, retriable_status_codes=[503], rate_semaphore=<keystoneauth1._fair_semaphore.FairSemaphore object>, global_request_id=None, connect_retry_delay=None, status_code_retry_delay=None, **kwargs={'allow_redirects': False, 'cert': (None, None), 'data': '{"subnet": {"cidr": "41.108.153.64/26", "network...in", "default-project", "default-network-ipam"]}}', 'headers': {'Accept': 'application/json', 'Content-Type': 'application/json', 'User-Agent': 'python-neutronclient', 'X-Auth-Token': 'fd286dd29b3c413f832b61158492e3fa'}, 'verify': False})
  911                 kwargs.update(connection_params)
  912 
  913         resp = send(**kwargs)
  914 
  915         # log callee and caller request-id for each api call
resp undefined
send = functools.partial(<bound method Session._send_re...auth1.session._Retries object at 0x7fc9f2476a90>)
kwargs = {'allow_redirects': False, 'cert': (None, None), 'data': '{"subnet": {"cidr": "41.108.153.64/26", "network...in", "default-project", "default-network-ipam"]}}', 'headers': {'Accept': 'application/json', 'Content-Type': 'application/json', 'User-Agent': 'python-neutronclient', 'X-Auth-Token': 'fd286dd29b3c413f832b61158492e3fa'}, 'verify': False}

 /usr/local/lib/python3.6/site-packages/keystoneauth1/session.py in _send_request(self=<keystoneauth1.session.Session object>, url='http://192.168.7.31:9696/v2.0/subnets', method='POST', redirect=30, log=True, logger=<Logger keystoneauth.session (WARNING)>, split_loggers=None, connect_retries=0, status_code_retries=0, retriable_status_codes=[503], rate_semaphore=<keystoneauth1._fair_semaphore.FairSemaphore object>, connect_retry_delays=<keystoneauth1.session._Retries object>, status_code_retry_delays=<keystoneauth1.session._Retries object>, **kwargs={'allow_redirects': False, 'cert': (None, None), 'data': '{"subnet": {"cidr": "41.108.153.64/26", "network...in", "default-project", "default-network-ipam"]}}', 'headers': {'Accept': 'application/json', 'Content-Type': 'application/json', 'User-Agent': 'python-neutronclient', 'X-Auth-Token': 'fd286dd29b3c413f832b61158492e3fa'}, 'verify': False})
 1018                 # and firewall blocking.
 1019                 msg = 'Unable to establish connection to %s: %s' % (url, e)
 1020                 raise exceptions.ConnectFailure(msg)
 1021             except requests.exceptions.RequestException as e:
 1022                 msg = 'Unexpected exception for %(url)s: %(error)s' % {
global exceptions = <module 'keystoneauth1.exceptions' from '/usr/lo...e-packages/keystoneauth1/exceptions/__init__.py'>
exceptions.ConnectFailure = <class 'keystoneauth1.exceptions.connection.ConnectFailure'>
msg = "Unable to establish connection to http://192.168...Remote end closed connection without response',))"
ConnectFailure: Unable to establish connection to http://192.168.7.31:9696/v2.0/subnets: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
    __cause__ = None
    __class__ = <class 'keystoneauth1.exceptions.connection.ConnectFailure'>
    __context__ = ConnectionError(ProtocolError('Connection aborte...mote end closed connection without response',)),)
    __delattr__ = <method-wrapper '__delattr__' of ConnectFailure object>
    __dict__ = {'message': "Unable to establish connection to http://192.168...Remote end closed connection without response',))"}
    __dir__ = <built-in method __dir__ of ConnectFailure object>
    __doc__ = None
    __eq__ = <method-wrapper '__eq__' of ConnectFailure object>
    __format__ = <built-in method __format__ of ConnectFailure object>
    __ge__ = <method-wrapper '__ge__' of ConnectFailure object>
    __getattribute__ = <method-wrapper '__getattribute__' of ConnectFailure object>
    __gt__ = <method-wrapper '__gt__' of ConnectFailure object>
    __hash__ = <method-wrapper '__hash__' of ConnectFailure object>
    __init__ = <bound method ClientException.__init__ of Connec...te end closed connection without response',))",)>
    __init_subclass__ = <built-in method __init_subclass__ of type object>
    __le__ = <method-wrapper '__le__' of ConnectFailure object>
    __lt__ = <method-wrapper '__lt__' of ConnectFailure object>
    __module__ = 'keystoneauth1.exceptions.connection'
    __ne__ = <method-wrapper '__ne__' of ConnectFailure object>
    __new__ = <built-in method __new__ of type object>
    __reduce__ = <built-in method __reduce__ of ConnectFailure object>
    __reduce_ex__ = <built-in method __reduce_ex__ of ConnectFailure object>
    __repr__ = <method-wrapper '__repr__' of ConnectFailure object>
    __setattr__ = <method-wrapper '__setattr__' of ConnectFailure object>
    __setstate__ = <built-in method __setstate__ of ConnectFailure object>
    __sizeof__ = <built-in method __sizeof__ of ConnectFailure object>
    __str__ = <method-wrapper '__str__' of ConnectFailure object>
    __subclasshook__ = <built-in method __subclasshook__ of type object>
    __suppress_context__ = False
    __traceback__ = <traceback object>
    __weakref__ = None
    args = ("Unable to establish connection to http://192.168...Remote end closed connection without response',))",)
    message = "Unable to establish connection to http://192.168...Remote end closed connection without response',))"
    with_traceback = <built-in method with_traceback of ConnectFailure object>

The above is a description of an error in a Python program.  Here is
the original traceback:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib64/python3.6/http/client.py", line 1346, in getresponse
    response.begin()
  File "/usr/lib64/python3.6/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python3.6/http/client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/retry.py", line 400, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.6/site-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib64/python3.6/http/client.py", line 1346, in getresponse
    response.begin()
  File "/usr/lib64/python3.6/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python3.6/http/client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/keystoneauth1/session.py", line 1004, in _send_request
    resp = self.session.request(method, url, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/contrail-test/tcutils/wrappers.py", line 82, in wrapper
    result = function(self, *args, **kwargs)
  File "/contrail-test/scripts/svc_firewall/test_svc_fw.py", line 33, in test_svc_in_network_datapath
    create_svms=True)
  File "/contrail-test/common/servicechain/verify.py", line 328, in verify_svc_chain
    ret_dict = svc_chain_info or self.config_svc_chain(*args, **kwargs)
  File "/contrail-test/common/servicechain/config.py", line 484, in config_svc_chain
    **kwargs)
  File "/contrail-test/common/servicechain/config.py", line 375, in _get_vn_for_config
    vn_fixture = vn_fixture or self.config_vn(vn_name, vn_subnets, **kwargs)
  File "/contrail-test/common/servicechain/config.py", line 156, in config_vn
    vn_name=vn_name, inputs=self.inputs, subnets=vn_net, **kwargs))
  File "/usr/local/lib/python3.6/site-packages/testtools/testcase.py", line 756, in useFixture
    reraise(*exc_info)
  File "/usr/local/lib/python3.6/site-packages/testtools/_compat3x.py", line 16, in reraise
    raise exc_obj.with_traceback(exc_tb)
  File "/usr/local/lib/python3.6/site-packages/testtools/testcase.py", line 731, in useFixture
    fixture.setUp()
  File "/contrail-test/fixtures/vn_test.py", line 444, in setUp
    self.create()
  File "/contrail-test/fixtures/vn_test.py", line 457, in create
    self._create_vn_orch()
  File "/contrail-test/fixtures/vn_test.py", line 315, in _create_vn_orch
    dns_nameservers_list=self.dns_nameservers_list)
  File "/contrail-test/fixtures/openstack.py", line 186, in create_vn
    return self.quantum_h.create_network(name, subnets, **kwargs)
  File "/contrail-test/fixtures/quantum_test.py", line 109, in create_network
    subnet, net_id, ipam_fq_name, enable_dhcp, disable_gateway,dns_nameservers_list)
  File "/contrail-test/fixtures/quantum_test.py", line 129, in create_subnet
    subnet_rsp = self.obj.create_subnet({'subnet': subnet_req})
  File "/usr/local/lib/python3.6/site-packages/neutronclient/v2_0/client.py", line 848, in create_subnet
    return self.post(self.subnets_path, body=body)
  File "/usr/local/lib/python3.6/site-packages/neutronclient/v2_0/client.py", line 359, in post
    headers=headers, params=params)
  File "/usr/local/lib/python3.6/site-packages/neutronclient/v2_0/client.py", line 282, in do_request
    headers=headers)
  File "/usr/local/lib/python3.6/site-packages/neutronclient/client.py", line 340, in do_request
    return self.request(url, method, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/neutronclient/client.py", line 328, in request
    resp = super(SessionClient, self).request(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/keystoneauth1/adapter.py", line 248, in request
    return self.session.request(url, method, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/keystoneauth1/session.py", line 913, in request
    resp = send(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/keystoneauth1/session.py", line 1020, in _send_request
    raise exceptions.ConnectFailure(msg)
keystoneauth1.exceptions.connection.ConnectFailure: Unable to establish connection to http://192.168.7.31:9696/v2.0/subnets: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))



2021-02-23 05:56:04,161 - DEBUG - No XMPP flaps were noticed during the test
2021-02-23 05:56:04,161 - INFO - 
<div id=test_svc_in_network_datapath>2021-02-23 05:56:04,161 - INFO - END TEST : test_svc_in_network_datapath : FAILED[0:01:43]
</div>2021-02-23 05:56:04,161 - INFO - --------------------------------------------------------------------------------
2021-02-23 05:56:04,297 - WARNING - Project ctest-TestSvcRegr-25072308 still has VNs [{'to': ['admin_domain', 'ctest-TestSvcRegr-25072308', 'ctest-left_vn-67489712'], 'href': 'https://192.168.7.34:8082/virtual-network/ec593376-5b27-4eee-a80e-9e19e90af92e', 'uuid': 'ec593376-5b27-4eee-a80e-9e19e90af92e'}] before deletion
2021-02-23 05:56:06,397 - WARNING - Project ctest-TestSvcRegr-25072308 still has VNs [{'to': ['admin_domain', 'ctest-TestSvcRegr-25072308', 'ctest-left_vn-67489712'], 'href': 'https://192.168.7.34:8082/virtual-network/ec593376-5b27-4eee-a80e-9e19e90af92e', 'uuid': 'ec593376-5b27-4eee-a80e-9e19e90af92e'}] before deletion
2021-02-23 05:56:08,517 - WARNING - Project ctest-TestSvcRegr-25072308 still has VNs [{'to': ['admin_domain', 'ctest-TestSvcRegr-25072308', 'ctest-left_vn-67489712'], 'href': 'https://192.168.7.34:8082/virtual-network/ec593376-5b27-4eee-a80e-9e19e90af92e', 'uuid': 'ec593376-5b27-4eee-a80e-9e19e90af92e'}] before deletion
2021-02-23 05:56:10,638 - WARNING - Project ctest-TestSvcRegr-25072308 still has VNs [{'to': ['admin_domain', 'ctest-TestSvcRegr-25072308', 'ctest-left_vn-67489712'], 'href': 'https://192.168.7.34:8082/virtual-network/ec593376-5b27-4eee-a80e-9e19e90af92e', 'uuid': 'ec593376-5b27-4eee-a80e-9e19e90af92e'}] before deletion
2021-02-23 05:56:12,771 - WARNING - Project ctest-TestSvcRegr-25072308 still has VNs [{'to': ['admin_domain', 'ctest-TestSvcRegr-25072308', 'ctest-left_vn-67489712'], 'href': 'https://192.168.7.34:8082/virtual-network/ec593376-5b27-4eee-a80e-9e19e90af92e', 'uuid': 'ec593376-5b27-4eee-a80e-9e19e90af92e'}] before deletion
2021-02-23 05:56:14,890 - WARNING - Project ctest-TestSvcRegr-25072308 still has VNs [{'to': ['admin_domain', 'ctest-TestSvcRegr-25072308', 'ctest-left_vn-67489712'], 'href': 'https://192.168.7.34:8082/virtual-network/ec593376-5b27-4eee-a80e-9e19e90af92e', 'uuid': 'ec593376-5b27-4eee-a80e-9e19e90af92e'}] before deletion
2021-02-23 05:56:16,991 - WARNING - Project ctest-TestSvcRegr-25072308 still has VNs [{'to': ['admin_domain', 'ctest-TestSvcRegr-25072308', 'ctest-left_vn-67489712'], 'href': 'https://192.168.7.34:8082/virtual-network/ec593376-5b27-4eee-a80e-9e19e90af92e', 'uuid': 'ec593376-5b27-4eee-a80e-9e19e90af92e'}] before deletion
2021-02-23 05:56:19,105 - WARNING - Project ctest-TestSvcRegr-25072308 still has VNs [{'to': ['admin_domain', 'ctest-TestSvcRegr-25072308', 'ctest-left_vn-67489712'], 'href': 'https://192.168.7.34:8082/virtual-network/ec593376-5b27-4eee-a80e-9e19e90af92e', 'uuid': 'ec593376-5b27-4eee-a80e-9e19e90af92e'}] before deletion
2021-02-23 05:56:21,213 - WARNING - Project ctest-TestSvcRegr-25072308 still has VNs [{'to': ['admin_domain', 'ctest-TestSvcRegr-25072308', 'ctest-left_vn-67489712'], 'href': 'https://192.168.7.34:8082/virtual-network/ec593376-5b27-4eee-a80e-9e19e90af92e', 'uuid': 'ec593376-5b27-4eee-a80e-9e19e90af92e'}] before deletion
2021-02-23 05:56:23,320 - WARNING - Project ctest-TestSvcRegr-25072308 still has VNs [{'to': ['admin_domain', 'ctest-TestSvcRegr-25072308', 'ctest-left_vn-67489712'], 'href': 'https://192.168.7.34:8082/virtual-network/ec593376-5b27-4eee-a80e-9e19e90af92e', 'uuid': 'ec593376-5b27-4eee-a80e-9e19e90af92e'}] before deletion
2021-02-23 05:56:25,453 - WARNING - Project ctest-TestSvcRegr-25072308 still has VNs [{'to': ['admin_domain', 'ctest-TestSvcRegr-25072308', 'ctest-left_vn-67489712'], 'href': 'https://192.168.7.34:8082/virtual-network/ec593376-5b27-4eee-a80e-9e19e90af92e', 'uuid': 'ec593376-5b27-4eee-a80e-9e19e90af92e'}] before deletion
2021-02-23 05:56:27,591 - WARNING - Project ctest-TestSvcRegr-25072308 still has VNs [{'to': ['admin_domain', 'ctest-TestSvcRegr-25072308', 'ctest-left_vn-67489712'], 'href': 'https://192.168.7.34:8082/virtual-network/ec593376-5b27-4eee-a80e-9e19e90af92e', 'uuid': 'ec593376-5b27-4eee-a80e-9e19e90af92e'}] before deletion
2021-02-23 05:56:29,704 - WARNING - Project ctest-TestSvcRegr-25072308 still has VNs [{'to': ['admin_domain', 'ctest-TestSvcRegr-25072308', 'ctest-left_vn-67489712'], 'href': 'https://192.168.7.34:8082/virtual-network/ec593376-5b27-4eee-a80e-9e19e90af92e', 'uuid': 'ec593376-5b27-4eee-a80e-9e19e90af92e'}] before deletion
2021-02-23 05:56:31,827 - WARNING - Project ctest-TestSvcRegr-25072308 still has VNs [{'to': ['admin_domain', 'ctest-TestSvcRegr-25072308', 'ctest-left_vn-67489712'], 'href': 'https://192.168.7.34:8082/virtual-network/ec593376-5b27-4eee-a80e-9e19e90af92e', 'uuid': 'ec593376-5b27-4eee-a80e-9e19e90af92e'}] before deletion
2021-02-23 05:56:33,948 - WARNING - Project ctest-TestSvcRegr-25072308 still has VNs [{'to': ['admin_domain', 'ctest-TestSvcRegr-25072308', 'ctest-left_vn-67489712'], 'href': 'https://192.168.7.34:8082/virtual-network/ec593376-5b27-4eee-a80e-9e19e90af92e', 'uuid': 'ec593376-5b27-4eee-a80e-9e19e90af92e'}] before deletion
2021-02-23 05:56:36,057 - WARNING - Project ctest-TestSvcRegr-25072308 still has VNs [{'to': ['admin_domain', 'ctest-TestSvcRegr-25072308', 'ctest-left_vn-67489712'], 'href': 'https://192.168.7.34:8082/virtual-network/ec593376-5b27-4eee-a80e-9e19e90af92e', 'uuid': 'ec593376-5b27-4eee-a80e-9e19e90af92e'}] before deletion
2021-02-23 05:56:38,172 - WARNING - Project ctest-TestSvcRegr-25072308 still has VNs [{'to': ['admin_domain', 'ctest-TestSvcRegr-25072308', 'ctest-left_vn-67489712'], 'href': 'https://192.168.7.34:8082/virtual-network/ec593376-5b27-4eee-a80e-9e19e90af92e', 'uuid': 'ec593376-5b27-4eee-a80e-9e19e90af92e'}] before deletion
2021-02-23 05:56:40,275 - WARNING - Project ctest-TestSvcRegr-25072308 still has VNs [{'to': ['admin_domain', 'ctest-TestSvcRegr-25072308', 'ctest-left_vn-67489712'], 'href': 'https://192.168.7.34:8082/virtual-network/ec593376-5b27-4eee-a80e-9e19e90af92e', 'uuid': 'ec593376-5b27-4eee-a80e-9e19e90af92e'}] before deletion
2021-02-23 05:56:42,385 - WARNING - Project ctest-TestSvcRegr-25072308 still has VNs [{'to': ['admin_domain', 'ctest-TestSvcRegr-25072308', 'ctest-left_vn-67489712'], 'href': 'https://192.168.7.34:8082/virtual-network/ec593376-5b27-4eee-a80e-9e19e90af92e', 'uuid': 'ec593376-5b27-4eee-a80e-9e19e90af92e'}] before deletion
2021-02-23 05:56:44,495 - WARNING - Project ctest-TestSvcRegr-25072308 still has VNs [{'to': ['admin_domain', 'ctest-TestSvcRegr-25072308', 'ctest-left_vn-67489712'], 'href': 'https://192.168.7.34:8082/virtual-network/ec593376-5b27-4eee-a80e-9e19e90af92e', 'uuid': 'ec593376-5b27-4eee-a80e-9e19e90af92e'}] before deletion
2021-02-23 05:56:46,606 - WARNING - Project ctest-TestSvcRegr-25072308 still has VNs [{'to': ['admin_domain', 'ctest-TestSvcRegr-25072308', 'ctest-left_vn-67489712'], 'href': 'https://192.168.7.34:8082/virtual-network/ec593376-5b27-4eee-a80e-9e19e90af92e', 'uuid': 'ec593376-5b27-4eee-a80e-9e19e90af92e'}] before deletion
2021-02-23 05:56:48,728 - WARNING - Project ctest-TestSvcRegr-25072308 still has VNs [{'to': ['admin_domain', 'ctest-TestSvcRegr-25072308', 'ctest-left_vn-67489712'], 'href': 'https://192.168.7.34:8082/virtual-network/ec593376-5b27-4eee-a80e-9e19e90af92e', 'uuid': 'ec593376-5b27-4eee-a80e-9e19e90af92e'}] before deletion
2021-02-23 05:56:50,843 - WARNING - Project ctest-TestSvcRegr-25072308 still has VNs [{'to': ['admin_domain', 'ctest-TestSvcRegr-25072308', 'ctest-left_vn-67489712'], 'href': 'https://192.168.7.34:8082/virtual-network/ec593376-5b27-4eee-a80e-9e19e90af92e', 'uuid': 'ec593376-5b27-4eee-a80e-9e19e90af92e'}] before deletion
2021-02-23 05:56:52,952 - WARNING - Project ctest-TestSvcRegr-25072308 still has VNs [{'to': ['admin_domain', 'ctest-TestSvcRegr-25072308', 'ctest-left_vn-67489712'], 'href': 'https://192.168.7.34:8082/virtual-network/ec593376-5b27-4eee-a80e-9e19e90af92e', 'uuid': 'ec593376-5b27-4eee-a80e-9e19e90af92e'}] before deletion
2021-02-23 05:56:55,069 - WARNING - Project ctest-TestSvcRegr-25072308 still has VNs [{'to': ['admin_domain', 'ctest-TestSvcRegr-25072308', 'ctest-left_vn-67489712'], 'href': 'https://192.168.7.34:8082/virtual-network/ec593376-5b27-4eee-a80e-9e19e90af92e', 'uuid': 'ec593376-5b27-4eee-a80e-9e19e90af92e'}] before deletion
2021-02-23 05:56:57,188 - WARNING - Project ctest-TestSvcRegr-25072308 still has VNs [{'to': ['admin_domain', 'ctest-TestSvcRegr-25072308', 'ctest-left_vn-67489712'], 'href': 'https://192.168.7.34:8082/virtual-network/ec593376-5b27-4eee-a80e-9e19e90af92e', 'uuid': 'ec593376-5b27-4eee-a80e-9e19e90af92e'}] before deletion
2021-02-23 05:56:59,303 - WARNING - Project ctest-TestSvcRegr-25072308 still has VNs [{'to': ['admin_domain', 'ctest-TestSvcRegr-25072308', 'ctest-left_vn-67489712'], 'href': 'https://192.168.7.34:8082/virtual-network/ec593376-5b27-4eee-a80e-9e19e90af92e', 'uuid': 'ec593376-5b27-4eee-a80e-9e19e90af92e'}] before deletion
2021-02-23 05:57:01,462 - WARNING - Project ctest-TestSvcRegr-25072308 still has VNs [{'to': ['admin_domain', 'ctest-TestSvcRegr-25072308', 'ctest-left_vn-67489712'], 'href': 'https://192.168.7.34:8082/virtual-network/ec593376-5b27-4eee-a80e-9e19e90af92e', 'uuid': 'ec593376-5b27-4eee-a80e-9e19e90af92e'}] before deletion
2021-02-23 05:57:03,585 - WARNING - Project ctest-TestSvcRegr-25072308 still has VNs [{'to': ['admin_domain', 'ctest-TestSvcRegr-25072308', 'ctest-left_vn-67489712'], 'href': 'https://192.168.7.34:8082/virtual-network/ec593376-5b27-4eee-a80e-9e19e90af92e', 'uuid': 'ec593376-5b27-4eee-a80e-9e19e90af92e'}] before deletion
2021-02-23 05:57:05,703 - WARNING - Project ctest-TestSvcRegr-25072308 still has VNs [{'to': ['admin_domain', 'ctest-TestSvcRegr-25072308', 'ctest-left_vn-67489712'], 'href': 'https://192.168.7.34:8082/virtual-network/ec593376-5b27-4eee-a80e-9e19e90af92e', 'uuid': 'ec593376-5b27-4eee-a80e-9e19e90af92e'}] before deletion
2021-02-23 05:57:07,826 - WARNING - Project ctest-TestSvcRegr-25072308 still has VNs [{'to': ['admin_domain', 'ctest-TestSvcRegr-25072308', 'ctest-left_vn-67489712'], 'href': 'https://192.168.7.34:8082/virtual-network/ec593376-5b27-4eee-a80e-9e19e90af92e', 'uuid': 'ec593376-5b27-4eee-a80e-9e19e90af92e'}] before deletion
2021-02-23 05:57:07,827 - WARNING - One or more references still present, will not delete the project ctest-TestSvcRegr-25072308
2021-02-24 06:22:21,092 - INFO - Reading existing Domain with UUID f27c063f-c6c4-434f-a616-97e72e0043e5
2021-02-24 06:22:21,131 - INFO - Using existing domain ['admin_domain'](f27c063f-c6c4-434f-a616-97e72e0043e5)
2021-02-24 06:22:22,281 - INFO - Project ctest-TestSvcRegr-21662114 not found, creating it
2021-02-24 06:22:23,394 - INFO - Created Project:ctest-TestSvcRegr-21662114, ID : 7ed682e1-903c-4e87-86f0-68e3ca4e0045 
2021-02-24 06:22:30,682 - INFO - ================================================================================
2021-02-24 06:22:30,682 - INFO - STARTING TEST    : test_svc_in_network_datapath
2021-02-24 06:22:31,987 - DEBUG - Nothing to compare xmpp stats {'192.168.7.19': {'192.168.27.20': '0', '192.168.27.34': '0'}, '192.168.7.9': {'192.168.27.20': '0', '192.168.27.34': '0'}} with
2021-02-24 06:22:31,988 - INFO - Initial checks done. Running the testcase now
2021-02-24 06:22:31,988 - INFO - 
2021-02-24 06:22:34,718 - DEBUG - Response for create_network : {'network': {'status': 'ACTIVE', 'router:external': False, 'subnets': [], 'fq_name': ['admin_domain', 'ctest-TestSvcRegr-21662114', 'ctest-mgmt_vn-33657845'], 'name': 'ctest-mgmt_vn-33657845', 'admin_state_up': True, 'tenant_id': '7ed682e1903c4e8786f068e3ca4e0045', 'created_at': None, 'updated_at': None, 'shared': False, 'port_security_enabled': True, 'project_id': '7ed682e1903c4e8786f068e3ca4e0045', 'id': '788871cd-572c-43fe-902a-14f2f6c83786', 'description': ''}}
2021-02-24 06:22:35,194 - DEBUG - Response for create_subnet : {'subnet': {'name': '', 'enable_dhcp': True, 'network_id': '788871cd-572c-43fe-902a-14f2f6c83786', 'tenant_id': '7ed682e1903c4e8786f068e3ca4e0045', 'created_at': '2021-02-24T06:22:34.242600', 'dns_nameservers': [], 'updated_at': '2021-02-24T06:22:34.242600', 'ipv6_ra_mode': None, 'allocation_pools': [{'start': '69.120.14.2', 'end': '69.120.14.62'}], 'gateway_ip': '69.120.14.1', 'dns_server_address': '69.120.14.2', 'ipv6_address_mode': None, 'ip_version': 4, 'host_routes': [], 'cidr': '69.120.14.0/26', 'id': '36607453-0ed5-4889-9439-723caadaece8'}}
2021-02-24 06:22:35,243 - INFO - Created VN ctest-mgmt_vn-33657845
2021-02-24 06:22:35,277 - DEBUG - VN ctest-mgmt_vn-33657845 UUID is 788871cd-572c-43fe-902a-14f2f6c83786
2021-02-24 06:22:35,466 - DEBUG - Requesting: https://192.168.7.20:8082/domains
2021-02-24 06:22:36,241 - DEBUG - Requesting: https://192.168.7.20:8082/domains
2021-02-24 06:22:36,799 - DEBUG - Requesting: https://192.168.7.20:8082/domain/f27c063f-c6c4-434f-a616-97e72e0043e5
2021-02-24 06:22:36,851 - DEBUG - Requesting: https://192.168.7.20:8082/project/7ed682e1-903c-4e87-86f0-68e3ca4e0045
2021-02-24 06:22:36,912 - DEBUG - Requesting: https://192.168.7.20:8082/virtual-network/788871cd-572c-43fe-902a-14f2f6c83786
2021-02-24 06:22:36,941 - DEBUG - Requesting: https://192.168.7.20:8082/virtual-network/788871cd-572c-43fe-902a-14f2f6c83786
2021-02-24 06:22:36,966 - DEBUG - Requesting: https://192.168.7.20:8082/routing-instance/88bb1444-3ba8-4140-a1f1-d1bb2b3b9493
2021-02-24 06:22:36,992 - DEBUG - Requesting: https://192.168.7.20:8082/routing-instance/88bb1444-3ba8-4140-a1f1-d1bb2b3b9493
2021-02-24 06:22:37,016 - DEBUG - Requesting: https://192.168.7.20:8082/route-target/eaad72dc-1170-4d31-8cc6-dc91d657e406
2021-02-24 06:22:37,041 - DEBUG - Route Targets: ['target:64512:8000033']
2021-02-24 06:22:37,042 - DEBUG - Requesting: https://192.168.7.20:8082/virtual-network/788871cd-572c-43fe-902a-14f2f6c83786
2021-02-24 06:22:37,070 - DEBUG - Requesting: https://192.168.7.20:8082/routing-instance/88bb1444-3ba8-4140-a1f1-d1bb2b3b9493
2021-02-24 06:22:37,112 - INFO - Verified VN network id 13 for VN 788871cd-572c-43fe-902a-14f2f6c83786
2021-02-24 06:22:37,112 - INFO - Verifications in API Server for VN ctest-mgmt_vn-33657845 passed
2021-02-24 06:22:37,112 - DEBUG - Requesting: https://192.168.7.20:8082/virtual-network/788871cd-572c-43fe-902a-14f2f6c83786
2021-02-24 06:22:37,140 - DEBUG - Requesting: https://192.168.7.20:8082/routing-instance/88bb1444-3ba8-4140-a1f1-d1bb2b3b9493
2021-02-24 06:22:37,165 - DEBUG - Requesting: https://192.168.7.20:8082/routing-instance/88bb1444-3ba8-4140-a1f1-d1bb2b3b9493
2021-02-24 06:22:37,193 - DEBUG - Requesting: https://192.168.7.20:8082/route-target/eaad72dc-1170-4d31-8cc6-dc91d657e406
2021-02-24 06:22:37,216 - DEBUG - Requesting: https://192.168.7.20:8083/Snh_IFMapTableShowReq?table_name=virtual-network&search_string=virtual-network:admin_domain:ctest-TestSvcRegr-21662114:ctest-mgmt_vn-33657845
2021-02-24 06:22:37,235 - DEBUG - Control-node 192.168.7.20 : VN object is : {'node_name': 'virtual-network:admin_domain:ctest-TestSvcRegr-21662114:ctest-mgmt_vn-33657845', 'interests': '-', 'advertised': '-', 'dbentryflags': None, 'obj_info': {'sequence_number': '0', 'origin': 'Cassandra', 'data': {'id-perms': {'permissions': {'owner': 'ctest-TestSvcRegr-21662114', 'owner-access': '7', 'group': 'admin', 'group-access': '7', 'other-access': '7'}, 'uuid': {'uuid-mslong': '8685317008128754686', 'uuid-lslong': '10388138524238428038'}, 'enable': 'true', 'created': '2021-02-24T06:22:33', 'last-modified': '2021-02-24T06:22:34', 'description': None, 'user-visible': 'true', 'creator': None}}}, 'neighbors': None, 'last_modified': '00:00:02.135302'}
2021-02-24 06:22:37,235 - DEBUG - Requesting: https://192.168.7.20:8083/Snh_ShowRoutingInstanceReq?name=admin_domain:ctest-TestSvcRegr-21662114:ctest-mgmt_vn-33657845:ctest-mgmt_vn-33657845
2021-02-24 06:22:37,255 - DEBUG - Route Targets: ['target:64512:8000033']
2021-02-24 06:22:37,255 - DEBUG - Requesting: https://192.168.7.29:8083/Snh_IFMapTableShowReq?table_name=virtual-network&search_string=virtual-network:admin_domain:ctest-TestSvcRegr-21662114:ctest-mgmt_vn-33657845
2021-02-24 06:22:37,352 - DEBUG - Control-node 192.168.7.29 : VN object is : {'node_name': 'virtual-network:admin_domain:ctest-TestSvcRegr-21662114:ctest-mgmt_vn-33657845', 'interests': '-', 'advertised': '-', 'dbentryflags': None, 'obj_info': {'sequence_number': '0', 'origin': 'Cassandra', 'data': {'id-perms': {'permissions': {'owner': 'ctest-TestSvcRegr-21662114', 'owner-access': '7', 'group': 'admin', 'group-access': '7', 'other-access': '7'}, 'uuid': {'uuid-mslong': '8685317008128754686', 'uuid-lslong': '10388138524238428038'}, 'enable': 'true', 'created': '2021-02-24T06:22:33', 'last-modified': '2021-02-24T06:22:34', 'description': None, 'user-visible': 'true', 'creator': None}}}, 'neighbors': None, 'last_modified': '00:00:02.252482'}
2021-02-24 06:22:37,352 - DEBUG - Requesting: https://192.168.7.29:8083/Snh_ShowRoutingInstanceReq?name=admin_domain:ctest-TestSvcRegr-21662114:ctest-mgmt_vn-33657845:ctest-mgmt_vn-33657845
2021-02-24 06:22:37,452 - DEBUG - Route Targets: ['target:64512:8000033']
2021-02-24 06:22:37,452 - DEBUG - Requesting: https://192.168.7.34:8083/Snh_IFMapTableShowReq?table_name=virtual-network&search_string=virtual-network:admin_domain:ctest-TestSvcRegr-21662114:ctest-mgmt_vn-33657845
2021-02-24 06:22:37,469 - DEBUG - Control-node 192.168.7.34 : VN object is : {'node_name': 'virtual-network:admin_domain:ctest-TestSvcRegr-21662114:ctest-mgmt_vn-33657845', 'interests': '-', 'advertised': '-', 'dbentryflags': None, 'obj_info': {'sequence_number': '0', 'origin': 'Cassandra', 'data': {'id-perms': {'permissions': {'owner': 'ctest-TestSvcRegr-21662114', 'owner-access': '7', 'group': 'admin', 'group-access': '7', 'other-access': '7'}, 'uuid': {'uuid-mslong': '8685317008128754686', 'uuid-lslong': '10388138524238428038'}, 'enable': 'true', 'created': '2021-02-24T06:22:33', 'last-modified': '2021-02-24T06:22:34', 'description': None, 'user-visible': 'true', 'creator': None}}}, 'neighbors': None, 'last_modified': '00:00:02.369958'}
2021-02-24 06:22:37,469 - DEBUG - Requesting: https://192.168.7.34:8083/Snh_ShowRoutingInstanceReq?name=admin_domain:ctest-TestSvcRegr-21662114:ctest-mgmt_vn-33657845:ctest-mgmt_vn-33657845
2021-02-24 06:22:37,488 - DEBUG - Route Targets: ['target:64512:8000033']
2021-02-24 06:22:37,488 - INFO - On all control nodes, Config, RI and RT verification for VN ctest-mgmt_vn-33657845 passed
2021-02-24 06:22:37,490 - DEBUG - ====Verifying policy data for ctest-mgmt_vn-33657845 in API_Server ======
2021-02-24 06:22:37,490 - DEBUG - Requesting: https://192.168.7.20:8082/domains
2021-02-24 06:22:37,515 - DEBUG - Requesting: https://192.168.7.20:8082/domain/f27c063f-c6c4-434f-a616-97e72e0043e5
2021-02-24 06:22:37,560 - DEBUG - Requesting: https://192.168.7.20:8082/project/7ed682e1-903c-4e87-86f0-68e3ca4e0045
2021-02-24 06:22:37,620 - DEBUG - Requesting: https://192.168.7.20:8082/virtual-network/788871cd-572c-43fe-902a-14f2f6c83786
2021-02-24 06:22:37,644 - DEBUG - =>VN ctest-mgmt_vn-33657845 has no policy to be verified
2021-02-24 06:22:37,645 - DEBUG - Verifying the vn in opserver
2021-02-24 06:22:37,645 - DEBUG - Verifying the admin_domain:ctest-TestSvcRegr-21662114:ctest-mgmt_vn-33657845 virtual network link  through opserver 192.168.7.20
2021-02-24 06:22:37,646 - DEBUG - Requesting: https://192.168.7.20:8081/analytics/uves/virtual-networks
2021-02-24 06:22:38,387 - DEBUG - Requesting: https://192.168.7.20:8081/analytics/uves/virtual-networks
2021-02-24 06:22:38,790 - DEBUG - vn link and name as {'href': 'https://192.168.7.20:8081/analytics/uves/virtual-network/admin_domain:ctest-TestSvcRegr-21662114:ctest-mgmt_vn-33657845?flat', 'name': 'admin_domain:ctest-TestSvcRegr-21662114:ctest-mgmt_vn-33657845'}
2021-02-24 06:22:38,790 - DEBUG - Verifying the admin_domain:ctest-TestSvcRegr-21662114:ctest-mgmt_vn-33657845 virtual network link  through opserver 192.168.7.29
2021-02-24 06:22:38,790 - DEBUG - Requesting: https://192.168.7.29:8081/analytics/uves/virtual-networks
2021-02-24 06:22:39,631 - DEBUG - Requesting: https://192.168.7.29:8081/analytics/uves/virtual-networks
2021-02-24 06:22:39,830 - DEBUG - vn link and name as {'href': 'https://192.168.7.29:8081/analytics/uves/virtual-network/admin_domain:ctest-TestSvcRegr-21662114:ctest-mgmt_vn-33657845?flat', 'name': 'admin_domain:ctest-TestSvcRegr-21662114:ctest-mgmt_vn-33657845'}
2021-02-24 06:22:39,830 - DEBUG - Verifying the admin_domain:ctest-TestSvcRegr-21662114:ctest-mgmt_vn-33657845 virtual network link  through opserver 192.168.7.34
2021-02-24 06:22:39,831 - DEBUG - Requesting: https://192.168.7.34:8081/analytics/uves/virtual-networks
2021-02-24 06:22:40,578 - DEBUG - Requesting: https://192.168.7.34:8081/analytics/uves/virtual-networks
2021-02-24 06:22:41,725 - DEBUG - vn link and name as {'href': 'https://192.168.7.34:8081/analytics/uves/virtual-network/admin_domain:ctest-TestSvcRegr-21662114:ctest-mgmt_vn-33657845?flat', 'name': 'admin_domain:ctest-TestSvcRegr-21662114:ctest-mgmt_vn-33657845'}
2021-02-24 06:22:41,725 - INFO - Validated that VN admin_domain:ctest-TestSvcRegr-21662114:ctest-mgmt_vn-33657845 is found in opserver
2021-02-24 06:22:41,961 - DEBUG - Do not have enough data to verify VN in agent
2021-02-24 06:22:42,076 - DEBUG - VRF ids for VN ctest-mgmt_vn-33657845: {}
2021-02-24 06:22:42,423 - DEBUG - Response for create_network : {'network': {'status': 'ACTIVE', 'router:external': False, 'subnets': [], 'fq_name': ['admin_domain', 'ctest-TestSvcRegr-21662114', 'ctest-left_vn-16213293'], 'name': 'ctest-left_vn-16213293', 'admin_state_up': True, 'tenant_id': '7ed682e1903c4e8786f068e3ca4e0045', 'created_at': None, 'updated_at': None, 'shared': False, 'port_security_enabled': True, 'project_id': '7ed682e1903c4e8786f068e3ca4e0045', 'id': 'c9629181-5790-447b-895b-bc4d32362a3c', 'description': ''}}
2021-02-24 06:22:42,748 - DEBUG - Response for create_subnet : {'subnet': {'name': '', 'enable_dhcp': True, 'network_id': 'c9629181-5790-447b-895b-bc4d32362a3c', 'tenant_id': '7ed682e1903c4e8786f068e3ca4e0045', 'created_at': '2021-02-24T06:22:41.822928', 'dns_nameservers': [], 'updated_at': '2021-02-24T06:22:41.822928', 'ipv6_ra_mode': None, 'allocation_pools': [{'start': '79.132.127.130', 'end': '79.132.127.190'}], 'gateway_ip': '79.132.127.129', 'dns_server_address': '79.132.127.130', 'ipv6_address_mode': None, 'ip_version': 4, 'host_routes': [], 'cidr': '79.132.127.128/26', 'id': '97b5a474-8838-4a81-adc0-8bc0c4e38204'}}
2021-02-24 06:22:42,797 - INFO - Created VN ctest-left_vn-16213293
2021-02-24 06:22:42,833 - DEBUG - VN ctest-left_vn-16213293 UUID is c9629181-5790-447b-895b-bc4d32362a3c
2021-02-24 06:22:42,994 - DEBUG - Requesting: https://192.168.7.20:8082/domains
2021-02-24 06:22:43,015 - DEBUG - Requesting: https://192.168.7.20:8082/domain/f27c063f-c6c4-434f-a616-97e72e0043e5
2021-02-24 06:22:43,062 - DEBUG - Requesting: https://192.168.7.20:8082/project/7ed682e1-903c-4e87-86f0-68e3ca4e0045
2021-02-24 06:22:43,125 - DEBUG - Requesting: https://192.168.7.20:8082/virtual-network/c9629181-5790-447b-895b-bc4d32362a3c
2021-02-24 06:22:43,155 - DEBUG - Requesting: https://192.168.7.20:8082/virtual-network/c9629181-5790-447b-895b-bc4d32362a3c
2021-02-24 06:22:43,180 - DEBUG - Requesting: https://192.168.7.20:8082/routing-instance/843c4749-8d6c-4cd3-89c3-312e316f5a01
2021-02-24 06:22:43,204 - DEBUG - Requesting: https://192.168.7.20:8082/routing-instance/843c4749-8d6c-4cd3-89c3-312e316f5a01
2021-02-24 06:22:43,226 - DEBUG - Requesting: https://192.168.7.20:8082/route-target/fa21a4b6-d4c1-4b47-bbad-58e5e02ef9c9
2021-02-24 06:22:43,250 - DEBUG - Route Targets: ['target:64512:8000035']
2021-02-24 06:22:43,250 - DEBUG - Requesting: https://192.168.7.20:8082/virtual-network/c9629181-5790-447b-895b-bc4d32362a3c
2021-02-24 06:22:43,281 - DEBUG - Requesting: https://192.168.7.20:8082/routing-instance/843c4749-8d6c-4cd3-89c3-312e316f5a01
2021-02-24 06:22:43,323 - INFO - Verified VN network id 45 for VN c9629181-5790-447b-895b-bc4d32362a3c
2021-02-24 06:22:43,323 - INFO - Verifications in API Server for VN ctest-left_vn-16213293 passed
2021-02-24 06:22:43,324 - DEBUG - Requesting: https://192.168.7.20:8082/virtual-network/c9629181-5790-447b-895b-bc4d32362a3c
2021-02-24 06:22:43,354 - DEBUG - Requesting: https://192.168.7.20:8082/routing-instance/843c4749-8d6c-4cd3-89c3-312e316f5a01
2021-02-24 06:22:43,380 - DEBUG - Requesting: https://192.168.7.20:8082/routing-instance/843c4749-8d6c-4cd3-89c3-312e316f5a01
2021-02-24 06:22:43,403 - DEBUG - Requesting: https://192.168.7.20:8082/route-target/fa21a4b6-d4c1-4b47-bbad-58e5e02ef9c9
2021-02-24 06:22:43,426 - DEBUG - Requesting: https://192.168.7.20:8083/Snh_IFMapTableShowReq?table_name=virtual-network&search_string=virtual-network:admin_domain:ctest-TestSvcRegr-21662114:ctest-left_vn-16213293
2021-02-24 06:22:43,444 - DEBUG - Control-node 192.168.7.20 : VN object is : {'node_name': 'virtual-network:admin_domain:ctest-TestSvcRegr-21662114:ctest-left_vn-16213293', 'interests': '-', 'advertised': '-', 'dbentryflags': None, 'obj_info': {'sequence_number': '0', 'origin': 'Cassandra', 'data': {'id-perms': {'permissions': {'owner': 'ctest-TestSvcRegr-21662114', 'owner-access': '7', 'group': 'admin', 'group-access': '7', 'other-access': '7'}, 'uuid': {'uuid-mslong': '14511320934047040635', 'uuid-lslong': '9897711645817711164'}, 'enable': 'true', 'created': '2021-02-24T06:22:41', 'last-modified': '2021-02-24T06:22:41', 'description': None, 'user-visible': 'true', 'creator': None}}}, 'neighbors': None, 'last_modified': '00:00:00.764093'}
2021-02-24 06:22:43,444 - DEBUG - Requesting: https://192.168.7.20:8083/Snh_ShowRoutingInstanceReq?name=admin_domain:ctest-TestSvcRegr-21662114:ctest-left_vn-16213293:ctest-left_vn-16213293
2021-02-24 06:22:43,465 - DEBUG - Route Targets: ['target:64512:8000035']
2021-02-24 06:22:43,465 - DEBUG - Requesting: https://192.168.7.29:8083/Snh_IFMapTableShowReq?table_name=virtual-network&search_string=virtual-network:admin_domain:ctest-TestSvcRegr-21662114:ctest-left_vn-16213293
2021-02-24 06:22:43,487 - DEBUG - Control-node 192.168.7.29 : VN object is : {'node_name': 'virtual-network:admin_domain:ctest-TestSvcRegr-21662114:ctest-left_vn-16213293', 'interests': '-', 'advertised': '-', 'dbentryflags': None, 'obj_info': {'sequence_number': '0', 'origin': 'Cassandra', 'data': {'id-perms': {'permissions': {'owner': 'ctest-TestSvcRegr-21662114', 'owner-access': '7', 'group': 'admin', 'group-access': '7', 'other-access': '7'}, 'uuid': {'uuid-mslong': '14511320934047040635', 'uuid-lslong': '9897711645817711164'}, 'enable': 'true', 'created': '2021-02-24T06:22:41', 'last-modified': '2021-02-24T06:22:41', 'description': None, 'user-visible': 'true', 'creator': None}}}, 'neighbors': None, 'last_modified': '00:00:00.807274'}
2021-02-24 06:22:43,487 - DEBUG - Requesting: https://192.168.7.29:8083/Snh_ShowRoutingInstanceReq?name=admin_domain:ctest-TestSvcRegr-21662114:ctest-left_vn-16213293:ctest-left_vn-16213293
2021-02-24 06:22:43,510 - DEBUG - Route Targets: ['target:64512:8000035']
2021-02-24 06:22:43,510 - DEBUG - Requesting: https://192.168.7.34:8083/Snh_IFMapTableShowReq?table_name=virtual-network&search_string=virtual-network:admin_domain:ctest-TestSvcRegr-21662114:ctest-left_vn-16213293
2021-02-24 06:22:43,528 - DEBUG - Control-node 192.168.7.34 : VN object is : {'node_name': 'virtual-network:admin_domain:ctest-TestSvcRegr-21662114:ctest-left_vn-16213293', 'interests': '-', 'advertised': '-', 'dbentryflags': None, 'obj_info': {'sequence_number': '0', 'origin': 'Cassandra', 'data': {'id-perms': {'permissions': {'owner': 'ctest-TestSvcRegr-21662114', 'owner-access': '7', 'group': 'admin', 'group-access': '7', 'other-access': '7'}, 'uuid': {'uuid-mslong': '14511320934047040635', 'uuid-lslong': '9897711645817711164'}, 'enable': 'true', 'created': '2021-02-24T06:22:41', 'last-modified': '2021-02-24T06:22:41', 'description': None, 'user-visible': 'true', 'creator': None}}}, 'neighbors': None, 'last_modified': '00:00:00.847641'}
2021-02-24 06:22:43,528 - DEBUG - Requesting: https://192.168.7.34:8083/Snh_ShowRoutingInstanceReq?name=admin_domain:ctest-TestSvcRegr-21662114:ctest-left_vn-16213293:ctest-left_vn-16213293
2021-02-24 06:22:43,548 - DEBUG - Route Targets: ['target:64512:8000035']
2021-02-24 06:22:43,548 - INFO - On all control nodes, Config, RI and RT verification for VN ctest-left_vn-16213293 passed
2021-02-24 06:22:43,549 - DEBUG - ====Verifying policy data for ctest-left_vn-16213293 in API_Server ======
2021-02-24 06:22:43,549 - DEBUG - Requesting: https://192.168.7.20:8082/domains
2021-02-24 06:22:43,571 - DEBUG - Requesting: https://192.168.7.20:8082/domain/f27c063f-c6c4-434f-a616-97e72e0043e5
2021-02-24 06:22:43,615 - DEBUG - Requesting: https://192.168.7.20:8082/project/7ed682e1-903c-4e87-86f0-68e3ca4e0045
2021-02-24 06:22:43,680 - DEBUG - Requesting: https://192.168.7.20:8082/virtual-network/c9629181-5790-447b-895b-bc4d32362a3c
2021-02-24 06:22:43,704 - DEBUG - =>VN ctest-left_vn-16213293 has no policy to be verified
2021-02-24 06:22:43,704 - DEBUG - Verifying the vn in opserver
2021-02-24 06:22:43,704 - DEBUG - Verifying the admin_domain:ctest-TestSvcRegr-21662114:ctest-left_vn-16213293 virtual network link  through opserver 192.168.7.20
2021-02-24 06:22:43,704 - DEBUG - Requesting: https://192.168.7.20:8081/analytics/uves/virtual-networks
2021-02-24 06:22:43,940 - DEBUG - vn link and name as {'href': 'https://192.168.7.20:8081/analytics/uves/virtual-network/admin_domain:ctest-TestSvcRegr-21662114:ctest-left_vn-16213293?flat', 'name': 'admin_domain:ctest-TestSvcRegr-21662114:ctest-left_vn-16213293'}
2021-02-24 06:22:43,940 - DEBUG - Verifying the admin_domain:ctest-TestSvcRegr-21662114:ctest-left_vn-16213293 virtual network link  through opserver 192.168.7.29
2021-02-24 06:22:43,940 - DEBUG - Requesting: https://192.168.7.29:8081/analytics/uves/virtual-networks
2021-02-24 06:22:44,082 - DEBUG - vn link and name as {'href': 'https://192.168.7.29:8081/analytics/uves/virtual-network/admin_domain:ctest-TestSvcRegr-21662114:ctest-left_vn-16213293?flat', 'name': 'admin_domain:ctest-TestSvcRegr-21662114:ctest-left_vn-16213293'}
2021-02-24 06:22:44,082 - DEBUG - Verifying the admin_domain:ctest-TestSvcRegr-21662114:ctest-left_vn-16213293 virtual network link  through opserver 192.168.7.34
2021-02-24 06:22:44,082 - DEBUG - Requesting: https://192.168.7.34:8081/analytics/uves/virtual-networks
2021-02-24 06:22:44,311 - DEBUG - vn link and name as {'href': 'https://192.168.7.34:8081/analytics/uves/virtual-network/admin_domain:ctest-TestSvcRegr-21662114:ctest-left_vn-16213293?flat', 'name': 'admin_domain:ctest-TestSvcRegr-21662114:ctest-left_vn-16213293'}
2021-02-24 06:22:44,311 - INFO - Validated that VN admin_domain:ctest-TestSvcRegr-21662114:ctest-left_vn-16213293 is found in opserver
2021-02-24 06:22:44,552 - DEBUG - Do not have enough data to verify VN in agent
2021-02-24 06:22:44,664 - DEBUG - VRF ids for VN ctest-left_vn-16213293: {}
2021-02-24 06:22:44,996 - DEBUG - Response for create_network : {'network': {'status': 'ACTIVE', 'router:external': False, 'subnets': [], 'fq_name': ['admin_domain', 'ctest-TestSvcRegr-21662114', 'ctest-right_vn-24695491'], 'name': 'ctest-right_vn-24695491', 'admin_state_up': True, 'tenant_id': '7ed682e1903c4e8786f068e3ca4e0045', 'created_at': None, 'updated_at': None, 'shared': False, 'port_security_enabled': True, 'project_id': '7ed682e1903c4e8786f068e3ca4e0045', 'id': '800da3e6-7c55-4e66-906e-985310b6b16e', 'description': ''}}
2021-02-24 06:22:45,322 - DEBUG - Response for create_subnet : {'subnet': {'name': '', 'enable_dhcp': True, 'network_id': '800da3e6-7c55-4e66-906e-985310b6b16e', 'tenant_id': '7ed682e1903c4e8786f068e3ca4e0045', 'created_at': '2021-02-24T06:22:46.805898', 'dns_nameservers': [], 'updated_at': '2021-02-24T06:22:46.805898', 'ipv6_ra_mode': None, 'allocation_pools': [{'start': '182.34.247.194', 'end': '182.34.247.254'}], 'gateway_ip': '182.34.247.193', 'dns_server_address': '182.34.247.194', 'ipv6_address_mode': None, 'ip_version': 4, 'host_routes': [], 'cidr': '182.34.247.192/26', 'id': '39d72af0-9bdb-442d-93d8-e8205917bf80'}}
2021-02-24 06:22:45,375 - INFO - Created VN ctest-right_vn-24695491
2021-02-24 06:22:45,405 - DEBUG - VN ctest-right_vn-24695491 UUID is 800da3e6-7c55-4e66-906e-985310b6b16e
2021-02-24 06:22:45,581 - DEBUG - Requesting: https://192.168.7.20:8082/domains
2021-02-24 06:22:45,606 - DEBUG - Requesting: https://192.168.7.20:8082/domain/f27c063f-c6c4-434f-a616-97e72e0043e5
2021-02-24 06:22:45,653 - DEBUG - Requesting: https://192.168.7.20:8082/project/7ed682e1-903c-4e87-86f0-68e3ca4e0045
2021-02-24 06:22:45,717 - DEBUG - Requesting: https://192.168.7.20:8082/virtual-network/800da3e6-7c55-4e66-906e-985310b6b16e
2021-02-24 06:22:45,748 - DEBUG - Requesting: https://192.168.7.20:8082/virtual-network/800da3e6-7c55-4e66-906e-985310b6b16e
2021-02-24 06:22:45,777 - DEBUG - Requesting: https://192.168.7.20:8082/routing-instance/6dc8f270-b088-4e76-b7d1-737757d05f51
2021-02-24 06:22:45,801 - DEBUG - Requesting: https://192.168.7.20:8082/routing-instance/6dc8f270-b088-4e76-b7d1-737757d05f51
2021-02-24 06:22:45,828 - DEBUG - Requesting: https://192.168.7.20:8082/route-target/10c1759a-d257-43f6-810f-b2321a29e394
2021-02-24 06:22:45,853 - DEBUG - Route Targets: ['target:64512:8000036']
2021-02-24 06:22:45,853 - DEBUG - Requesting: https://192.168.7.20:8082/virtual-network/800da3e6-7c55-4e66-906e-985310b6b16e
2021-02-24 06:22:45,881 - DEBUG - Requesting: https://192.168.7.20:8082/routing-instance/6dc8f270-b088-4e76-b7d1-737757d05f51
2021-02-24 06:22:45,925 - INFO - Verified VN network id 47 for VN 800da3e6-7c55-4e66-906e-985310b6b16e
2021-02-24 06:22:45,925 - INFO - Verifications in API Server for VN ctest-right_vn-24695491 passed
2021-02-24 06:22:45,925 - DEBUG - Requesting: https://192.168.7.20:8082/virtual-network/800da3e6-7c55-4e66-906e-985310b6b16e
2021-02-24 06:22:45,954 - DEBUG - Requesting: https://192.168.7.20:8082/routing-instance/6dc8f270-b088-4e76-b7d1-737757d05f51
2021-02-24 06:22:45,984 - DEBUG - Requesting: https://192.168.7.20:8082/routing-instance/6dc8f270-b088-4e76-b7d1-737757d05f51
2021-02-24 06:22:46,011 - DEBUG - Requesting: https://192.168.7.20:8082/route-target/10c1759a-d257-43f6-810f-b2321a29e394
2021-02-24 06:22:46,044 - DEBUG - Requesting: https://192.168.7.20:8083/Snh_IFMapTableShowReq?table_name=virtual-network&search_string=virtual-network:admin_domain:ctest-TestSvcRegr-21662114:ctest-right_vn-24695491
2021-02-24 06:22:46,065 - DEBUG - Control-node 192.168.7.20 : VN object is : {'node_name': 'virtual-network:admin_domain:ctest-TestSvcRegr-21662114:ctest-right_vn-24695491', 'interests': '-', 'advertised': '-', 'dbentryflags': None, 'obj_info': {'sequence_number': '0', 'origin': 'Cassandra', 'data': {'id-perms': {'permissions': {'owner': 'ctest-TestSvcRegr-21662114', 'owner-access': '7', 'group': 'admin', 'group-access': '7', 'other-access': '7'}, 'uuid': {'uuid-mslong': '9227211421875785318', 'uuid-lslong': '10407423271429910894'}, 'enable': 'true', 'created': '2021-02-24T06:22:44', 'last-modified': '2021-02-24T06:22:46', 'description': None, 'user-visible': 'true', 'creator': None}}}, 'neighbors': None, 'last_modified': '00:00:00.807049'}
2021-02-24 06:22:46,065 - DEBUG - Requesting: https://192.168.7.20:8083/Snh_ShowRoutingInstanceReq?name=admin_domain:ctest-TestSvcRegr-21662114:ctest-right_vn-24695491:ctest-right_vn-24695491
2021-02-24 06:22:46,088 - DEBUG - Route Targets: ['target:64512:8000036']
2021-02-24 06:22:46,088 - DEBUG - Requesting: https://192.168.7.29:8083/Snh_IFMapTableShowReq?table_name=virtual-network&search_string=virtual-network:admin_domain:ctest-TestSvcRegr-21662114:ctest-right_vn-24695491
2021-02-24 06:22:46,109 - DEBUG - Control-node 192.168.7.29 : VN object is : {'node_name': 'virtual-network:admin_domain:ctest-TestSvcRegr-21662114:ctest-right_vn-24695491', 'interests': '-', 'advertised': '-', 'dbentryflags': None, 'obj_info': {'sequence_number': '0', 'origin': 'Cassandra', 'data': {'id-perms': {'permissions': {'owner': 'ctest-TestSvcRegr-21662114', 'owner-access': '7', 'group': 'admin', 'group-access': '7', 'other-access': '7'}, 'uuid': {'uuid-mslong': '9227211421875785318', 'uuid-lslong': '10407423271429910894'}, 'enable': 'true', 'created': '2021-02-24T06:22:44', 'last-modified': '2021-02-24T06:22:46', 'description': None, 'user-visible': 'true', 'creator': None}}}, 'neighbors': None, 'last_modified': '00:00:00.851626'}
2021-02-24 06:22:46,109 - DEBUG - Requesting: https://192.168.7.29:8083/Snh_ShowRoutingInstanceReq?name=admin_domain:ctest-TestSvcRegr-21662114:ctest-right_vn-24695491:ctest-right_vn-24695491
2021-02-24 06:22:46,131 - DEBUG - Route Targets: ['target:64512:8000036']
2021-02-24 06:22:46,132 - DEBUG - Requesting: https://192.168.7.34:8083/Snh_IFMapTableShowReq?table_name=virtual-network&search_string=virtual-network:admin_domain:ctest-TestSvcRegr-21662114:ctest-right_vn-24695491
2021-02-24 06:22:46,148 - DEBUG - Control-node 192.168.7.34 : VN object is : {'node_name': 'virtual-network:admin_domain:ctest-TestSvcRegr-21662114:ctest-right_vn-24695491', 'interests': '-', 'advertised': '-', 'dbentryflags': None, 'obj_info': {'sequence_number': '0', 'origin': 'Cassandra', 'data': {'id-perms': {'permissions': {'owner': 'ctest-TestSvcRegr-21662114', 'owner-access': '7', 'group': 'admin', 'group-access': '7', 'other-access': '7'}, 'uuid': {'uuid-mslong': '9227211421875785318', 'uuid-lslong': '10407423271429910894'}, 'enable': 'true', 'created': '2021-02-24T06:22:44', 'last-modified': '2021-02-24T06:22:46', 'description': None, 'user-visible': 'true', 'creator': None}}}, 'neighbors': None, 'last_modified': '00:00:00.891425'}
2021-02-24 06:22:46,149 - DEBUG - Requesting: https://192.168.7.34:8083/Snh_ShowRoutingInstanceReq?name=admin_domain:ctest-TestSvcRegr-21662114:ctest-right_vn-24695491:ctest-right_vn-24695491
2021-02-24 06:22:46,169 - DEBUG - Route Targets: ['target:64512:8000036']
2021-02-24 06:22:46,169 - INFO - On all control nodes, Config, RI and RT verification for VN ctest-right_vn-24695491 passed
2021-02-24 06:22:46,170 - DEBUG - ====Verifying policy data for ctest-right_vn-24695491 in API_Server ======
2021-02-24 06:22:46,170 - DEBUG - Requesting: https://192.168.7.20:8082/domains
2021-02-24 06:22:46,194 - DEBUG - Requesting: https://192.168.7.20:8082/domain/f27c063f-c6c4-434f-a616-97e72e0043e5
2021-02-24 06:22:46,237 - DEBUG - Requesting: https://192.168.7.20:8082/project/7ed682e1-903c-4e87-86f0-68e3ca4e0045
2021-02-24 06:22:46,301 - DEBUG - Requesting: https://192.168.7.20:8082/virtual-network/800da3e6-7c55-4e66-906e-985310b6b16e
2021-02-24 06:22:46,322 - DEBUG - =>VN ctest-right_vn-24695491 has no policy to be verified
2021-02-24 06:22:46,322 - DEBUG - Verifying the vn in opserver
2021-02-24 06:22:46,322 - DEBUG - Verifying the admin_domain:ctest-TestSvcRegr-21662114:ctest-right_vn-24695491 virtual network link  through opserver 192.168.7.20
2021-02-24 06:22:46,323 - DEBUG - Requesting: https://192.168.7.20:8081/analytics/uves/virtual-networks
2021-02-24 06:22:46,545 - DEBUG - vn link and name as {'href': 'https://192.168.7.20:8081/analytics/uves/virtual-network/admin_domain:ctest-TestSvcRegr-21662114:ctest-right_vn-24695491?flat', 'name': 'admin_domain:ctest-TestSvcRegr-21662114:ctest-right_vn-24695491'}
2021-02-24 06:22:46,545 - DEBUG - Verifying the admin_domain:ctest-TestSvcRegr-21662114:ctest-right_vn-24695491 virtual network link  through opserver 192.168.7.29
2021-02-24 06:22:46,546 - DEBUG - Requesting: https://192.168.7.29:8081/analytics/uves/virtual-networks
2021-02-24 06:22:46,777 - DEBUG - vn link and name as {'href': 'https://192.168.7.29:8081/analytics/uves/virtual-network/admin_domain:ctest-TestSvcRegr-21662114:ctest-right_vn-24695491?flat', 'name': 'admin_domain:ctest-TestSvcRegr-21662114:ctest-right_vn-24695491'}
2021-02-24 06:22:46,777 - DEBUG - Verifying the admin_domain:ctest-TestSvcRegr-21662114:ctest-right_vn-24695491 virtual network link  through opserver 192.168.7.34
2021-02-24 06:22:46,777 - DEBUG - Requesting: https://192.168.7.34:8081/analytics/uves/virtual-networks
2021-02-24 06:22:46,954 - DEBUG - vn link and name as {'href': 'https://192.168.7.34:8081/analytics/uves/virtual-network/admin_domain:ctest-TestSvcRegr-21662114:ctest-right_vn-24695491?flat', 'name': 'admin_domain:ctest-TestSvcRegr-21662114:ctest-right_vn-24695491'}
2021-02-24 06:22:46,955 - INFO - Validated that VN admin_domain:ctest-TestSvcRegr-21662114:ctest-right_vn-24695491 is found in opserver
2021-02-24 06:22:47,184 - DEBUG - Do not have enough data to verify VN in agent
2021-02-24 06:22:47,300 - DEBUG - VRF ids for VN ctest-right_vn-24695491: {}
2021-02-24 06:22:47,646 - DEBUG - Services list from nova: [<Service: 1>, <Service: 3>, <Service: 4>, <Service: 16>]
2021-02-24 06:22:49,117 - INFO - VM ([<Server: ctest-left_vm-16805544>]) created on node: (nodec9), Zone: (nova:nodec9)
2021-02-24 06:22:50,896 - INFO - VM ([<Server: ctest-right_vm-86024076>]) created on node: (nodec9), Zone: (nova:nodec9)
2021-02-24 06:22:50,897 - DEBUG - Creating service template: ['admin_domain', 'ctest-service_template_1-27574769']
2021-02-24 06:22:51,077 - DEBUG - Service template: ['admin_domain', 'ctest-service_template_1-27574769'] created succesfully
2021-02-24 06:22:54,128 - INFO - VM ([<Server: ctest-pt_svm0-10372771>]) created on node: (nodec9), Zone: (nova:nodec9)
2021-02-24 06:22:54,129 - INFO - Waiting for VM ctest-pt_svm0-10372771 to be up..
2021-02-24 06:22:54,243 - DEBUG - VM <Server: ctest-pt_svm0-10372771> is still in BUILD state, Expected: ACTIVE
2021-02-24 06:22:59,507 - DEBUG - VM <Server: ctest-pt_svm0-10372771> is still in BUILD state, Expected: ACTIVE
2021-02-24 06:23:04,714 - DEBUG - VM <Server: ctest-pt_svm0-10372771> is still in BUILD state, Expected: ACTIVE
2021-02-24 06:23:09,941 - DEBUG - VM <Server: ctest-pt_svm0-10372771> is still in BUILD state, Expected: ACTIVE
2021-02-24 06:23:15,089 - DEBUG - VM <Server: ctest-pt_svm0-10372771> is in ERROR state now
2021-02-24 06:23:15,090 - ERROR - VM in error state.
2021-02-24 06:23:15,090 - ERROR - VM is not in ACTIVE state
2021-02-24 06:23:15,288 - ERROR - Fatal Nova Exception while getting VM detail
2021-02-24 06:23:15,288 - DEBUG - None
2021-02-24 06:23:15,298 - INFO - Deleting VM ctest-pt_svm0-10372771
2021-02-24 06:23:15,336 - ERROR - VM ctest-pt_svm0-10372771 has failed to come up
2021-02-24 06:23:15,336 - ERROR - Fault seen in nova show <vm-uuid> is:  {'message': 'Unexpected vif_type=unbound', 'code': 500, 'details': 'Traceback (most recent call last):\n  File "/usr/lib/python2.7/dist-packages/nova/compute/manager.py", line 1863, in _do_build_and_run_instance\n    filter_properties, request_spec)\n  File "/usr/lib/python2.7/dist-packages/nova/compute/manager.py", line 2143, in _build_and_run_instance\n    instance_uuid=instance.uuid, reason=six.text_type(e))\nRescheduledException: Build of instance 9e7cbeb8-51c8-44b3-8787-32e4372cc3d0 was re-scheduled: Unexpected vif_type=unbound\n', 'created': '2021-02-24T06:23:12Z'}
2021-02-24 06:23:15,342 - DEBUG - Deleting service template: ['admin_domain', 'ctest-service_template_1-27574769']
2021-02-24 06:23:15,431 - INFO - Service template: ['admin_domain', 'ctest-service_template_1-27574769'] deleted successfully.
2021-02-24 06:23:15,431 - INFO - Deleting VM ctest-right_vm-86024076
2021-02-24 06:23:15,431 - ERROR - VM ctest-right_vm-86024076 has failed to come up
2021-02-24 06:23:15,432 - ERROR - Nova failed to get host of the VM
2021-02-24 06:23:15,769 - INFO - Deleting VM ctest-left_vm-16805544
2021-02-24 06:23:15,769 - ERROR - VM ctest-left_vm-16805544 has failed to come up
2021-02-24 06:23:15,769 - ERROR - Nova failed to get host of the VM
2021-02-24 06:23:16,103 - INFO - Deleting VN ctest-right_vn-24695491 
2021-02-24 06:23:16,205 - DEBUG - VN 800da3e6-7c55-4e66-906e-985310b6b16e still in use: Unable to complete operation on network 800da3e6-7c55-4e66-906e-985310b6b16e. There are one or more ports still in use on the network.
Neutron server returns request_ids: ['req-a615419f-8219-44ed-bbdc-644928223120']
2021-02-24 06:23:16,206 - WARNING - Deleting VN ctest-right_vn-24695491 failed..Will retry
2021-02-24 06:23:18,324 - DEBUG - VN 800da3e6-7c55-4e66-906e-985310b6b16e still in use: Unable to complete operation on network 800da3e6-7c55-4e66-906e-985310b6b16e. There are one or more ports still in use on the network.
Neutron server returns request_ids: ['req-13e28a0f-ddb1-4a70-a96b-aec5c7428c07']
2021-02-24 06:23:18,325 - WARNING - Deleting VN ctest-right_vn-24695491 failed..Will retry
2021-02-24 06:23:20,416 - DEBUG - VN 800da3e6-7c55-4e66-906e-985310b6b16e still in use: Unable to complete operation on network 800da3e6-7c55-4e66-906e-985310b6b16e. There are one or more ports still in use on the network.
Neutron server returns request_ids: ['req-36ccfb94-d2e4-4b5f-bb50-e7703db26fa4']
2021-02-24 06:23:20,417 - WARNING - Deleting VN ctest-right_vn-24695491 failed..Will retry
2021-02-24 06:23:22,506 - DEBUG - VN 800da3e6-7c55-4e66-906e-985310b6b16e still in use: Unable to complete operation on network 800da3e6-7c55-4e66-906e-985310b6b16e. There are one or more ports still in use on the network.
Neutron server returns request_ids: ['req-b6d69ae4-484f-441e-80a4-900fec89adaa']
2021-02-24 06:23:22,507 - WARNING - Deleting VN ctest-right_vn-24695491 failed..Will retry
2021-02-24 06:23:24,610 - DEBUG - VN 800da3e6-7c55-4e66-906e-985310b6b16e still in use: Unable to complete operation on network 800da3e6-7c55-4e66-906e-985310b6b16e. There are one or more ports still in use on the network.
Neutron server returns request_ids: ['req-48d4c66e-44c8-4ded-8052-485c2f2aed13']
2021-02-24 06:23:24,610 - WARNING - Deleting VN ctest-right_vn-24695491 failed..Will retry
2021-02-24 06:23:26,704 - DEBUG - VN 800da3e6-7c55-4e66-906e-985310b6b16e still in use: Unable to complete operation on network 800da3e6-7c55-4e66-906e-985310b6b16e. There are one or more ports still in use on the network.
Neutron server returns request_ids: ['req-710eed83-e8f4-4a87-bca4-76c118b41dc4']
2021-02-24 06:23:26,705 - WARNING - Deleting VN ctest-right_vn-24695491 failed..Will retry
2021-02-24 06:23:28,795 - DEBUG - VN 800da3e6-7c55-4e66-906e-985310b6b16e still in use: Unable to complete operation on network 800da3e6-7c55-4e66-906e-985310b6b16e. There are one or more ports still in use on the network.
Neutron server returns request_ids: ['req-7cbe5ea9-88d6-4a3d-aee8-ef85b88c281e']
2021-02-24 06:23:28,795 - WARNING - Deleting VN ctest-right_vn-24695491 failed..Will retry
2021-02-24 06:23:30,894 - DEBUG - VN 800da3e6-7c55-4e66-906e-985310b6b16e still in use: Unable to complete operation on network 800da3e6-7c55-4e66-906e-985310b6b16e. There are one or more ports still in use on the network.
Neutron server returns request_ids: ['req-bf8f5725-1e0a-4608-9ca5-a7c7ef4b7167']
2021-02-24 06:23:30,895 - WARNING - Deleting VN ctest-right_vn-24695491 failed..Will retry
2021-02-24 06:23:33,038 - DEBUG - VN 800da3e6-7c55-4e66-906e-985310b6b16e still in use: Unable to complete operation on network 800da3e6-7c55-4e66-906e-985310b6b16e. There are one or more ports still in use on the network.
Neutron server returns request_ids: ['req-4195c075-54b3-4cb0-b259-21ebde836427']
2021-02-24 06:23:33,039 - WARNING - Deleting VN ctest-right_vn-24695491 failed..Will retry
2021-02-24 06:23:35,559 - DEBUG - Response for deleting network ()
2021-02-24 06:23:35,559 - DEBUG - Requesting: https://192.168.7.20:8082/routing-instance/6dc8f270-b088-4e76-b7d1-737757d05f51
2021-02-24 06:23:35,584 - DEBUG - Response Code: 404
2021-02-24 06:23:35,584 - DEBUG - Requesting: https://192.168.7.20:8082/domains
2021-02-24 06:23:35,603 - DEBUG - Requesting: https://192.168.7.20:8082/domain/f27c063f-c6c4-434f-a616-97e72e0043e5
2021-02-24 06:23:35,647 - DEBUG - Requesting: https://192.168.7.20:8082/project/7ed682e1-903c-4e87-86f0-68e3ca4e0045
2021-02-24 06:23:35,717 - INFO - Validated that VN ctest-right_vn-24695491 is not found in API Server
2021-02-24 06:23:35,836 - DEBUG - VN ctest-right_vn-24695491 is not present in Agent 192.168.7.19 
2021-02-24 06:23:35,948 - DEBUG - VN ctest-right_vn-24695491 is not present in Agent 192.168.7.9 
2021-02-24 06:23:35,948 - INFO - Validated that VN ctest-right_vn-24695491 is not in any agent
2021-02-24 06:23:36,064 - DEBUG - Requesting: https://192.168.7.20:8083/Snh_ShowRoutingInstanceReq?name=admin_domain:ctest-TestSvcRegr-21662114:ctest-right_vn-24695491:ctest-right_vn-24695491
2021-02-24 06:23:36,125 - DEBUG - Requesting: https://192.168.7.29:8083/Snh_ShowRoutingInstanceReq?name=admin_domain:ctest-TestSvcRegr-21662114:ctest-right_vn-24695491:ctest-right_vn-24695491
2021-02-24 06:23:36,265 - DEBUG - Requesting: https://192.168.7.34:8083/Snh_ShowRoutingInstanceReq?name=admin_domain:ctest-TestSvcRegr-21662114:ctest-right_vn-24695491:ctest-right_vn-24695491
2021-02-24 06:23:36,321 - DEBUG - Requesting: https://192.168.7.34:8083/Snh_IFMapTableShowReq?table_name=virtual-network&search_string=virtual-network:admin_domain:ctest-TestSvcRegr-21662114:ctest-right_vn-24695491
2021-02-24 06:23:36,381 - INFO - Validated that Routing instances and Config db in Control-nodes does not have VN ctest-right_vn-24695491 info
2021-02-24 06:23:36,381 - INFO - Deleting VN ctest-left_vn-16213293 
2021-02-24 06:23:36,711 - DEBUG - Response for deleting network ()
2021-02-24 06:23:36,711 - DEBUG - Requesting: https://192.168.7.20:8082/routing-instance/843c4749-8d6c-4cd3-89c3-312e316f5a01
2021-02-24 06:23:36,733 - DEBUG - Response Code: 404
2021-02-24 06:23:36,733 - DEBUG - Requesting: https://192.168.7.20:8082/domains
2021-02-24 06:23:36,754 - DEBUG - Requesting: https://192.168.7.20:8082/domain/f27c063f-c6c4-434f-a616-97e72e0043e5
2021-02-24 06:23:36,794 - DEBUG - Requesting: https://192.168.7.20:8082/project/7ed682e1-903c-4e87-86f0-68e3ca4e0045
2021-02-24 06:23:36,861 - INFO - Validated that VN ctest-left_vn-16213293 is not found in API Server
2021-02-24 06:23:36,980 - DEBUG - VN ctest-left_vn-16213293 is not present in Agent 192.168.7.19 
2021-02-24 06:23:37,092 - DEBUG - VN ctest-left_vn-16213293 is not present in Agent 192.168.7.9 
2021-02-24 06:23:37,093 - INFO - Validated that VN ctest-left_vn-16213293 is not in any agent
2021-02-24 06:23:37,204 - DEBUG - Requesting: https://192.168.7.20:8083/Snh_ShowRoutingInstanceReq?name=admin_domain:ctest-TestSvcRegr-21662114:ctest-left_vn-16213293:ctest-left_vn-16213293
2021-02-24 06:23:37,264 - DEBUG - Requesting: https://192.168.7.29:8083/Snh_ShowRoutingInstanceReq?name=admin_domain:ctest-TestSvcRegr-21662114:ctest-left_vn-16213293:ctest-left_vn-16213293
2021-02-24 06:23:37,401 - DEBUG - Requesting: https://192.168.7.34:8083/Snh_ShowRoutingInstanceReq?name=admin_domain:ctest-TestSvcRegr-21662114:ctest-left_vn-16213293:ctest-left_vn-16213293
2021-02-24 06:23:37,461 - DEBUG - Requesting: https://192.168.7.34:8083/Snh_IFMapTableShowReq?table_name=virtual-network&search_string=virtual-network:admin_domain:ctest-TestSvcRegr-21662114:ctest-left_vn-16213293
2021-02-24 06:23:37,521 - INFO - Validated that Routing instances and Config db in Control-nodes does not have VN ctest-left_vn-16213293 info
2021-02-24 06:23:37,522 - INFO - Deleting VN ctest-mgmt_vn-33657845 
2021-02-24 06:23:37,800 - DEBUG - Response for deleting network ()
2021-02-24 06:23:37,800 - DEBUG - Requesting: https://192.168.7.20:8082/routing-instance/88bb1444-3ba8-4140-a1f1-d1bb2b3b9493
2021-02-24 06:23:37,819 - DEBUG - Response Code: 404
2021-02-24 06:23:37,819 - DEBUG - Requesting: https://192.168.7.20:8082/domains
2021-02-24 06:23:37,839 - DEBUG - Requesting: https://192.168.7.20:8082/domain/f27c063f-c6c4-434f-a616-97e72e0043e5
2021-02-24 06:23:37,884 - DEBUG - Requesting: https://192.168.7.20:8082/project/7ed682e1-903c-4e87-86f0-68e3ca4e0045
2021-02-24 06:23:37,949 - INFO - Validated that VN ctest-mgmt_vn-33657845 is not found in API Server
2021-02-24 06:23:38,068 - DEBUG - VN ctest-mgmt_vn-33657845 is not present in Agent 192.168.7.19 
2021-02-24 06:23:38,180 - DEBUG - VN ctest-mgmt_vn-33657845 is not present in Agent 192.168.7.9 
2021-02-24 06:23:38,180 - INFO - Validated that VN ctest-mgmt_vn-33657845 is not in any agent
2021-02-24 06:23:38,296 - DEBUG - Requesting: https://192.168.7.20:8083/Snh_ShowRoutingInstanceReq?name=admin_domain:ctest-TestSvcRegr-21662114:ctest-mgmt_vn-33657845:ctest-mgmt_vn-33657845
2021-02-24 06:23:38,357 - DEBUG - Requesting: https://192.168.7.29:8083/Snh_ShowRoutingInstanceReq?name=admin_domain:ctest-TestSvcRegr-21662114:ctest-mgmt_vn-33657845:ctest-mgmt_vn-33657845
2021-02-24 06:23:38,496 - DEBUG - Requesting: https://192.168.7.34:8083/Snh_ShowRoutingInstanceReq?name=admin_domain:ctest-TestSvcRegr-21662114:ctest-mgmt_vn-33657845:ctest-mgmt_vn-33657845
2021-02-24 06:23:38,557 - DEBUG - Requesting: https://192.168.7.34:8083/Snh_IFMapTableShowReq?table_name=virtual-network&search_string=virtual-network:admin_domain:ctest-TestSvcRegr-21662114:ctest-mgmt_vn-33657845
2021-02-24 06:23:38,617 - INFO - Validated that Routing instances and Config db in Control-nodes does not have VN ctest-mgmt_vn-33657845 info
2021-02-24 06:23:41,538 - INFO - Deleted project: ctest-TestSvcRegr-21662114, ID : 7ed682e1-903c-4e87-86f0-68e3ca4e0045 
